// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	usermerchantv1 "github.com/xiongwp/user-merchant-core/kitex_gen/usermerchant/v1"
	v1 "github.com/xiongwp/user-merchant-core/kitex_gen/usermerchant/v1"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newRegisterArgs,
		newRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newLoginArgs,
		newLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"OAuthLogin": kitex.NewMethodInfo(
		oAuthLoginHandler,
		newOAuthLoginArgs,
		newOAuthLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VerifyOTP": kitex.NewMethodInfo(
		verifyOTPHandler,
		newVerifyOTPArgs,
		newVerifyOTPResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SendCode": kitex.NewMethodInfo(
		sendCodeHandler,
		newSendCodeArgs,
		newSendCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VerifyCode": kitex.NewMethodInfo(
		verifyCodeHandler,
		newVerifyCodeArgs,
		newVerifyCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BindIdentity": kitex.NewMethodInfo(
		bindIdentityHandler,
		newBindIdentityArgs,
		newBindIdentityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnbindIdentity": kitex.NewMethodInfo(
		unbindIdentityHandler,
		newUnbindIdentityArgs,
		newUnbindIdentityResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListIdentities": kitex.NewMethodInfo(
		listIdentitiesHandler,
		newListIdentitiesArgs,
		newListIdentitiesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"EnableTOTP": kitex.NewMethodInfo(
		enableTOTPHandler,
		newEnableTOTPArgs,
		newEnableTOTPResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newChangePasswordArgs,
		newChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUser": kitex.NewMethodInfo(
		getUserHandler,
		newGetUserArgs,
		newGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BindUserAccount": kitex.NewMethodInfo(
		bindUserAccountHandler,
		newBindUserAccountArgs,
		newBindUserAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListUserAccounts": kitex.NewMethodInfo(
		listUserAccountsHandler,
		newListUserAccountsArgs,
		newListUserAccountsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"IntrospectToken": kitex.NewMethodInfo(
		introspectTokenHandler,
		newIntrospectTokenArgs,
		newIntrospectTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newLogoutArgs,
		newLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"LogoutAll": kitex.NewMethodInfo(
		logoutAllHandler,
		newLogoutAllArgs,
		newLogoutAllResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"HasPermission": kitex.NewMethodInfo(
		hasPermissionHandler,
		newHasPermissionArgs,
		newHasPermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListPermissions": kitex.NewMethodInfo(
		listPermissionsHandler,
		newListPermissionsArgs,
		newListPermissionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteUser": kitex.NewMethodInfo(
		deleteUserHandler,
		newDeleteUserArgs,
		newDeleteUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*usermerchantv1.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "usermerchant.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RegisterRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).Register(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RegisterArgs:
		success, err := handler.(usermerchantv1.UserService).Register(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RegisterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRegisterArgs() interface{} {
	return &RegisterArgs{}
}

func newRegisterResult() interface{} {
	return &RegisterResult{}
}

type RegisterArgs struct {
	Req *v1.RegisterRequest
}

func (p *RegisterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RegisterArgs) Unmarshal(in []byte) error {
	msg := new(v1.RegisterRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RegisterArgs_Req_DEFAULT *v1.RegisterRequest

func (p *RegisterArgs) GetReq() *v1.RegisterRequest {
	if !p.IsSetReq() {
		return RegisterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RegisterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RegisterResult struct {
	Success *v1.RegisterResponse
}

var RegisterResult_Success_DEFAULT *v1.RegisterResponse

func (p *RegisterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RegisterResult) Unmarshal(in []byte) error {
	msg := new(v1.RegisterResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RegisterResult) GetSuccess() *v1.RegisterResponse {
	if !p.IsSetSuccess() {
		return RegisterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RegisterResponse)
}

func (p *RegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RegisterResult) GetResult() interface{} {
	return p.Success
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.LoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).Login(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginArgs:
		success, err := handler.(usermerchantv1.UserService).Login(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginArgs() interface{} {
	return &LoginArgs{}
}

func newLoginResult() interface{} {
	return &LoginResult{}
}

type LoginArgs struct {
	Req *v1.LoginRequest
}

func (p *LoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginArgs) Unmarshal(in []byte) error {
	msg := new(v1.LoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginArgs_Req_DEFAULT *v1.LoginRequest

func (p *LoginArgs) GetReq() *v1.LoginRequest {
	if !p.IsSetReq() {
		return LoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginResult struct {
	Success *v1.LoginResponse
}

var LoginResult_Success_DEFAULT *v1.LoginResponse

func (p *LoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginResult) Unmarshal(in []byte) error {
	msg := new(v1.LoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginResult) GetSuccess() *v1.LoginResponse {
	if !p.IsSetSuccess() {
		return LoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.LoginResponse)
}

func (p *LoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginResult) GetResult() interface{} {
	return p.Success
}

func oAuthLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.OAuthLoginRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).OAuthLogin(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *OAuthLoginArgs:
		success, err := handler.(usermerchantv1.UserService).OAuthLogin(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*OAuthLoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newOAuthLoginArgs() interface{} {
	return &OAuthLoginArgs{}
}

func newOAuthLoginResult() interface{} {
	return &OAuthLoginResult{}
}

type OAuthLoginArgs struct {
	Req *v1.OAuthLoginRequest
}

func (p *OAuthLoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *OAuthLoginArgs) Unmarshal(in []byte) error {
	msg := new(v1.OAuthLoginRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var OAuthLoginArgs_Req_DEFAULT *v1.OAuthLoginRequest

func (p *OAuthLoginArgs) GetReq() *v1.OAuthLoginRequest {
	if !p.IsSetReq() {
		return OAuthLoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OAuthLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OAuthLoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type OAuthLoginResult struct {
	Success *v1.LoginResponse
}

var OAuthLoginResult_Success_DEFAULT *v1.LoginResponse

func (p *OAuthLoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *OAuthLoginResult) Unmarshal(in []byte) error {
	msg := new(v1.LoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *OAuthLoginResult) GetSuccess() *v1.LoginResponse {
	if !p.IsSetSuccess() {
		return OAuthLoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OAuthLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.LoginResponse)
}

func (p *OAuthLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OAuthLoginResult) GetResult() interface{} {
	return p.Success
}

func verifyOTPHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.VerifyOTPRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).VerifyOTP(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VerifyOTPArgs:
		success, err := handler.(usermerchantv1.UserService).VerifyOTP(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VerifyOTPResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVerifyOTPArgs() interface{} {
	return &VerifyOTPArgs{}
}

func newVerifyOTPResult() interface{} {
	return &VerifyOTPResult{}
}

type VerifyOTPArgs struct {
	Req *v1.VerifyOTPRequest
}

func (p *VerifyOTPArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VerifyOTPArgs) Unmarshal(in []byte) error {
	msg := new(v1.VerifyOTPRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VerifyOTPArgs_Req_DEFAULT *v1.VerifyOTPRequest

func (p *VerifyOTPArgs) GetReq() *v1.VerifyOTPRequest {
	if !p.IsSetReq() {
		return VerifyOTPArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VerifyOTPArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerifyOTPArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VerifyOTPResult struct {
	Success *v1.LoginResponse
}

var VerifyOTPResult_Success_DEFAULT *v1.LoginResponse

func (p *VerifyOTPResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VerifyOTPResult) Unmarshal(in []byte) error {
	msg := new(v1.LoginResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VerifyOTPResult) GetSuccess() *v1.LoginResponse {
	if !p.IsSetSuccess() {
		return VerifyOTPResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VerifyOTPResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.LoginResponse)
}

func (p *VerifyOTPResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyOTPResult) GetResult() interface{} {
	return p.Success
}

func sendCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.SendCodeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).SendCode(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SendCodeArgs:
		success, err := handler.(usermerchantv1.UserService).SendCode(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SendCodeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSendCodeArgs() interface{} {
	return &SendCodeArgs{}
}

func newSendCodeResult() interface{} {
	return &SendCodeResult{}
}

type SendCodeArgs struct {
	Req *v1.SendCodeRequest
}

func (p *SendCodeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SendCodeArgs) Unmarshal(in []byte) error {
	msg := new(v1.SendCodeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SendCodeArgs_Req_DEFAULT *v1.SendCodeRequest

func (p *SendCodeArgs) GetReq() *v1.SendCodeRequest {
	if !p.IsSetReq() {
		return SendCodeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SendCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SendCodeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SendCodeResult struct {
	Success *v1.SendCodeResponse
}

var SendCodeResult_Success_DEFAULT *v1.SendCodeResponse

func (p *SendCodeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SendCodeResult) Unmarshal(in []byte) error {
	msg := new(v1.SendCodeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SendCodeResult) GetSuccess() *v1.SendCodeResponse {
	if !p.IsSetSuccess() {
		return SendCodeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SendCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.SendCodeResponse)
}

func (p *SendCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SendCodeResult) GetResult() interface{} {
	return p.Success
}

func verifyCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.VerifyCodeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).VerifyCode(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VerifyCodeArgs:
		success, err := handler.(usermerchantv1.UserService).VerifyCode(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VerifyCodeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVerifyCodeArgs() interface{} {
	return &VerifyCodeArgs{}
}

func newVerifyCodeResult() interface{} {
	return &VerifyCodeResult{}
}

type VerifyCodeArgs struct {
	Req *v1.VerifyCodeRequest
}

func (p *VerifyCodeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VerifyCodeArgs) Unmarshal(in []byte) error {
	msg := new(v1.VerifyCodeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VerifyCodeArgs_Req_DEFAULT *v1.VerifyCodeRequest

func (p *VerifyCodeArgs) GetReq() *v1.VerifyCodeRequest {
	if !p.IsSetReq() {
		return VerifyCodeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VerifyCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VerifyCodeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VerifyCodeResult struct {
	Success *v1.VerifyCodeResponse
}

var VerifyCodeResult_Success_DEFAULT *v1.VerifyCodeResponse

func (p *VerifyCodeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VerifyCodeResult) Unmarshal(in []byte) error {
	msg := new(v1.VerifyCodeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VerifyCodeResult) GetSuccess() *v1.VerifyCodeResponse {
	if !p.IsSetSuccess() {
		return VerifyCodeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VerifyCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.VerifyCodeResponse)
}

func (p *VerifyCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyCodeResult) GetResult() interface{} {
	return p.Success
}

func bindIdentityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.BindIdentityRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).BindIdentity(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BindIdentityArgs:
		success, err := handler.(usermerchantv1.UserService).BindIdentity(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BindIdentityResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBindIdentityArgs() interface{} {
	return &BindIdentityArgs{}
}

func newBindIdentityResult() interface{} {
	return &BindIdentityResult{}
}

type BindIdentityArgs struct {
	Req *v1.BindIdentityRequest
}

func (p *BindIdentityArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BindIdentityArgs) Unmarshal(in []byte) error {
	msg := new(v1.BindIdentityRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BindIdentityArgs_Req_DEFAULT *v1.BindIdentityRequest

func (p *BindIdentityArgs) GetReq() *v1.BindIdentityRequest {
	if !p.IsSetReq() {
		return BindIdentityArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BindIdentityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BindIdentityArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BindIdentityResult struct {
	Success *v1.BindIdentityResponse
}

var BindIdentityResult_Success_DEFAULT *v1.BindIdentityResponse

func (p *BindIdentityResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BindIdentityResult) Unmarshal(in []byte) error {
	msg := new(v1.BindIdentityResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BindIdentityResult) GetSuccess() *v1.BindIdentityResponse {
	if !p.IsSetSuccess() {
		return BindIdentityResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BindIdentityResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.BindIdentityResponse)
}

func (p *BindIdentityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BindIdentityResult) GetResult() interface{} {
	return p.Success
}

func unbindIdentityHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UnbindIdentityRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).UnbindIdentity(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnbindIdentityArgs:
		success, err := handler.(usermerchantv1.UserService).UnbindIdentity(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnbindIdentityResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnbindIdentityArgs() interface{} {
	return &UnbindIdentityArgs{}
}

func newUnbindIdentityResult() interface{} {
	return &UnbindIdentityResult{}
}

type UnbindIdentityArgs struct {
	Req *v1.UnbindIdentityRequest
}

func (p *UnbindIdentityArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnbindIdentityArgs) Unmarshal(in []byte) error {
	msg := new(v1.UnbindIdentityRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnbindIdentityArgs_Req_DEFAULT *v1.UnbindIdentityRequest

func (p *UnbindIdentityArgs) GetReq() *v1.UnbindIdentityRequest {
	if !p.IsSetReq() {
		return UnbindIdentityArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnbindIdentityArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnbindIdentityArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnbindIdentityResult struct {
	Success *v1.UnbindIdentityResponse
}

var UnbindIdentityResult_Success_DEFAULT *v1.UnbindIdentityResponse

func (p *UnbindIdentityResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnbindIdentityResult) Unmarshal(in []byte) error {
	msg := new(v1.UnbindIdentityResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnbindIdentityResult) GetSuccess() *v1.UnbindIdentityResponse {
	if !p.IsSetSuccess() {
		return UnbindIdentityResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnbindIdentityResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UnbindIdentityResponse)
}

func (p *UnbindIdentityResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnbindIdentityResult) GetResult() interface{} {
	return p.Success
}

func listIdentitiesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListIdentitiesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).ListIdentities(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListIdentitiesArgs:
		success, err := handler.(usermerchantv1.UserService).ListIdentities(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListIdentitiesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListIdentitiesArgs() interface{} {
	return &ListIdentitiesArgs{}
}

func newListIdentitiesResult() interface{} {
	return &ListIdentitiesResult{}
}

type ListIdentitiesArgs struct {
	Req *v1.ListIdentitiesRequest
}

func (p *ListIdentitiesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListIdentitiesArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListIdentitiesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListIdentitiesArgs_Req_DEFAULT *v1.ListIdentitiesRequest

func (p *ListIdentitiesArgs) GetReq() *v1.ListIdentitiesRequest {
	if !p.IsSetReq() {
		return ListIdentitiesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListIdentitiesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListIdentitiesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListIdentitiesResult struct {
	Success *v1.ListIdentitiesResponse
}

var ListIdentitiesResult_Success_DEFAULT *v1.ListIdentitiesResponse

func (p *ListIdentitiesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListIdentitiesResult) Unmarshal(in []byte) error {
	msg := new(v1.ListIdentitiesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListIdentitiesResult) GetSuccess() *v1.ListIdentitiesResponse {
	if !p.IsSetSuccess() {
		return ListIdentitiesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListIdentitiesResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListIdentitiesResponse)
}

func (p *ListIdentitiesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListIdentitiesResult) GetResult() interface{} {
	return p.Success
}

func enableTOTPHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.EnableTOTPRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).EnableTOTP(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EnableTOTPArgs:
		success, err := handler.(usermerchantv1.UserService).EnableTOTP(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EnableTOTPResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEnableTOTPArgs() interface{} {
	return &EnableTOTPArgs{}
}

func newEnableTOTPResult() interface{} {
	return &EnableTOTPResult{}
}

type EnableTOTPArgs struct {
	Req *v1.EnableTOTPRequest
}

func (p *EnableTOTPArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EnableTOTPArgs) Unmarshal(in []byte) error {
	msg := new(v1.EnableTOTPRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EnableTOTPArgs_Req_DEFAULT *v1.EnableTOTPRequest

func (p *EnableTOTPArgs) GetReq() *v1.EnableTOTPRequest {
	if !p.IsSetReq() {
		return EnableTOTPArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EnableTOTPArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EnableTOTPArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EnableTOTPResult struct {
	Success *v1.EnableTOTPResponse
}

var EnableTOTPResult_Success_DEFAULT *v1.EnableTOTPResponse

func (p *EnableTOTPResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EnableTOTPResult) Unmarshal(in []byte) error {
	msg := new(v1.EnableTOTPResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EnableTOTPResult) GetSuccess() *v1.EnableTOTPResponse {
	if !p.IsSetSuccess() {
		return EnableTOTPResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EnableTOTPResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.EnableTOTPResponse)
}

func (p *EnableTOTPResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EnableTOTPResult) GetResult() interface{} {
	return p.Success
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ChangePasswordRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).ChangePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ChangePasswordArgs:
		success, err := handler.(usermerchantv1.UserService).ChangePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newChangePasswordArgs() interface{} {
	return &ChangePasswordArgs{}
}

func newChangePasswordResult() interface{} {
	return &ChangePasswordResult{}
}

type ChangePasswordArgs struct {
	Req *v1.ChangePasswordRequest
}

func (p *ChangePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChangePasswordArgs) Unmarshal(in []byte) error {
	msg := new(v1.ChangePasswordRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangePasswordArgs_Req_DEFAULT *v1.ChangePasswordRequest

func (p *ChangePasswordArgs) GetReq() *v1.ChangePasswordRequest {
	if !p.IsSetReq() {
		return ChangePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangePasswordResult struct {
	Success *v1.ChangePasswordResponse
}

var ChangePasswordResult_Success_DEFAULT *v1.ChangePasswordResponse

func (p *ChangePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChangePasswordResult) Unmarshal(in []byte) error {
	msg := new(v1.ChangePasswordResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangePasswordResult) GetSuccess() *v1.ChangePasswordResponse {
	if !p.IsSetSuccess() {
		return ChangePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ChangePasswordResponse)
}

func (p *ChangePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangePasswordResult) GetResult() interface{} {
	return p.Success
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).GetUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserArgs:
		success, err := handler.(usermerchantv1.UserService).GetUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserArgs() interface{} {
	return &GetUserArgs{}
}

func newGetUserResult() interface{} {
	return &GetUserResult{}
}

type GetUserArgs struct {
	Req *v1.GetUserRequest
}

func (p *GetUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserArgs_Req_DEFAULT *v1.GetUserRequest

func (p *GetUserArgs) GetReq() *v1.GetUserRequest {
	if !p.IsSetReq() {
		return GetUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserResult struct {
	Success *v1.User
}

var GetUserResult_Success_DEFAULT *v1.User

func (p *GetUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserResult) Unmarshal(in []byte) error {
	msg := new(v1.User)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserResult) GetSuccess() *v1.User {
	if !p.IsSetSuccess() {
		return GetUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.User)
}

func (p *GetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserResult) GetResult() interface{} {
	return p.Success
}

func bindUserAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.BindUserAccountRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).BindUserAccount(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BindUserAccountArgs:
		success, err := handler.(usermerchantv1.UserService).BindUserAccount(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BindUserAccountResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBindUserAccountArgs() interface{} {
	return &BindUserAccountArgs{}
}

func newBindUserAccountResult() interface{} {
	return &BindUserAccountResult{}
}

type BindUserAccountArgs struct {
	Req *v1.BindUserAccountRequest
}

func (p *BindUserAccountArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BindUserAccountArgs) Unmarshal(in []byte) error {
	msg := new(v1.BindUserAccountRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BindUserAccountArgs_Req_DEFAULT *v1.BindUserAccountRequest

func (p *BindUserAccountArgs) GetReq() *v1.BindUserAccountRequest {
	if !p.IsSetReq() {
		return BindUserAccountArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BindUserAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BindUserAccountArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BindUserAccountResult struct {
	Success *v1.BindUserAccountResponse
}

var BindUserAccountResult_Success_DEFAULT *v1.BindUserAccountResponse

func (p *BindUserAccountResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BindUserAccountResult) Unmarshal(in []byte) error {
	msg := new(v1.BindUserAccountResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BindUserAccountResult) GetSuccess() *v1.BindUserAccountResponse {
	if !p.IsSetSuccess() {
		return BindUserAccountResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BindUserAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.BindUserAccountResponse)
}

func (p *BindUserAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BindUserAccountResult) GetResult() interface{} {
	return p.Success
}

func listUserAccountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListUserAccountsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).ListUserAccounts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListUserAccountsArgs:
		success, err := handler.(usermerchantv1.UserService).ListUserAccounts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListUserAccountsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListUserAccountsArgs() interface{} {
	return &ListUserAccountsArgs{}
}

func newListUserAccountsResult() interface{} {
	return &ListUserAccountsResult{}
}

type ListUserAccountsArgs struct {
	Req *v1.ListUserAccountsRequest
}

func (p *ListUserAccountsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListUserAccountsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListUserAccountsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListUserAccountsArgs_Req_DEFAULT *v1.ListUserAccountsRequest

func (p *ListUserAccountsArgs) GetReq() *v1.ListUserAccountsRequest {
	if !p.IsSetReq() {
		return ListUserAccountsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListUserAccountsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListUserAccountsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListUserAccountsResult struct {
	Success *v1.ListUserAccountsResponse
}

var ListUserAccountsResult_Success_DEFAULT *v1.ListUserAccountsResponse

func (p *ListUserAccountsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListUserAccountsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListUserAccountsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListUserAccountsResult) GetSuccess() *v1.ListUserAccountsResponse {
	if !p.IsSetSuccess() {
		return ListUserAccountsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListUserAccountsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListUserAccountsResponse)
}

func (p *ListUserAccountsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListUserAccountsResult) GetResult() interface{} {
	return p.Success
}

func introspectTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.IntrospectTokenRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).IntrospectToken(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *IntrospectTokenArgs:
		success, err := handler.(usermerchantv1.UserService).IntrospectToken(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*IntrospectTokenResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newIntrospectTokenArgs() interface{} {
	return &IntrospectTokenArgs{}
}

func newIntrospectTokenResult() interface{} {
	return &IntrospectTokenResult{}
}

type IntrospectTokenArgs struct {
	Req *v1.IntrospectTokenRequest
}

func (p *IntrospectTokenArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *IntrospectTokenArgs) Unmarshal(in []byte) error {
	msg := new(v1.IntrospectTokenRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var IntrospectTokenArgs_Req_DEFAULT *v1.IntrospectTokenRequest

func (p *IntrospectTokenArgs) GetReq() *v1.IntrospectTokenRequest {
	if !p.IsSetReq() {
		return IntrospectTokenArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *IntrospectTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IntrospectTokenArgs) GetFirstArgument() interface{} {
	return p.Req
}

type IntrospectTokenResult struct {
	Success *v1.IntrospectTokenResponse
}

var IntrospectTokenResult_Success_DEFAULT *v1.IntrospectTokenResponse

func (p *IntrospectTokenResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *IntrospectTokenResult) Unmarshal(in []byte) error {
	msg := new(v1.IntrospectTokenResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *IntrospectTokenResult) GetSuccess() *v1.IntrospectTokenResponse {
	if !p.IsSetSuccess() {
		return IntrospectTokenResult_Success_DEFAULT
	}
	return p.Success
}

func (p *IntrospectTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.IntrospectTokenResponse)
}

func (p *IntrospectTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IntrospectTokenResult) GetResult() interface{} {
	return p.Success
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.LogoutRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).Logout(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LogoutArgs:
		success, err := handler.(usermerchantv1.UserService).Logout(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LogoutResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLogoutArgs() interface{} {
	return &LogoutArgs{}
}

func newLogoutResult() interface{} {
	return &LogoutResult{}
}

type LogoutArgs struct {
	Req *v1.LogoutRequest
}

func (p *LogoutArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LogoutArgs) Unmarshal(in []byte) error {
	msg := new(v1.LogoutRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LogoutArgs_Req_DEFAULT *v1.LogoutRequest

func (p *LogoutArgs) GetReq() *v1.LogoutRequest {
	if !p.IsSetReq() {
		return LogoutArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LogoutArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LogoutResult struct {
	Success *v1.LogoutResponse
}

var LogoutResult_Success_DEFAULT *v1.LogoutResponse

func (p *LogoutResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LogoutResult) Unmarshal(in []byte) error {
	msg := new(v1.LogoutResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LogoutResult) GetSuccess() *v1.LogoutResponse {
	if !p.IsSetSuccess() {
		return LogoutResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.LogoutResponse)
}

func (p *LogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LogoutResult) GetResult() interface{} {
	return p.Success
}

func logoutAllHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.LogoutAllRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).LogoutAll(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LogoutAllArgs:
		success, err := handler.(usermerchantv1.UserService).LogoutAll(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LogoutAllResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLogoutAllArgs() interface{} {
	return &LogoutAllArgs{}
}

func newLogoutAllResult() interface{} {
	return &LogoutAllResult{}
}

type LogoutAllArgs struct {
	Req *v1.LogoutAllRequest
}

func (p *LogoutAllArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LogoutAllArgs) Unmarshal(in []byte) error {
	msg := new(v1.LogoutAllRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LogoutAllArgs_Req_DEFAULT *v1.LogoutAllRequest

func (p *LogoutAllArgs) GetReq() *v1.LogoutAllRequest {
	if !p.IsSetReq() {
		return LogoutAllArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LogoutAllArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LogoutAllArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LogoutAllResult struct {
	Success *v1.LogoutResponse
}

var LogoutAllResult_Success_DEFAULT *v1.LogoutResponse

func (p *LogoutAllResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LogoutAllResult) Unmarshal(in []byte) error {
	msg := new(v1.LogoutResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LogoutAllResult) GetSuccess() *v1.LogoutResponse {
	if !p.IsSetSuccess() {
		return LogoutAllResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LogoutAllResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.LogoutResponse)
}

func (p *LogoutAllResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LogoutAllResult) GetResult() interface{} {
	return p.Success
}

func hasPermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.HasPermissionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).HasPermission(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HasPermissionArgs:
		success, err := handler.(usermerchantv1.UserService).HasPermission(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HasPermissionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHasPermissionArgs() interface{} {
	return &HasPermissionArgs{}
}

func newHasPermissionResult() interface{} {
	return &HasPermissionResult{}
}

type HasPermissionArgs struct {
	Req *v1.HasPermissionRequest
}

func (p *HasPermissionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HasPermissionArgs) Unmarshal(in []byte) error {
	msg := new(v1.HasPermissionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HasPermissionArgs_Req_DEFAULT *v1.HasPermissionRequest

func (p *HasPermissionArgs) GetReq() *v1.HasPermissionRequest {
	if !p.IsSetReq() {
		return HasPermissionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HasPermissionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HasPermissionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HasPermissionResult struct {
	Success *v1.HasPermissionResponse
}

var HasPermissionResult_Success_DEFAULT *v1.HasPermissionResponse

func (p *HasPermissionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HasPermissionResult) Unmarshal(in []byte) error {
	msg := new(v1.HasPermissionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HasPermissionResult) GetSuccess() *v1.HasPermissionResponse {
	if !p.IsSetSuccess() {
		return HasPermissionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HasPermissionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.HasPermissionResponse)
}

func (p *HasPermissionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HasPermissionResult) GetResult() interface{} {
	return p.Success
}

func listPermissionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListPermissionsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).ListPermissions(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListPermissionsArgs:
		success, err := handler.(usermerchantv1.UserService).ListPermissions(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListPermissionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListPermissionsArgs() interface{} {
	return &ListPermissionsArgs{}
}

func newListPermissionsResult() interface{} {
	return &ListPermissionsResult{}
}

type ListPermissionsArgs struct {
	Req *v1.ListPermissionsRequest
}

func (p *ListPermissionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListPermissionsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListPermissionsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListPermissionsArgs_Req_DEFAULT *v1.ListPermissionsRequest

func (p *ListPermissionsArgs) GetReq() *v1.ListPermissionsRequest {
	if !p.IsSetReq() {
		return ListPermissionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListPermissionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListPermissionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListPermissionsResult struct {
	Success *v1.ListPermissionsResponse
}

var ListPermissionsResult_Success_DEFAULT *v1.ListPermissionsResponse

func (p *ListPermissionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListPermissionsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListPermissionsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListPermissionsResult) GetSuccess() *v1.ListPermissionsResponse {
	if !p.IsSetSuccess() {
		return ListPermissionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListPermissionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListPermissionsResponse)
}

func (p *ListPermissionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListPermissionsResult) GetResult() interface{} {
	return p.Success
}

func deleteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeleteUserRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.UserService).DeleteUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteUserArgs:
		success, err := handler.(usermerchantv1.UserService).DeleteUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteUserArgs() interface{} {
	return &DeleteUserArgs{}
}

func newDeleteUserResult() interface{} {
	return &DeleteUserResult{}
}

type DeleteUserArgs struct {
	Req *v1.DeleteUserRequest
}

func (p *DeleteUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteUserArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeleteUserRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteUserArgs_Req_DEFAULT *v1.DeleteUserRequest

func (p *DeleteUserArgs) GetReq() *v1.DeleteUserRequest {
	if !p.IsSetReq() {
		return DeleteUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteUserResult struct {
	Success *v1.DeleteUserResponse
}

var DeleteUserResult_Success_DEFAULT *v1.DeleteUserResponse

func (p *DeleteUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteUserResult) Unmarshal(in []byte) error {
	msg := new(v1.DeleteUserResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteUserResult) GetSuccess() *v1.DeleteUserResponse {
	if !p.IsSetSuccess() {
		return DeleteUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DeleteUserResponse)
}

func (p *DeleteUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteUserResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, Req *v1.RegisterRequest) (r *v1.RegisterResponse, err error) {
	var _args RegisterArgs
	_args.Req = Req
	var _result RegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, Req *v1.LoginRequest) (r *v1.LoginResponse, err error) {
	var _args LoginArgs
	_args.Req = Req
	var _result LoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OAuthLogin(ctx context.Context, Req *v1.OAuthLoginRequest) (r *v1.LoginResponse, err error) {
	var _args OAuthLoginArgs
	_args.Req = Req
	var _result OAuthLoginResult
	if err = p.c.Call(ctx, "OAuthLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyOTP(ctx context.Context, Req *v1.VerifyOTPRequest) (r *v1.LoginResponse, err error) {
	var _args VerifyOTPArgs
	_args.Req = Req
	var _result VerifyOTPResult
	if err = p.c.Call(ctx, "VerifyOTP", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendCode(ctx context.Context, Req *v1.SendCodeRequest) (r *v1.SendCodeResponse, err error) {
	var _args SendCodeArgs
	_args.Req = Req
	var _result SendCodeResult
	if err = p.c.Call(ctx, "SendCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VerifyCode(ctx context.Context, Req *v1.VerifyCodeRequest) (r *v1.VerifyCodeResponse, err error) {
	var _args VerifyCodeArgs
	_args.Req = Req
	var _result VerifyCodeResult
	if err = p.c.Call(ctx, "VerifyCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindIdentity(ctx context.Context, Req *v1.BindIdentityRequest) (r *v1.BindIdentityResponse, err error) {
	var _args BindIdentityArgs
	_args.Req = Req
	var _result BindIdentityResult
	if err = p.c.Call(ctx, "BindIdentity", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnbindIdentity(ctx context.Context, Req *v1.UnbindIdentityRequest) (r *v1.UnbindIdentityResponse, err error) {
	var _args UnbindIdentityArgs
	_args.Req = Req
	var _result UnbindIdentityResult
	if err = p.c.Call(ctx, "UnbindIdentity", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListIdentities(ctx context.Context, Req *v1.ListIdentitiesRequest) (r *v1.ListIdentitiesResponse, err error) {
	var _args ListIdentitiesArgs
	_args.Req = Req
	var _result ListIdentitiesResult
	if err = p.c.Call(ctx, "ListIdentities", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EnableTOTP(ctx context.Context, Req *v1.EnableTOTPRequest) (r *v1.EnableTOTPResponse, err error) {
	var _args EnableTOTPArgs
	_args.Req = Req
	var _result EnableTOTPResult
	if err = p.c.Call(ctx, "EnableTOTP", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, Req *v1.ChangePasswordRequest) (r *v1.ChangePasswordResponse, err error) {
	var _args ChangePasswordArgs
	_args.Req = Req
	var _result ChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, Req *v1.GetUserRequest) (r *v1.User, err error) {
	var _args GetUserArgs
	_args.Req = Req
	var _result GetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindUserAccount(ctx context.Context, Req *v1.BindUserAccountRequest) (r *v1.BindUserAccountResponse, err error) {
	var _args BindUserAccountArgs
	_args.Req = Req
	var _result BindUserAccountResult
	if err = p.c.Call(ctx, "BindUserAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListUserAccounts(ctx context.Context, Req *v1.ListUserAccountsRequest) (r *v1.ListUserAccountsResponse, err error) {
	var _args ListUserAccountsArgs
	_args.Req = Req
	var _result ListUserAccountsResult
	if err = p.c.Call(ctx, "ListUserAccounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IntrospectToken(ctx context.Context, Req *v1.IntrospectTokenRequest) (r *v1.IntrospectTokenResponse, err error) {
	var _args IntrospectTokenArgs
	_args.Req = Req
	var _result IntrospectTokenResult
	if err = p.c.Call(ctx, "IntrospectToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, Req *v1.LogoutRequest) (r *v1.LogoutResponse, err error) {
	var _args LogoutArgs
	_args.Req = Req
	var _result LogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LogoutAll(ctx context.Context, Req *v1.LogoutAllRequest) (r *v1.LogoutResponse, err error) {
	var _args LogoutAllArgs
	_args.Req = Req
	var _result LogoutAllResult
	if err = p.c.Call(ctx, "LogoutAll", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HasPermission(ctx context.Context, Req *v1.HasPermissionRequest) (r *v1.HasPermissionResponse, err error) {
	var _args HasPermissionArgs
	_args.Req = Req
	var _result HasPermissionResult
	if err = p.c.Call(ctx, "HasPermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListPermissions(ctx context.Context, Req *v1.ListPermissionsRequest) (r *v1.ListPermissionsResponse, err error) {
	var _args ListPermissionsArgs
	_args.Req = Req
	var _result ListPermissionsResult
	if err = p.c.Call(ctx, "ListPermissions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUser(ctx context.Context, Req *v1.DeleteUserRequest) (r *v1.DeleteUserResponse, err error) {
	var _args DeleteUserArgs
	_args.Req = Req
	var _result DeleteUserResult
	if err = p.c.Call(ctx, "DeleteUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
