// Code generated by Kitex v0.16.2. DO NOT EDIT.

package chargeservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	orderv1 "github.com/xiongwp/order-core/kitex_gen/order/v1"
	v1 "github.com/xiongwp/order-core/kitex_gen/order/v1"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Retrieve": kitex.NewMethodInfo(
		retrieveHandler,
		newRetrieveArgs,
		newRetrieveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"List": kitex.NewMethodInfo(
		listHandler,
		newListArgs,
		newListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	chargeServiceServiceInfo                = NewServiceInfo()
	chargeServiceServiceInfoForClient       = NewServiceInfoForClient()
	chargeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chargeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chargeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chargeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChargeService"
	handlerType := (*orderv1.ChargeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func retrieveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RetrieveChargeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.ChargeService).Retrieve(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RetrieveArgs:
		success, err := handler.(orderv1.ChargeService).Retrieve(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RetrieveResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRetrieveArgs() interface{} {
	return &RetrieveArgs{}
}

func newRetrieveResult() interface{} {
	return &RetrieveResult{}
}

type RetrieveArgs struct {
	Req *v1.RetrieveChargeRequest
}

func (p *RetrieveArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RetrieveArgs) Unmarshal(in []byte) error {
	msg := new(v1.RetrieveChargeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RetrieveArgs_Req_DEFAULT *v1.RetrieveChargeRequest

func (p *RetrieveArgs) GetReq() *v1.RetrieveChargeRequest {
	if !p.IsSetReq() {
		return RetrieveArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RetrieveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RetrieveArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RetrieveResult struct {
	Success *v1.RetrieveChargeResponse
}

var RetrieveResult_Success_DEFAULT *v1.RetrieveChargeResponse

func (p *RetrieveResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RetrieveResult) Unmarshal(in []byte) error {
	msg := new(v1.RetrieveChargeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RetrieveResult) GetSuccess() *v1.RetrieveChargeResponse {
	if !p.IsSetSuccess() {
		return RetrieveResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RetrieveResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RetrieveChargeResponse)
}

func (p *RetrieveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RetrieveResult) GetResult() interface{} {
	return p.Success
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListChargesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.ChargeService).List(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListArgs:
		success, err := handler.(orderv1.ChargeService).List(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListArgs() interface{} {
	return &ListArgs{}
}

func newListResult() interface{} {
	return &ListResult{}
}

type ListArgs struct {
	Req *v1.ListChargesRequest
}

func (p *ListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListChargesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListArgs_Req_DEFAULT *v1.ListChargesRequest

func (p *ListArgs) GetReq() *v1.ListChargesRequest {
	if !p.IsSetReq() {
		return ListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListResult struct {
	Success *v1.ListChargesResponse
}

var ListResult_Success_DEFAULT *v1.ListChargesResponse

func (p *ListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListResult) Unmarshal(in []byte) error {
	msg := new(v1.ListChargesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListResult) GetSuccess() *v1.ListChargesResponse {
	if !p.IsSetSuccess() {
		return ListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListChargesResponse)
}

func (p *ListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Retrieve(ctx context.Context, Req *v1.RetrieveChargeRequest) (r *v1.RetrieveChargeResponse, err error) {
	var _args RetrieveArgs
	_args.Req = Req
	var _result RetrieveResult
	if err = p.c.Call(ctx, "Retrieve", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, Req *v1.ListChargesRequest) (r *v1.ListChargesResponse, err error) {
	var _args ListArgs
	_args.Req = Req
	var _result ListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
