// Code generated by Kitex v0.16.2. DO NOT EDIT.
package freezeservice

import (
	server "github.com/cloudwego/kitex/server"
	accountingv1 "github.com/xiongwp/accounting-system/kitex_gen/accounting/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler accountingv1.FreezeService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler accountingv1.FreezeService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
