// Code generated by Kitex v0.16.2. DO NOT EDIT.

package transactionservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	v1 "github.com/xiongwp/accounting-system/kitex_gen/accounting/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	DoubleEntryBooking(ctx context.Context, Req *v1.DoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.DoubleEntryBookingResponse, err error)
	BatchBooking(ctx context.Context, Req *v1.BatchBookingRequest, callOptions ...callopt.Option) (r *v1.BatchBookingResponse, err error)
	HybridDoubleEntryBooking(ctx context.Context, Req *v1.HybridDoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.HybridDoubleEntryBookingResponse, err error)
	AtomicBatchBooking(ctx context.Context, Req *v1.AtomicBatchBookingRequest, callOptions ...callopt.Option) (r *v1.AtomicBatchBookingResponse, err error)
	GetTransaction(ctx context.Context, Req *v1.GetTransactionRequest, callOptions ...callopt.Option) (r *v1.GetTransactionResponse, err error)
	CreateTransaction(ctx context.Context, Req *v1.CreateTransactionRequest, callOptions ...callopt.Option) (r *v1.CreateTransactionResponse, err error)
	ListAccountTypes(ctx context.Context, Req *v1.ListAccountTypesRequest, callOptions ...callopt.Option) (r *v1.ListAccountTypesResponse, err error)
	ListTransactionRules(ctx context.Context, Req *v1.ListTransactionRulesRequest, callOptions ...callopt.Option) (r *v1.ListTransactionRulesResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTransactionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTransactionServiceClient struct {
	*kClient
}

func (p *kTransactionServiceClient) DoubleEntryBooking(ctx context.Context, Req *v1.DoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.DoubleEntryBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DoubleEntryBooking(ctx, Req)
}

func (p *kTransactionServiceClient) BatchBooking(ctx context.Context, Req *v1.BatchBookingRequest, callOptions ...callopt.Option) (r *v1.BatchBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchBooking(ctx, Req)
}

func (p *kTransactionServiceClient) HybridDoubleEntryBooking(ctx context.Context, Req *v1.HybridDoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.HybridDoubleEntryBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HybridDoubleEntryBooking(ctx, Req)
}

func (p *kTransactionServiceClient) AtomicBatchBooking(ctx context.Context, Req *v1.AtomicBatchBookingRequest, callOptions ...callopt.Option) (r *v1.AtomicBatchBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AtomicBatchBooking(ctx, Req)
}

func (p *kTransactionServiceClient) GetTransaction(ctx context.Context, Req *v1.GetTransactionRequest, callOptions ...callopt.Option) (r *v1.GetTransactionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTransaction(ctx, Req)
}

func (p *kTransactionServiceClient) CreateTransaction(ctx context.Context, Req *v1.CreateTransactionRequest, callOptions ...callopt.Option) (r *v1.CreateTransactionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTransaction(ctx, Req)
}

func (p *kTransactionServiceClient) ListAccountTypes(ctx context.Context, Req *v1.ListAccountTypesRequest, callOptions ...callopt.Option) (r *v1.ListAccountTypesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAccountTypes(ctx, Req)
}

func (p *kTransactionServiceClient) ListTransactionRules(ctx context.Context, Req *v1.ListTransactionRulesRequest, callOptions ...callopt.Option) (r *v1.ListTransactionRulesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTransactionRules(ctx, Req)
}
