-- user_merchant_db_6 的影子表（压测 / shadow 流量）
-- 依赖：6_init.sql 已经导入完成（CREATE TABLE LIKE 需要主表存在）。
SET NAMES utf8mb4;
USE `user_merchant_db_6`;

CREATE TABLE IF NOT EXISTS `users_60_shadow` LIKE `users_60`;
CREATE TABLE IF NOT EXISTS `user_profiles_60_shadow` LIKE `user_profiles_60`;
CREATE TABLE IF NOT EXISTS `user_auths_60_shadow` LIKE `user_auths_60`;
CREATE TABLE IF NOT EXISTS `login_logs_60_shadow` LIKE `login_logs_60`;
CREATE TABLE IF NOT EXISTS `user_sessions_60_shadow` LIKE `user_sessions_60`;
CREATE TABLE IF NOT EXISTS `user_roles_60_shadow` LIKE `user_roles_60`;
CREATE TABLE IF NOT EXISTS `user_accounts_60_shadow` LIKE `user_accounts_60`;
CREATE TABLE IF NOT EXISTS `user_settings_60_shadow` LIKE `user_settings_60`;
CREATE TABLE IF NOT EXISTS `user_card_60_shadow` LIKE `user_card_60`;
CREATE TABLE IF NOT EXISTS `merchants_60_shadow` LIKE `merchants_60`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_60_shadow` LIKE `merchant_kyc_document_60`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_60_shadow` LIKE `merchant_channel_secret_60`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_60_shadow` LIKE `admin_audit_log_60`;

CREATE TABLE IF NOT EXISTS `users_61_shadow` LIKE `users_61`;
CREATE TABLE IF NOT EXISTS `user_profiles_61_shadow` LIKE `user_profiles_61`;
CREATE TABLE IF NOT EXISTS `user_auths_61_shadow` LIKE `user_auths_61`;
CREATE TABLE IF NOT EXISTS `login_logs_61_shadow` LIKE `login_logs_61`;
CREATE TABLE IF NOT EXISTS `user_sessions_61_shadow` LIKE `user_sessions_61`;
CREATE TABLE IF NOT EXISTS `user_roles_61_shadow` LIKE `user_roles_61`;
CREATE TABLE IF NOT EXISTS `user_accounts_61_shadow` LIKE `user_accounts_61`;
CREATE TABLE IF NOT EXISTS `user_settings_61_shadow` LIKE `user_settings_61`;
CREATE TABLE IF NOT EXISTS `user_card_61_shadow` LIKE `user_card_61`;
CREATE TABLE IF NOT EXISTS `merchants_61_shadow` LIKE `merchants_61`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_61_shadow` LIKE `merchant_kyc_document_61`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_61_shadow` LIKE `merchant_channel_secret_61`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_61_shadow` LIKE `admin_audit_log_61`;

CREATE TABLE IF NOT EXISTS `users_62_shadow` LIKE `users_62`;
CREATE TABLE IF NOT EXISTS `user_profiles_62_shadow` LIKE `user_profiles_62`;
CREATE TABLE IF NOT EXISTS `user_auths_62_shadow` LIKE `user_auths_62`;
CREATE TABLE IF NOT EXISTS `login_logs_62_shadow` LIKE `login_logs_62`;
CREATE TABLE IF NOT EXISTS `user_sessions_62_shadow` LIKE `user_sessions_62`;
CREATE TABLE IF NOT EXISTS `user_roles_62_shadow` LIKE `user_roles_62`;
CREATE TABLE IF NOT EXISTS `user_accounts_62_shadow` LIKE `user_accounts_62`;
CREATE TABLE IF NOT EXISTS `user_settings_62_shadow` LIKE `user_settings_62`;
CREATE TABLE IF NOT EXISTS `user_card_62_shadow` LIKE `user_card_62`;
CREATE TABLE IF NOT EXISTS `merchants_62_shadow` LIKE `merchants_62`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_62_shadow` LIKE `merchant_kyc_document_62`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_62_shadow` LIKE `merchant_channel_secret_62`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_62_shadow` LIKE `admin_audit_log_62`;

CREATE TABLE IF NOT EXISTS `users_63_shadow` LIKE `users_63`;
CREATE TABLE IF NOT EXISTS `user_profiles_63_shadow` LIKE `user_profiles_63`;
CREATE TABLE IF NOT EXISTS `user_auths_63_shadow` LIKE `user_auths_63`;
CREATE TABLE IF NOT EXISTS `login_logs_63_shadow` LIKE `login_logs_63`;
CREATE TABLE IF NOT EXISTS `user_sessions_63_shadow` LIKE `user_sessions_63`;
CREATE TABLE IF NOT EXISTS `user_roles_63_shadow` LIKE `user_roles_63`;
CREATE TABLE IF NOT EXISTS `user_accounts_63_shadow` LIKE `user_accounts_63`;
CREATE TABLE IF NOT EXISTS `user_settings_63_shadow` LIKE `user_settings_63`;
CREATE TABLE IF NOT EXISTS `user_card_63_shadow` LIKE `user_card_63`;
CREATE TABLE IF NOT EXISTS `merchants_63_shadow` LIKE `merchants_63`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_63_shadow` LIKE `merchant_kyc_document_63`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_63_shadow` LIKE `merchant_channel_secret_63`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_63_shadow` LIKE `admin_audit_log_63`;

CREATE TABLE IF NOT EXISTS `users_64_shadow` LIKE `users_64`;
CREATE TABLE IF NOT EXISTS `user_profiles_64_shadow` LIKE `user_profiles_64`;
CREATE TABLE IF NOT EXISTS `user_auths_64_shadow` LIKE `user_auths_64`;
CREATE TABLE IF NOT EXISTS `login_logs_64_shadow` LIKE `login_logs_64`;
CREATE TABLE IF NOT EXISTS `user_sessions_64_shadow` LIKE `user_sessions_64`;
CREATE TABLE IF NOT EXISTS `user_roles_64_shadow` LIKE `user_roles_64`;
CREATE TABLE IF NOT EXISTS `user_accounts_64_shadow` LIKE `user_accounts_64`;
CREATE TABLE IF NOT EXISTS `user_settings_64_shadow` LIKE `user_settings_64`;
CREATE TABLE IF NOT EXISTS `user_card_64_shadow` LIKE `user_card_64`;
CREATE TABLE IF NOT EXISTS `merchants_64_shadow` LIKE `merchants_64`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_64_shadow` LIKE `merchant_kyc_document_64`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_64_shadow` LIKE `merchant_channel_secret_64`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_64_shadow` LIKE `admin_audit_log_64`;

CREATE TABLE IF NOT EXISTS `users_65_shadow` LIKE `users_65`;
CREATE TABLE IF NOT EXISTS `user_profiles_65_shadow` LIKE `user_profiles_65`;
CREATE TABLE IF NOT EXISTS `user_auths_65_shadow` LIKE `user_auths_65`;
CREATE TABLE IF NOT EXISTS `login_logs_65_shadow` LIKE `login_logs_65`;
CREATE TABLE IF NOT EXISTS `user_sessions_65_shadow` LIKE `user_sessions_65`;
CREATE TABLE IF NOT EXISTS `user_roles_65_shadow` LIKE `user_roles_65`;
CREATE TABLE IF NOT EXISTS `user_accounts_65_shadow` LIKE `user_accounts_65`;
CREATE TABLE IF NOT EXISTS `user_settings_65_shadow` LIKE `user_settings_65`;
CREATE TABLE IF NOT EXISTS `user_card_65_shadow` LIKE `user_card_65`;
CREATE TABLE IF NOT EXISTS `merchants_65_shadow` LIKE `merchants_65`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_65_shadow` LIKE `merchant_kyc_document_65`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_65_shadow` LIKE `merchant_channel_secret_65`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_65_shadow` LIKE `admin_audit_log_65`;

CREATE TABLE IF NOT EXISTS `users_66_shadow` LIKE `users_66`;
CREATE TABLE IF NOT EXISTS `user_profiles_66_shadow` LIKE `user_profiles_66`;
CREATE TABLE IF NOT EXISTS `user_auths_66_shadow` LIKE `user_auths_66`;
CREATE TABLE IF NOT EXISTS `login_logs_66_shadow` LIKE `login_logs_66`;
CREATE TABLE IF NOT EXISTS `user_sessions_66_shadow` LIKE `user_sessions_66`;
CREATE TABLE IF NOT EXISTS `user_roles_66_shadow` LIKE `user_roles_66`;
CREATE TABLE IF NOT EXISTS `user_accounts_66_shadow` LIKE `user_accounts_66`;
CREATE TABLE IF NOT EXISTS `user_settings_66_shadow` LIKE `user_settings_66`;
CREATE TABLE IF NOT EXISTS `user_card_66_shadow` LIKE `user_card_66`;
CREATE TABLE IF NOT EXISTS `merchants_66_shadow` LIKE `merchants_66`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_66_shadow` LIKE `merchant_kyc_document_66`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_66_shadow` LIKE `merchant_channel_secret_66`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_66_shadow` LIKE `admin_audit_log_66`;

CREATE TABLE IF NOT EXISTS `users_67_shadow` LIKE `users_67`;
CREATE TABLE IF NOT EXISTS `user_profiles_67_shadow` LIKE `user_profiles_67`;
CREATE TABLE IF NOT EXISTS `user_auths_67_shadow` LIKE `user_auths_67`;
CREATE TABLE IF NOT EXISTS `login_logs_67_shadow` LIKE `login_logs_67`;
CREATE TABLE IF NOT EXISTS `user_sessions_67_shadow` LIKE `user_sessions_67`;
CREATE TABLE IF NOT EXISTS `user_roles_67_shadow` LIKE `user_roles_67`;
CREATE TABLE IF NOT EXISTS `user_accounts_67_shadow` LIKE `user_accounts_67`;
CREATE TABLE IF NOT EXISTS `user_settings_67_shadow` LIKE `user_settings_67`;
CREATE TABLE IF NOT EXISTS `user_card_67_shadow` LIKE `user_card_67`;
CREATE TABLE IF NOT EXISTS `merchants_67_shadow` LIKE `merchants_67`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_67_shadow` LIKE `merchant_kyc_document_67`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_67_shadow` LIKE `merchant_channel_secret_67`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_67_shadow` LIKE `admin_audit_log_67`;

CREATE TABLE IF NOT EXISTS `users_68_shadow` LIKE `users_68`;
CREATE TABLE IF NOT EXISTS `user_profiles_68_shadow` LIKE `user_profiles_68`;
CREATE TABLE IF NOT EXISTS `user_auths_68_shadow` LIKE `user_auths_68`;
CREATE TABLE IF NOT EXISTS `login_logs_68_shadow` LIKE `login_logs_68`;
CREATE TABLE IF NOT EXISTS `user_sessions_68_shadow` LIKE `user_sessions_68`;
CREATE TABLE IF NOT EXISTS `user_roles_68_shadow` LIKE `user_roles_68`;
CREATE TABLE IF NOT EXISTS `user_accounts_68_shadow` LIKE `user_accounts_68`;
CREATE TABLE IF NOT EXISTS `user_settings_68_shadow` LIKE `user_settings_68`;
CREATE TABLE IF NOT EXISTS `user_card_68_shadow` LIKE `user_card_68`;
CREATE TABLE IF NOT EXISTS `merchants_68_shadow` LIKE `merchants_68`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_68_shadow` LIKE `merchant_kyc_document_68`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_68_shadow` LIKE `merchant_channel_secret_68`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_68_shadow` LIKE `admin_audit_log_68`;

CREATE TABLE IF NOT EXISTS `users_69_shadow` LIKE `users_69`;
CREATE TABLE IF NOT EXISTS `user_profiles_69_shadow` LIKE `user_profiles_69`;
CREATE TABLE IF NOT EXISTS `user_auths_69_shadow` LIKE `user_auths_69`;
CREATE TABLE IF NOT EXISTS `login_logs_69_shadow` LIKE `login_logs_69`;
CREATE TABLE IF NOT EXISTS `user_sessions_69_shadow` LIKE `user_sessions_69`;
CREATE TABLE IF NOT EXISTS `user_roles_69_shadow` LIKE `user_roles_69`;
CREATE TABLE IF NOT EXISTS `user_accounts_69_shadow` LIKE `user_accounts_69`;
CREATE TABLE IF NOT EXISTS `user_settings_69_shadow` LIKE `user_settings_69`;
CREATE TABLE IF NOT EXISTS `user_card_69_shadow` LIKE `user_card_69`;
CREATE TABLE IF NOT EXISTS `merchants_69_shadow` LIKE `merchants_69`;
CREATE TABLE IF NOT EXISTS `merchant_kyc_document_69_shadow` LIKE `merchant_kyc_document_69`;
CREATE TABLE IF NOT EXISTS `merchant_channel_secret_69_shadow` LIKE `merchant_channel_secret_69`;
CREATE TABLE IF NOT EXISTS `admin_audit_log_69_shadow` LIKE `admin_audit_log_69`;

