// payment-channel 暴露给 payment-core 的 gRPC 面。形状与 order-core 的
// internal/channel.PaymentChannel 一致（就是 PaymentChannel 的 gRPC 表达）。
// payment-core 只是在本接口外包一层「按 payment_method 选哪个 payment-channel
// 实例」的路由。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/channel/v1/channel.proto

package channelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AcquirerService_Charge_FullMethodName  = "/channel.v1.AcquirerService/Charge"
	AcquirerService_Capture_FullMethodName = "/channel.v1.AcquirerService/Capture"
	AcquirerService_Void_FullMethodName    = "/channel.v1.AcquirerService/Void"
	AcquirerService_Refund_FullMethodName  = "/channel.v1.AcquirerService/Refund"
	AcquirerService_Query_FullMethodName   = "/channel.v1.AcquirerService/Query"
)

// AcquirerServiceClient is the client API for AcquirerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AcquirerServiceClient interface {
	Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error)
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*OpResponse, error)
	Void(ctx context.Context, in *VoidRequest, opts ...grpc.CallOption) (*OpResponse, error)
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*OpResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type acquirerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcquirerServiceClient(cc grpc.ClientConnInterface) AcquirerServiceClient {
	return &acquirerServiceClient{cc}
}

func (c *acquirerServiceClient) Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*ChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChargeResponse)
	err := c.cc.Invoke(ctx, AcquirerService_Charge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acquirerServiceClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AcquirerService_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acquirerServiceClient) Void(ctx context.Context, in *VoidRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AcquirerService_Void_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acquirerServiceClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpResponse)
	err := c.cc.Invoke(ctx, AcquirerService_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acquirerServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, AcquirerService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcquirerServiceServer is the server API for AcquirerService service.
// All implementations must embed UnimplementedAcquirerServiceServer
// for forward compatibility.
type AcquirerServiceServer interface {
	Charge(context.Context, *ChargeRequest) (*ChargeResponse, error)
	Capture(context.Context, *CaptureRequest) (*OpResponse, error)
	Void(context.Context, *VoidRequest) (*OpResponse, error)
	Refund(context.Context, *RefundRequest) (*OpResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedAcquirerServiceServer()
}

// UnimplementedAcquirerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcquirerServiceServer struct{}

func (UnimplementedAcquirerServiceServer) Charge(context.Context, *ChargeRequest) (*ChargeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Charge not implemented")
}
func (UnimplementedAcquirerServiceServer) Capture(context.Context, *CaptureRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedAcquirerServiceServer) Void(context.Context, *VoidRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Void not implemented")
}
func (UnimplementedAcquirerServiceServer) Refund(context.Context, *RefundRequest) (*OpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedAcquirerServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAcquirerServiceServer) mustEmbedUnimplementedAcquirerServiceServer() {}
func (UnimplementedAcquirerServiceServer) testEmbeddedByValue()                         {}

// UnsafeAcquirerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcquirerServiceServer will
// result in compilation errors.
type UnsafeAcquirerServiceServer interface {
	mustEmbedUnimplementedAcquirerServiceServer()
}

func RegisterAcquirerServiceServer(s grpc.ServiceRegistrar, srv AcquirerServiceServer) {
	// If the following call panics, it indicates UnimplementedAcquirerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AcquirerService_ServiceDesc, srv)
}

func _AcquirerService_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcquirerServiceServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcquirerService_Charge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcquirerServiceServer).Charge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcquirerService_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcquirerServiceServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcquirerService_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcquirerServiceServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcquirerService_Void_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcquirerServiceServer).Void(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcquirerService_Void_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcquirerServiceServer).Void(ctx, req.(*VoidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcquirerService_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcquirerServiceServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcquirerService_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcquirerServiceServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcquirerService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcquirerServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AcquirerService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcquirerServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AcquirerService_ServiceDesc is the grpc.ServiceDesc for AcquirerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AcquirerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "channel.v1.AcquirerService",
	HandlerType: (*AcquirerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _AcquirerService_Charge_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _AcquirerService_Capture_Handler,
		},
		{
			MethodName: "Void",
			Handler:    _AcquirerService_Void_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _AcquirerService_Refund_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AcquirerService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/channel/v1/channel.proto",
}
