// Code generated by Kitex v0.16.2. DO NOT EDIT.

package cardcenter

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	v1 "github.com/xiongwp/card-center/kitex_gen/cardcenter/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Tokenize(ctx context.Context, Req *v1.TokenizeRequest, callOptions ...callopt.Option) (r *v1.TokenizeResponse, err error)
	CreatePaymentToken(ctx context.Context, Req *v1.CreatePaymentTokenRequest, callOptions ...callopt.Option) (r *v1.CreatePaymentTokenResponse, err error)
	Detokenize(ctx context.Context, Req *v1.DetokenizeRequest, callOptions ...callopt.Option) (r *v1.DetokenizeResponse, err error)
	DeleteCard(ctx context.Context, Req *v1.DeleteCardRequest, callOptions ...callopt.Option) (r *v1.DeleteCardResponse, err error)
	RevokeStoredToken(ctx context.Context, Req *v1.RevokeStoredTokenRequest, callOptions ...callopt.Option) (r *v1.RevokeStoredTokenResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCardCenterClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCardCenterClient struct {
	*kClient
}

func (p *kCardCenterClient) Tokenize(ctx context.Context, Req *v1.TokenizeRequest, callOptions ...callopt.Option) (r *v1.TokenizeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Tokenize(ctx, Req)
}

func (p *kCardCenterClient) CreatePaymentToken(ctx context.Context, Req *v1.CreatePaymentTokenRequest, callOptions ...callopt.Option) (r *v1.CreatePaymentTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePaymentToken(ctx, Req)
}

func (p *kCardCenterClient) Detokenize(ctx context.Context, Req *v1.DetokenizeRequest, callOptions ...callopt.Option) (r *v1.DetokenizeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Detokenize(ctx, Req)
}

func (p *kCardCenterClient) DeleteCard(ctx context.Context, Req *v1.DeleteCardRequest, callOptions ...callopt.Option) (r *v1.DeleteCardResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCard(ctx, Req)
}

func (p *kCardCenterClient) RevokeStoredToken(ctx context.Context, Req *v1.RevokeStoredTokenRequest, callOptions ...callopt.Option) (r *v1.RevokeStoredTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeStoredToken(ctx, Req)
}
