// Code generated by Kitex v0.16.2. DO NOT EDIT.

package accountingservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	accountingv1 "github.com/xiongwp/accounting-system/kitex_gen/accounting/v1"
	v1 "github.com/xiongwp/accounting-system/kitex_gen/accounting/v1"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateAccount": kitex.NewMethodInfo(
		createAccountHandler,
		newCreateAccountArgs,
		newCreateAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetAccount": kitex.NewMethodInfo(
		getAccountHandler,
		newGetAccountArgs,
		newGetAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FreezeAccount": kitex.NewMethodInfo(
		freezeAccountHandler,
		newFreezeAccountArgs,
		newFreezeAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnfreezeAccount": kitex.NewMethodInfo(
		unfreezeAccountHandler,
		newUnfreezeAccountArgs,
		newUnfreezeAccountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DoubleEntryBooking": kitex.NewMethodInfo(
		doubleEntryBookingHandler,
		newDoubleEntryBookingArgs,
		newDoubleEntryBookingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchBooking": kitex.NewMethodInfo(
		batchBookingHandler,
		newBatchBookingArgs,
		newBatchBookingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MoneyFlow": kitex.NewMethodInfo(
		moneyFlowHandler,
		newMoneyFlowArgs,
		newMoneyFlowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"HybridDoubleEntryBooking": kitex.NewMethodInfo(
		hybridDoubleEntryBookingHandler,
		newHybridDoubleEntryBookingArgs,
		newHybridDoubleEntryBookingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AtomicBatchBooking": kitex.NewMethodInfo(
		atomicBatchBookingHandler,
		newAtomicBatchBookingArgs,
		newAtomicBatchBookingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTransaction": kitex.NewMethodInfo(
		getTransactionHandler,
		newGetTransactionArgs,
		newGetTransactionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetBalanceSnapshot": kitex.NewMethodInfo(
		getBalanceSnapshotHandler,
		newGetBalanceSnapshotArgs,
		newGetBalanceSnapshotResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListAccountsByUserAndBusinessType": kitex.NewMethodInfo(
		listAccountsByUserAndBusinessTypeHandler,
		newListAccountsByUserAndBusinessTypeArgs,
		newListAccountsByUserAndBusinessTypeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListDayCutHistory": kitex.NewMethodInfo(
		listDayCutHistoryHandler,
		newListDayCutHistoryArgs,
		newListDayCutHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListSnapshotDates": kitex.NewMethodInfo(
		listSnapshotDatesHandler,
		newListSnapshotDatesArgs,
		newListSnapshotDatesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RebuildHotAccounts": kitex.NewMethodInfo(
		rebuildHotAccountsHandler,
		newRebuildHotAccountsArgs,
		newRebuildHotAccountsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"TriggerDayCut": kitex.NewMethodInfo(
		triggerDayCutHandler,
		newTriggerDayCutArgs,
		newTriggerDayCutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AdjustBalance": kitex.NewMethodInfo(
		adjustBalanceHandler,
		newAdjustBalanceArgs,
		newAdjustBalanceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTccStatus": kitex.NewMethodInfo(
		getTccStatusHandler,
		newGetTccStatusArgs,
		newGetTccStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListStuckTcc": kitex.NewMethodInfo(
		listStuckTccHandler,
		newListStuckTccArgs,
		newListStuckTccResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CancelTcc": kitex.NewMethodInfo(
		cancelTccHandler,
		newCancelTccArgs,
		newCancelTccResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CancelTccBranch": kitex.NewMethodInfo(
		cancelTccBranchHandler,
		newCancelTccBranchArgs,
		newCancelTccBranchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RunTrialBalance": kitex.NewMethodInfo(
		runTrialBalanceHandler,
		newRunTrialBalanceArgs,
		newRunTrialBalanceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	accountingServiceServiceInfo                = NewServiceInfo()
	accountingServiceServiceInfoForClient       = NewServiceInfoForClient()
	accountingServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return accountingServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return accountingServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return accountingServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AccountingService"
	handlerType := (*accountingv1.AccountingService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "accounting.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateAccountRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).CreateAccount(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateAccountArgs:
		success, err := handler.(accountingv1.AccountingService).CreateAccount(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateAccountResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateAccountArgs() interface{} {
	return &CreateAccountArgs{}
}

func newCreateAccountResult() interface{} {
	return &CreateAccountResult{}
}

type CreateAccountArgs struct {
	Req *v1.CreateAccountRequest
}

func (p *CreateAccountArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateAccountArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateAccountRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateAccountArgs_Req_DEFAULT *v1.CreateAccountRequest

func (p *CreateAccountArgs) GetReq() *v1.CreateAccountRequest {
	if !p.IsSetReq() {
		return CreateAccountArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateAccountArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateAccountResult struct {
	Success *v1.CreateAccountResponse
}

var CreateAccountResult_Success_DEFAULT *v1.CreateAccountResponse

func (p *CreateAccountResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateAccountResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateAccountResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateAccountResult) GetSuccess() *v1.CreateAccountResponse {
	if !p.IsSetSuccess() {
		return CreateAccountResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateAccountResponse)
}

func (p *CreateAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateAccountResult) GetResult() interface{} {
	return p.Success
}

func getAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetAccountRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).GetAccount(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetAccountArgs:
		success, err := handler.(accountingv1.AccountingService).GetAccount(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetAccountResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetAccountArgs() interface{} {
	return &GetAccountArgs{}
}

func newGetAccountResult() interface{} {
	return &GetAccountResult{}
}

type GetAccountArgs struct {
	Req *v1.GetAccountRequest
}

func (p *GetAccountArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetAccountArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetAccountRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetAccountArgs_Req_DEFAULT *v1.GetAccountRequest

func (p *GetAccountArgs) GetReq() *v1.GetAccountRequest {
	if !p.IsSetReq() {
		return GetAccountArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetAccountArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetAccountResult struct {
	Success *v1.GetAccountResponse
}

var GetAccountResult_Success_DEFAULT *v1.GetAccountResponse

func (p *GetAccountResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetAccountResult) Unmarshal(in []byte) error {
	msg := new(v1.GetAccountResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetAccountResult) GetSuccess() *v1.GetAccountResponse {
	if !p.IsSetSuccess() {
		return GetAccountResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetAccountResponse)
}

func (p *GetAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetAccountResult) GetResult() interface{} {
	return p.Success
}

func freezeAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.FreezeAccountRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).FreezeAccount(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FreezeAccountArgs:
		success, err := handler.(accountingv1.AccountingService).FreezeAccount(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FreezeAccountResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFreezeAccountArgs() interface{} {
	return &FreezeAccountArgs{}
}

func newFreezeAccountResult() interface{} {
	return &FreezeAccountResult{}
}

type FreezeAccountArgs struct {
	Req *v1.FreezeAccountRequest
}

func (p *FreezeAccountArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FreezeAccountArgs) Unmarshal(in []byte) error {
	msg := new(v1.FreezeAccountRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FreezeAccountArgs_Req_DEFAULT *v1.FreezeAccountRequest

func (p *FreezeAccountArgs) GetReq() *v1.FreezeAccountRequest {
	if !p.IsSetReq() {
		return FreezeAccountArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FreezeAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FreezeAccountArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FreezeAccountResult struct {
	Success *v1.FreezeAccountResponse
}

var FreezeAccountResult_Success_DEFAULT *v1.FreezeAccountResponse

func (p *FreezeAccountResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FreezeAccountResult) Unmarshal(in []byte) error {
	msg := new(v1.FreezeAccountResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FreezeAccountResult) GetSuccess() *v1.FreezeAccountResponse {
	if !p.IsSetSuccess() {
		return FreezeAccountResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FreezeAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.FreezeAccountResponse)
}

func (p *FreezeAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FreezeAccountResult) GetResult() interface{} {
	return p.Success
}

func unfreezeAccountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UnfreezeAccountRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).UnfreezeAccount(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnfreezeAccountArgs:
		success, err := handler.(accountingv1.AccountingService).UnfreezeAccount(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnfreezeAccountResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnfreezeAccountArgs() interface{} {
	return &UnfreezeAccountArgs{}
}

func newUnfreezeAccountResult() interface{} {
	return &UnfreezeAccountResult{}
}

type UnfreezeAccountArgs struct {
	Req *v1.UnfreezeAccountRequest
}

func (p *UnfreezeAccountArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnfreezeAccountArgs) Unmarshal(in []byte) error {
	msg := new(v1.UnfreezeAccountRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnfreezeAccountArgs_Req_DEFAULT *v1.UnfreezeAccountRequest

func (p *UnfreezeAccountArgs) GetReq() *v1.UnfreezeAccountRequest {
	if !p.IsSetReq() {
		return UnfreezeAccountArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnfreezeAccountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnfreezeAccountArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnfreezeAccountResult struct {
	Success *v1.UnfreezeAccountResponse
}

var UnfreezeAccountResult_Success_DEFAULT *v1.UnfreezeAccountResponse

func (p *UnfreezeAccountResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnfreezeAccountResult) Unmarshal(in []byte) error {
	msg := new(v1.UnfreezeAccountResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnfreezeAccountResult) GetSuccess() *v1.UnfreezeAccountResponse {
	if !p.IsSetSuccess() {
		return UnfreezeAccountResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnfreezeAccountResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UnfreezeAccountResponse)
}

func (p *UnfreezeAccountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnfreezeAccountResult) GetResult() interface{} {
	return p.Success
}

func doubleEntryBookingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DoubleEntryBookingRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).DoubleEntryBooking(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DoubleEntryBookingArgs:
		success, err := handler.(accountingv1.AccountingService).DoubleEntryBooking(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DoubleEntryBookingResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDoubleEntryBookingArgs() interface{} {
	return &DoubleEntryBookingArgs{}
}

func newDoubleEntryBookingResult() interface{} {
	return &DoubleEntryBookingResult{}
}

type DoubleEntryBookingArgs struct {
	Req *v1.DoubleEntryBookingRequest
}

func (p *DoubleEntryBookingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DoubleEntryBookingArgs) Unmarshal(in []byte) error {
	msg := new(v1.DoubleEntryBookingRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DoubleEntryBookingArgs_Req_DEFAULT *v1.DoubleEntryBookingRequest

func (p *DoubleEntryBookingArgs) GetReq() *v1.DoubleEntryBookingRequest {
	if !p.IsSetReq() {
		return DoubleEntryBookingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DoubleEntryBookingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DoubleEntryBookingArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DoubleEntryBookingResult struct {
	Success *v1.DoubleEntryBookingResponse
}

var DoubleEntryBookingResult_Success_DEFAULT *v1.DoubleEntryBookingResponse

func (p *DoubleEntryBookingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DoubleEntryBookingResult) Unmarshal(in []byte) error {
	msg := new(v1.DoubleEntryBookingResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DoubleEntryBookingResult) GetSuccess() *v1.DoubleEntryBookingResponse {
	if !p.IsSetSuccess() {
		return DoubleEntryBookingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DoubleEntryBookingResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DoubleEntryBookingResponse)
}

func (p *DoubleEntryBookingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DoubleEntryBookingResult) GetResult() interface{} {
	return p.Success
}

func batchBookingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.BatchBookingRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).BatchBooking(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchBookingArgs:
		success, err := handler.(accountingv1.AccountingService).BatchBooking(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchBookingResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchBookingArgs() interface{} {
	return &BatchBookingArgs{}
}

func newBatchBookingResult() interface{} {
	return &BatchBookingResult{}
}

type BatchBookingArgs struct {
	Req *v1.BatchBookingRequest
}

func (p *BatchBookingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchBookingArgs) Unmarshal(in []byte) error {
	msg := new(v1.BatchBookingRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchBookingArgs_Req_DEFAULT *v1.BatchBookingRequest

func (p *BatchBookingArgs) GetReq() *v1.BatchBookingRequest {
	if !p.IsSetReq() {
		return BatchBookingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchBookingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchBookingArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchBookingResult struct {
	Success *v1.BatchBookingResponse
}

var BatchBookingResult_Success_DEFAULT *v1.BatchBookingResponse

func (p *BatchBookingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchBookingResult) Unmarshal(in []byte) error {
	msg := new(v1.BatchBookingResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchBookingResult) GetSuccess() *v1.BatchBookingResponse {
	if !p.IsSetSuccess() {
		return BatchBookingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchBookingResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.BatchBookingResponse)
}

func (p *BatchBookingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchBookingResult) GetResult() interface{} {
	return p.Success
}

func moneyFlowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.MoneyFlowRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).MoneyFlow(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MoneyFlowArgs:
		success, err := handler.(accountingv1.AccountingService).MoneyFlow(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MoneyFlowResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMoneyFlowArgs() interface{} {
	return &MoneyFlowArgs{}
}

func newMoneyFlowResult() interface{} {
	return &MoneyFlowResult{}
}

type MoneyFlowArgs struct {
	Req *v1.MoneyFlowRequest
}

func (p *MoneyFlowArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MoneyFlowArgs) Unmarshal(in []byte) error {
	msg := new(v1.MoneyFlowRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MoneyFlowArgs_Req_DEFAULT *v1.MoneyFlowRequest

func (p *MoneyFlowArgs) GetReq() *v1.MoneyFlowRequest {
	if !p.IsSetReq() {
		return MoneyFlowArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MoneyFlowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MoneyFlowArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MoneyFlowResult struct {
	Success *v1.MoneyFlowResponse
}

var MoneyFlowResult_Success_DEFAULT *v1.MoneyFlowResponse

func (p *MoneyFlowResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MoneyFlowResult) Unmarshal(in []byte) error {
	msg := new(v1.MoneyFlowResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MoneyFlowResult) GetSuccess() *v1.MoneyFlowResponse {
	if !p.IsSetSuccess() {
		return MoneyFlowResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MoneyFlowResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.MoneyFlowResponse)
}

func (p *MoneyFlowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MoneyFlowResult) GetResult() interface{} {
	return p.Success
}

func hybridDoubleEntryBookingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.HybridDoubleEntryBookingRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).HybridDoubleEntryBooking(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HybridDoubleEntryBookingArgs:
		success, err := handler.(accountingv1.AccountingService).HybridDoubleEntryBooking(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HybridDoubleEntryBookingResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHybridDoubleEntryBookingArgs() interface{} {
	return &HybridDoubleEntryBookingArgs{}
}

func newHybridDoubleEntryBookingResult() interface{} {
	return &HybridDoubleEntryBookingResult{}
}

type HybridDoubleEntryBookingArgs struct {
	Req *v1.HybridDoubleEntryBookingRequest
}

func (p *HybridDoubleEntryBookingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HybridDoubleEntryBookingArgs) Unmarshal(in []byte) error {
	msg := new(v1.HybridDoubleEntryBookingRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HybridDoubleEntryBookingArgs_Req_DEFAULT *v1.HybridDoubleEntryBookingRequest

func (p *HybridDoubleEntryBookingArgs) GetReq() *v1.HybridDoubleEntryBookingRequest {
	if !p.IsSetReq() {
		return HybridDoubleEntryBookingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HybridDoubleEntryBookingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HybridDoubleEntryBookingArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HybridDoubleEntryBookingResult struct {
	Success *v1.HybridDoubleEntryBookingResponse
}

var HybridDoubleEntryBookingResult_Success_DEFAULT *v1.HybridDoubleEntryBookingResponse

func (p *HybridDoubleEntryBookingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HybridDoubleEntryBookingResult) Unmarshal(in []byte) error {
	msg := new(v1.HybridDoubleEntryBookingResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HybridDoubleEntryBookingResult) GetSuccess() *v1.HybridDoubleEntryBookingResponse {
	if !p.IsSetSuccess() {
		return HybridDoubleEntryBookingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HybridDoubleEntryBookingResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.HybridDoubleEntryBookingResponse)
}

func (p *HybridDoubleEntryBookingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HybridDoubleEntryBookingResult) GetResult() interface{} {
	return p.Success
}

func atomicBatchBookingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.AtomicBatchBookingRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).AtomicBatchBooking(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AtomicBatchBookingArgs:
		success, err := handler.(accountingv1.AccountingService).AtomicBatchBooking(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AtomicBatchBookingResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAtomicBatchBookingArgs() interface{} {
	return &AtomicBatchBookingArgs{}
}

func newAtomicBatchBookingResult() interface{} {
	return &AtomicBatchBookingResult{}
}

type AtomicBatchBookingArgs struct {
	Req *v1.AtomicBatchBookingRequest
}

func (p *AtomicBatchBookingArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AtomicBatchBookingArgs) Unmarshal(in []byte) error {
	msg := new(v1.AtomicBatchBookingRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AtomicBatchBookingArgs_Req_DEFAULT *v1.AtomicBatchBookingRequest

func (p *AtomicBatchBookingArgs) GetReq() *v1.AtomicBatchBookingRequest {
	if !p.IsSetReq() {
		return AtomicBatchBookingArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AtomicBatchBookingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AtomicBatchBookingArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AtomicBatchBookingResult struct {
	Success *v1.AtomicBatchBookingResponse
}

var AtomicBatchBookingResult_Success_DEFAULT *v1.AtomicBatchBookingResponse

func (p *AtomicBatchBookingResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AtomicBatchBookingResult) Unmarshal(in []byte) error {
	msg := new(v1.AtomicBatchBookingResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AtomicBatchBookingResult) GetSuccess() *v1.AtomicBatchBookingResponse {
	if !p.IsSetSuccess() {
		return AtomicBatchBookingResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AtomicBatchBookingResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.AtomicBatchBookingResponse)
}

func (p *AtomicBatchBookingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AtomicBatchBookingResult) GetResult() interface{} {
	return p.Success
}

func getTransactionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetTransactionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).GetTransaction(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTransactionArgs:
		success, err := handler.(accountingv1.AccountingService).GetTransaction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTransactionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTransactionArgs() interface{} {
	return &GetTransactionArgs{}
}

func newGetTransactionResult() interface{} {
	return &GetTransactionResult{}
}

type GetTransactionArgs struct {
	Req *v1.GetTransactionRequest
}

func (p *GetTransactionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTransactionArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetTransactionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTransactionArgs_Req_DEFAULT *v1.GetTransactionRequest

func (p *GetTransactionArgs) GetReq() *v1.GetTransactionRequest {
	if !p.IsSetReq() {
		return GetTransactionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTransactionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTransactionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTransactionResult struct {
	Success *v1.GetTransactionResponse
}

var GetTransactionResult_Success_DEFAULT *v1.GetTransactionResponse

func (p *GetTransactionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTransactionResult) Unmarshal(in []byte) error {
	msg := new(v1.GetTransactionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTransactionResult) GetSuccess() *v1.GetTransactionResponse {
	if !p.IsSetSuccess() {
		return GetTransactionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTransactionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetTransactionResponse)
}

func (p *GetTransactionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTransactionResult) GetResult() interface{} {
	return p.Success
}

func getBalanceSnapshotHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetBalanceSnapshotRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).GetBalanceSnapshot(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetBalanceSnapshotArgs:
		success, err := handler.(accountingv1.AccountingService).GetBalanceSnapshot(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetBalanceSnapshotResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetBalanceSnapshotArgs() interface{} {
	return &GetBalanceSnapshotArgs{}
}

func newGetBalanceSnapshotResult() interface{} {
	return &GetBalanceSnapshotResult{}
}

type GetBalanceSnapshotArgs struct {
	Req *v1.GetBalanceSnapshotRequest
}

func (p *GetBalanceSnapshotArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetBalanceSnapshotArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetBalanceSnapshotRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetBalanceSnapshotArgs_Req_DEFAULT *v1.GetBalanceSnapshotRequest

func (p *GetBalanceSnapshotArgs) GetReq() *v1.GetBalanceSnapshotRequest {
	if !p.IsSetReq() {
		return GetBalanceSnapshotArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetBalanceSnapshotArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetBalanceSnapshotArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetBalanceSnapshotResult struct {
	Success *v1.GetBalanceSnapshotResponse
}

var GetBalanceSnapshotResult_Success_DEFAULT *v1.GetBalanceSnapshotResponse

func (p *GetBalanceSnapshotResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetBalanceSnapshotResult) Unmarshal(in []byte) error {
	msg := new(v1.GetBalanceSnapshotResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetBalanceSnapshotResult) GetSuccess() *v1.GetBalanceSnapshotResponse {
	if !p.IsSetSuccess() {
		return GetBalanceSnapshotResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetBalanceSnapshotResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetBalanceSnapshotResponse)
}

func (p *GetBalanceSnapshotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetBalanceSnapshotResult) GetResult() interface{} {
	return p.Success
}

func listAccountsByUserAndBusinessTypeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListAccountsByUserAndBusinessTypeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).ListAccountsByUserAndBusinessType(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListAccountsByUserAndBusinessTypeArgs:
		success, err := handler.(accountingv1.AccountingService).ListAccountsByUserAndBusinessType(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListAccountsByUserAndBusinessTypeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListAccountsByUserAndBusinessTypeArgs() interface{} {
	return &ListAccountsByUserAndBusinessTypeArgs{}
}

func newListAccountsByUserAndBusinessTypeResult() interface{} {
	return &ListAccountsByUserAndBusinessTypeResult{}
}

type ListAccountsByUserAndBusinessTypeArgs struct {
	Req *v1.ListAccountsByUserAndBusinessTypeRequest
}

func (p *ListAccountsByUserAndBusinessTypeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListAccountsByUserAndBusinessTypeArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListAccountsByUserAndBusinessTypeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListAccountsByUserAndBusinessTypeArgs_Req_DEFAULT *v1.ListAccountsByUserAndBusinessTypeRequest

func (p *ListAccountsByUserAndBusinessTypeArgs) GetReq() *v1.ListAccountsByUserAndBusinessTypeRequest {
	if !p.IsSetReq() {
		return ListAccountsByUserAndBusinessTypeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListAccountsByUserAndBusinessTypeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListAccountsByUserAndBusinessTypeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListAccountsByUserAndBusinessTypeResult struct {
	Success *v1.ListAccountsByUserAndBusinessTypeResponse
}

var ListAccountsByUserAndBusinessTypeResult_Success_DEFAULT *v1.ListAccountsByUserAndBusinessTypeResponse

func (p *ListAccountsByUserAndBusinessTypeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListAccountsByUserAndBusinessTypeResult) Unmarshal(in []byte) error {
	msg := new(v1.ListAccountsByUserAndBusinessTypeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListAccountsByUserAndBusinessTypeResult) GetSuccess() *v1.ListAccountsByUserAndBusinessTypeResponse {
	if !p.IsSetSuccess() {
		return ListAccountsByUserAndBusinessTypeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListAccountsByUserAndBusinessTypeResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListAccountsByUserAndBusinessTypeResponse)
}

func (p *ListAccountsByUserAndBusinessTypeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListAccountsByUserAndBusinessTypeResult) GetResult() interface{} {
	return p.Success
}

func listDayCutHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListDayCutHistoryRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).ListDayCutHistory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListDayCutHistoryArgs:
		success, err := handler.(accountingv1.AccountingService).ListDayCutHistory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListDayCutHistoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListDayCutHistoryArgs() interface{} {
	return &ListDayCutHistoryArgs{}
}

func newListDayCutHistoryResult() interface{} {
	return &ListDayCutHistoryResult{}
}

type ListDayCutHistoryArgs struct {
	Req *v1.ListDayCutHistoryRequest
}

func (p *ListDayCutHistoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListDayCutHistoryArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListDayCutHistoryRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListDayCutHistoryArgs_Req_DEFAULT *v1.ListDayCutHistoryRequest

func (p *ListDayCutHistoryArgs) GetReq() *v1.ListDayCutHistoryRequest {
	if !p.IsSetReq() {
		return ListDayCutHistoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListDayCutHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListDayCutHistoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListDayCutHistoryResult struct {
	Success *v1.ListDayCutHistoryResponse
}

var ListDayCutHistoryResult_Success_DEFAULT *v1.ListDayCutHistoryResponse

func (p *ListDayCutHistoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListDayCutHistoryResult) Unmarshal(in []byte) error {
	msg := new(v1.ListDayCutHistoryResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListDayCutHistoryResult) GetSuccess() *v1.ListDayCutHistoryResponse {
	if !p.IsSetSuccess() {
		return ListDayCutHistoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListDayCutHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListDayCutHistoryResponse)
}

func (p *ListDayCutHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListDayCutHistoryResult) GetResult() interface{} {
	return p.Success
}

func listSnapshotDatesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListSnapshotDatesRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).ListSnapshotDates(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListSnapshotDatesArgs:
		success, err := handler.(accountingv1.AccountingService).ListSnapshotDates(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListSnapshotDatesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListSnapshotDatesArgs() interface{} {
	return &ListSnapshotDatesArgs{}
}

func newListSnapshotDatesResult() interface{} {
	return &ListSnapshotDatesResult{}
}

type ListSnapshotDatesArgs struct {
	Req *v1.ListSnapshotDatesRequest
}

func (p *ListSnapshotDatesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListSnapshotDatesArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListSnapshotDatesRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListSnapshotDatesArgs_Req_DEFAULT *v1.ListSnapshotDatesRequest

func (p *ListSnapshotDatesArgs) GetReq() *v1.ListSnapshotDatesRequest {
	if !p.IsSetReq() {
		return ListSnapshotDatesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListSnapshotDatesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListSnapshotDatesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListSnapshotDatesResult struct {
	Success *v1.ListSnapshotDatesResponse
}

var ListSnapshotDatesResult_Success_DEFAULT *v1.ListSnapshotDatesResponse

func (p *ListSnapshotDatesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListSnapshotDatesResult) Unmarshal(in []byte) error {
	msg := new(v1.ListSnapshotDatesResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListSnapshotDatesResult) GetSuccess() *v1.ListSnapshotDatesResponse {
	if !p.IsSetSuccess() {
		return ListSnapshotDatesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListSnapshotDatesResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListSnapshotDatesResponse)
}

func (p *ListSnapshotDatesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListSnapshotDatesResult) GetResult() interface{} {
	return p.Success
}

func rebuildHotAccountsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RebuildHotAccountsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).RebuildHotAccounts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RebuildHotAccountsArgs:
		success, err := handler.(accountingv1.AccountingService).RebuildHotAccounts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RebuildHotAccountsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRebuildHotAccountsArgs() interface{} {
	return &RebuildHotAccountsArgs{}
}

func newRebuildHotAccountsResult() interface{} {
	return &RebuildHotAccountsResult{}
}

type RebuildHotAccountsArgs struct {
	Req *v1.RebuildHotAccountsRequest
}

func (p *RebuildHotAccountsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RebuildHotAccountsArgs) Unmarshal(in []byte) error {
	msg := new(v1.RebuildHotAccountsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RebuildHotAccountsArgs_Req_DEFAULT *v1.RebuildHotAccountsRequest

func (p *RebuildHotAccountsArgs) GetReq() *v1.RebuildHotAccountsRequest {
	if !p.IsSetReq() {
		return RebuildHotAccountsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RebuildHotAccountsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RebuildHotAccountsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RebuildHotAccountsResult struct {
	Success *v1.RebuildHotAccountsResponse
}

var RebuildHotAccountsResult_Success_DEFAULT *v1.RebuildHotAccountsResponse

func (p *RebuildHotAccountsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RebuildHotAccountsResult) Unmarshal(in []byte) error {
	msg := new(v1.RebuildHotAccountsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RebuildHotAccountsResult) GetSuccess() *v1.RebuildHotAccountsResponse {
	if !p.IsSetSuccess() {
		return RebuildHotAccountsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RebuildHotAccountsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RebuildHotAccountsResponse)
}

func (p *RebuildHotAccountsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RebuildHotAccountsResult) GetResult() interface{} {
	return p.Success
}

func triggerDayCutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.TriggerDayCutRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).TriggerDayCut(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *TriggerDayCutArgs:
		success, err := handler.(accountingv1.AccountingService).TriggerDayCut(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TriggerDayCutResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newTriggerDayCutArgs() interface{} {
	return &TriggerDayCutArgs{}
}

func newTriggerDayCutResult() interface{} {
	return &TriggerDayCutResult{}
}

type TriggerDayCutArgs struct {
	Req *v1.TriggerDayCutRequest
}

func (p *TriggerDayCutArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *TriggerDayCutArgs) Unmarshal(in []byte) error {
	msg := new(v1.TriggerDayCutRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TriggerDayCutArgs_Req_DEFAULT *v1.TriggerDayCutRequest

func (p *TriggerDayCutArgs) GetReq() *v1.TriggerDayCutRequest {
	if !p.IsSetReq() {
		return TriggerDayCutArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TriggerDayCutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TriggerDayCutArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TriggerDayCutResult struct {
	Success *v1.TriggerDayCutResponse
}

var TriggerDayCutResult_Success_DEFAULT *v1.TriggerDayCutResponse

func (p *TriggerDayCutResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *TriggerDayCutResult) Unmarshal(in []byte) error {
	msg := new(v1.TriggerDayCutResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TriggerDayCutResult) GetSuccess() *v1.TriggerDayCutResponse {
	if !p.IsSetSuccess() {
		return TriggerDayCutResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TriggerDayCutResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.TriggerDayCutResponse)
}

func (p *TriggerDayCutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TriggerDayCutResult) GetResult() interface{} {
	return p.Success
}

func adjustBalanceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.AdjustBalanceRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).AdjustBalance(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AdjustBalanceArgs:
		success, err := handler.(accountingv1.AccountingService).AdjustBalance(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AdjustBalanceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAdjustBalanceArgs() interface{} {
	return &AdjustBalanceArgs{}
}

func newAdjustBalanceResult() interface{} {
	return &AdjustBalanceResult{}
}

type AdjustBalanceArgs struct {
	Req *v1.AdjustBalanceRequest
}

func (p *AdjustBalanceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AdjustBalanceArgs) Unmarshal(in []byte) error {
	msg := new(v1.AdjustBalanceRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AdjustBalanceArgs_Req_DEFAULT *v1.AdjustBalanceRequest

func (p *AdjustBalanceArgs) GetReq() *v1.AdjustBalanceRequest {
	if !p.IsSetReq() {
		return AdjustBalanceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AdjustBalanceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdjustBalanceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AdjustBalanceResult struct {
	Success *v1.AdjustBalanceResponse
}

var AdjustBalanceResult_Success_DEFAULT *v1.AdjustBalanceResponse

func (p *AdjustBalanceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AdjustBalanceResult) Unmarshal(in []byte) error {
	msg := new(v1.AdjustBalanceResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AdjustBalanceResult) GetSuccess() *v1.AdjustBalanceResponse {
	if !p.IsSetSuccess() {
		return AdjustBalanceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AdjustBalanceResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.AdjustBalanceResponse)
}

func (p *AdjustBalanceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdjustBalanceResult) GetResult() interface{} {
	return p.Success
}

func getTccStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetTccStatusRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).GetTccStatus(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTccStatusArgs:
		success, err := handler.(accountingv1.AccountingService).GetTccStatus(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTccStatusResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTccStatusArgs() interface{} {
	return &GetTccStatusArgs{}
}

func newGetTccStatusResult() interface{} {
	return &GetTccStatusResult{}
}

type GetTccStatusArgs struct {
	Req *v1.GetTccStatusRequest
}

func (p *GetTccStatusArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTccStatusArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetTccStatusRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTccStatusArgs_Req_DEFAULT *v1.GetTccStatusRequest

func (p *GetTccStatusArgs) GetReq() *v1.GetTccStatusRequest {
	if !p.IsSetReq() {
		return GetTccStatusArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTccStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTccStatusArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTccStatusResult struct {
	Success *v1.GetTccStatusResponse
}

var GetTccStatusResult_Success_DEFAULT *v1.GetTccStatusResponse

func (p *GetTccStatusResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTccStatusResult) Unmarshal(in []byte) error {
	msg := new(v1.GetTccStatusResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTccStatusResult) GetSuccess() *v1.GetTccStatusResponse {
	if !p.IsSetSuccess() {
		return GetTccStatusResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTccStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetTccStatusResponse)
}

func (p *GetTccStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTccStatusResult) GetResult() interface{} {
	return p.Success
}

func listStuckTccHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListStuckTccRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).ListStuckTcc(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListStuckTccArgs:
		success, err := handler.(accountingv1.AccountingService).ListStuckTcc(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListStuckTccResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListStuckTccArgs() interface{} {
	return &ListStuckTccArgs{}
}

func newListStuckTccResult() interface{} {
	return &ListStuckTccResult{}
}

type ListStuckTccArgs struct {
	Req *v1.ListStuckTccRequest
}

func (p *ListStuckTccArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListStuckTccArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListStuckTccRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListStuckTccArgs_Req_DEFAULT *v1.ListStuckTccRequest

func (p *ListStuckTccArgs) GetReq() *v1.ListStuckTccRequest {
	if !p.IsSetReq() {
		return ListStuckTccArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListStuckTccArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListStuckTccArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListStuckTccResult struct {
	Success *v1.ListStuckTccResponse
}

var ListStuckTccResult_Success_DEFAULT *v1.ListStuckTccResponse

func (p *ListStuckTccResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListStuckTccResult) Unmarshal(in []byte) error {
	msg := new(v1.ListStuckTccResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListStuckTccResult) GetSuccess() *v1.ListStuckTccResponse {
	if !p.IsSetSuccess() {
		return ListStuckTccResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListStuckTccResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListStuckTccResponse)
}

func (p *ListStuckTccResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListStuckTccResult) GetResult() interface{} {
	return p.Success
}

func cancelTccHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CancelTccRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).CancelTcc(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CancelTccArgs:
		success, err := handler.(accountingv1.AccountingService).CancelTcc(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CancelTccResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCancelTccArgs() interface{} {
	return &CancelTccArgs{}
}

func newCancelTccResult() interface{} {
	return &CancelTccResult{}
}

type CancelTccArgs struct {
	Req *v1.CancelTccRequest
}

func (p *CancelTccArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CancelTccArgs) Unmarshal(in []byte) error {
	msg := new(v1.CancelTccRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CancelTccArgs_Req_DEFAULT *v1.CancelTccRequest

func (p *CancelTccArgs) GetReq() *v1.CancelTccRequest {
	if !p.IsSetReq() {
		return CancelTccArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CancelTccArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CancelTccArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CancelTccResult struct {
	Success *v1.CancelTccResponse
}

var CancelTccResult_Success_DEFAULT *v1.CancelTccResponse

func (p *CancelTccResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CancelTccResult) Unmarshal(in []byte) error {
	msg := new(v1.CancelTccResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CancelTccResult) GetSuccess() *v1.CancelTccResponse {
	if !p.IsSetSuccess() {
		return CancelTccResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CancelTccResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CancelTccResponse)
}

func (p *CancelTccResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CancelTccResult) GetResult() interface{} {
	return p.Success
}

func cancelTccBranchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CancelTccBranchRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).CancelTccBranch(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CancelTccBranchArgs:
		success, err := handler.(accountingv1.AccountingService).CancelTccBranch(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CancelTccBranchResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCancelTccBranchArgs() interface{} {
	return &CancelTccBranchArgs{}
}

func newCancelTccBranchResult() interface{} {
	return &CancelTccBranchResult{}
}

type CancelTccBranchArgs struct {
	Req *v1.CancelTccBranchRequest
}

func (p *CancelTccBranchArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CancelTccBranchArgs) Unmarshal(in []byte) error {
	msg := new(v1.CancelTccBranchRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CancelTccBranchArgs_Req_DEFAULT *v1.CancelTccBranchRequest

func (p *CancelTccBranchArgs) GetReq() *v1.CancelTccBranchRequest {
	if !p.IsSetReq() {
		return CancelTccBranchArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CancelTccBranchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CancelTccBranchArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CancelTccBranchResult struct {
	Success *v1.CancelTccBranchResponse
}

var CancelTccBranchResult_Success_DEFAULT *v1.CancelTccBranchResponse

func (p *CancelTccBranchResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CancelTccBranchResult) Unmarshal(in []byte) error {
	msg := new(v1.CancelTccBranchResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CancelTccBranchResult) GetSuccess() *v1.CancelTccBranchResponse {
	if !p.IsSetSuccess() {
		return CancelTccBranchResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CancelTccBranchResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CancelTccBranchResponse)
}

func (p *CancelTccBranchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CancelTccBranchResult) GetResult() interface{} {
	return p.Success
}

func runTrialBalanceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RunTrialBalanceRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(accountingv1.AccountingService).RunTrialBalance(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RunTrialBalanceArgs:
		success, err := handler.(accountingv1.AccountingService).RunTrialBalance(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RunTrialBalanceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRunTrialBalanceArgs() interface{} {
	return &RunTrialBalanceArgs{}
}

func newRunTrialBalanceResult() interface{} {
	return &RunTrialBalanceResult{}
}

type RunTrialBalanceArgs struct {
	Req *v1.RunTrialBalanceRequest
}

func (p *RunTrialBalanceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RunTrialBalanceArgs) Unmarshal(in []byte) error {
	msg := new(v1.RunTrialBalanceRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RunTrialBalanceArgs_Req_DEFAULT *v1.RunTrialBalanceRequest

func (p *RunTrialBalanceArgs) GetReq() *v1.RunTrialBalanceRequest {
	if !p.IsSetReq() {
		return RunTrialBalanceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RunTrialBalanceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RunTrialBalanceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RunTrialBalanceResult struct {
	Success *v1.RunTrialBalanceResponse
}

var RunTrialBalanceResult_Success_DEFAULT *v1.RunTrialBalanceResponse

func (p *RunTrialBalanceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RunTrialBalanceResult) Unmarshal(in []byte) error {
	msg := new(v1.RunTrialBalanceResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RunTrialBalanceResult) GetSuccess() *v1.RunTrialBalanceResponse {
	if !p.IsSetSuccess() {
		return RunTrialBalanceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RunTrialBalanceResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RunTrialBalanceResponse)
}

func (p *RunTrialBalanceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RunTrialBalanceResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateAccount(ctx context.Context, Req *v1.CreateAccountRequest) (r *v1.CreateAccountResponse, err error) {
	var _args CreateAccountArgs
	_args.Req = Req
	var _result CreateAccountResult
	if err = p.c.Call(ctx, "CreateAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAccount(ctx context.Context, Req *v1.GetAccountRequest) (r *v1.GetAccountResponse, err error) {
	var _args GetAccountArgs
	_args.Req = Req
	var _result GetAccountResult
	if err = p.c.Call(ctx, "GetAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FreezeAccount(ctx context.Context, Req *v1.FreezeAccountRequest) (r *v1.FreezeAccountResponse, err error) {
	var _args FreezeAccountArgs
	_args.Req = Req
	var _result FreezeAccountResult
	if err = p.c.Call(ctx, "FreezeAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnfreezeAccount(ctx context.Context, Req *v1.UnfreezeAccountRequest) (r *v1.UnfreezeAccountResponse, err error) {
	var _args UnfreezeAccountArgs
	_args.Req = Req
	var _result UnfreezeAccountResult
	if err = p.c.Call(ctx, "UnfreezeAccount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DoubleEntryBooking(ctx context.Context, Req *v1.DoubleEntryBookingRequest) (r *v1.DoubleEntryBookingResponse, err error) {
	var _args DoubleEntryBookingArgs
	_args.Req = Req
	var _result DoubleEntryBookingResult
	if err = p.c.Call(ctx, "DoubleEntryBooking", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchBooking(ctx context.Context, Req *v1.BatchBookingRequest) (r *v1.BatchBookingResponse, err error) {
	var _args BatchBookingArgs
	_args.Req = Req
	var _result BatchBookingResult
	if err = p.c.Call(ctx, "BatchBooking", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MoneyFlow(ctx context.Context, Req *v1.MoneyFlowRequest) (r *v1.MoneyFlowResponse, err error) {
	var _args MoneyFlowArgs
	_args.Req = Req
	var _result MoneyFlowResult
	if err = p.c.Call(ctx, "MoneyFlow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HybridDoubleEntryBooking(ctx context.Context, Req *v1.HybridDoubleEntryBookingRequest) (r *v1.HybridDoubleEntryBookingResponse, err error) {
	var _args HybridDoubleEntryBookingArgs
	_args.Req = Req
	var _result HybridDoubleEntryBookingResult
	if err = p.c.Call(ctx, "HybridDoubleEntryBooking", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AtomicBatchBooking(ctx context.Context, Req *v1.AtomicBatchBookingRequest) (r *v1.AtomicBatchBookingResponse, err error) {
	var _args AtomicBatchBookingArgs
	_args.Req = Req
	var _result AtomicBatchBookingResult
	if err = p.c.Call(ctx, "AtomicBatchBooking", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTransaction(ctx context.Context, Req *v1.GetTransactionRequest) (r *v1.GetTransactionResponse, err error) {
	var _args GetTransactionArgs
	_args.Req = Req
	var _result GetTransactionResult
	if err = p.c.Call(ctx, "GetTransaction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBalanceSnapshot(ctx context.Context, Req *v1.GetBalanceSnapshotRequest) (r *v1.GetBalanceSnapshotResponse, err error) {
	var _args GetBalanceSnapshotArgs
	_args.Req = Req
	var _result GetBalanceSnapshotResult
	if err = p.c.Call(ctx, "GetBalanceSnapshot", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAccountsByUserAndBusinessType(ctx context.Context, Req *v1.ListAccountsByUserAndBusinessTypeRequest) (r *v1.ListAccountsByUserAndBusinessTypeResponse, err error) {
	var _args ListAccountsByUserAndBusinessTypeArgs
	_args.Req = Req
	var _result ListAccountsByUserAndBusinessTypeResult
	if err = p.c.Call(ctx, "ListAccountsByUserAndBusinessType", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListDayCutHistory(ctx context.Context, Req *v1.ListDayCutHistoryRequest) (r *v1.ListDayCutHistoryResponse, err error) {
	var _args ListDayCutHistoryArgs
	_args.Req = Req
	var _result ListDayCutHistoryResult
	if err = p.c.Call(ctx, "ListDayCutHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSnapshotDates(ctx context.Context, Req *v1.ListSnapshotDatesRequest) (r *v1.ListSnapshotDatesResponse, err error) {
	var _args ListSnapshotDatesArgs
	_args.Req = Req
	var _result ListSnapshotDatesResult
	if err = p.c.Call(ctx, "ListSnapshotDates", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RebuildHotAccounts(ctx context.Context, Req *v1.RebuildHotAccountsRequest) (r *v1.RebuildHotAccountsResponse, err error) {
	var _args RebuildHotAccountsArgs
	_args.Req = Req
	var _result RebuildHotAccountsResult
	if err = p.c.Call(ctx, "RebuildHotAccounts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TriggerDayCut(ctx context.Context, Req *v1.TriggerDayCutRequest) (r *v1.TriggerDayCutResponse, err error) {
	var _args TriggerDayCutArgs
	_args.Req = Req
	var _result TriggerDayCutResult
	if err = p.c.Call(ctx, "TriggerDayCut", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdjustBalance(ctx context.Context, Req *v1.AdjustBalanceRequest) (r *v1.AdjustBalanceResponse, err error) {
	var _args AdjustBalanceArgs
	_args.Req = Req
	var _result AdjustBalanceResult
	if err = p.c.Call(ctx, "AdjustBalance", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTccStatus(ctx context.Context, Req *v1.GetTccStatusRequest) (r *v1.GetTccStatusResponse, err error) {
	var _args GetTccStatusArgs
	_args.Req = Req
	var _result GetTccStatusResult
	if err = p.c.Call(ctx, "GetTccStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListStuckTcc(ctx context.Context, Req *v1.ListStuckTccRequest) (r *v1.ListStuckTccResponse, err error) {
	var _args ListStuckTccArgs
	_args.Req = Req
	var _result ListStuckTccResult
	if err = p.c.Call(ctx, "ListStuckTcc", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelTcc(ctx context.Context, Req *v1.CancelTccRequest) (r *v1.CancelTccResponse, err error) {
	var _args CancelTccArgs
	_args.Req = Req
	var _result CancelTccResult
	if err = p.c.Call(ctx, "CancelTcc", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelTccBranch(ctx context.Context, Req *v1.CancelTccBranchRequest) (r *v1.CancelTccBranchResponse, err error) {
	var _args CancelTccBranchArgs
	_args.Req = Req
	var _result CancelTccBranchResult
	if err = p.c.Call(ctx, "CancelTccBranch", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RunTrialBalance(ctx context.Context, Req *v1.RunTrialBalanceRequest) (r *v1.RunTrialBalanceResponse, err error) {
	var _args RunTrialBalanceArgs
	_args.Req = Req
	var _result RunTrialBalanceResult
	if err = p.c.Call(ctx, "RunTrialBalance", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
