// Code generated by Kitex v0.16.2. DO NOT EDIT.

package accountingservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	v1 "github.com/xiongwp/accounting-system/kitex_gen/accounting/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAccount(ctx context.Context, Req *v1.CreateAccountRequest, callOptions ...callopt.Option) (r *v1.CreateAccountResponse, err error)
	GetAccount(ctx context.Context, Req *v1.GetAccountRequest, callOptions ...callopt.Option) (r *v1.GetAccountResponse, err error)
	FreezeAccount(ctx context.Context, Req *v1.FreezeAccountRequest, callOptions ...callopt.Option) (r *v1.FreezeAccountResponse, err error)
	UnfreezeAccount(ctx context.Context, Req *v1.UnfreezeAccountRequest, callOptions ...callopt.Option) (r *v1.UnfreezeAccountResponse, err error)
	DoubleEntryBooking(ctx context.Context, Req *v1.DoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.DoubleEntryBookingResponse, err error)
	BatchBooking(ctx context.Context, Req *v1.BatchBookingRequest, callOptions ...callopt.Option) (r *v1.BatchBookingResponse, err error)
	MoneyFlow(ctx context.Context, Req *v1.MoneyFlowRequest, callOptions ...callopt.Option) (r *v1.MoneyFlowResponse, err error)
	HybridDoubleEntryBooking(ctx context.Context, Req *v1.HybridDoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.HybridDoubleEntryBookingResponse, err error)
	AtomicBatchBooking(ctx context.Context, Req *v1.AtomicBatchBookingRequest, callOptions ...callopt.Option) (r *v1.AtomicBatchBookingResponse, err error)
	GetTransaction(ctx context.Context, Req *v1.GetTransactionRequest, callOptions ...callopt.Option) (r *v1.GetTransactionResponse, err error)
	GetBalanceSnapshot(ctx context.Context, Req *v1.GetBalanceSnapshotRequest, callOptions ...callopt.Option) (r *v1.GetBalanceSnapshotResponse, err error)
	ListAccountsByUserAndBusinessType(ctx context.Context, Req *v1.ListAccountsByUserAndBusinessTypeRequest, callOptions ...callopt.Option) (r *v1.ListAccountsByUserAndBusinessTypeResponse, err error)
	ListDayCutHistory(ctx context.Context, Req *v1.ListDayCutHistoryRequest, callOptions ...callopt.Option) (r *v1.ListDayCutHistoryResponse, err error)
	ListSnapshotDates(ctx context.Context, Req *v1.ListSnapshotDatesRequest, callOptions ...callopt.Option) (r *v1.ListSnapshotDatesResponse, err error)
	RebuildHotAccounts(ctx context.Context, Req *v1.RebuildHotAccountsRequest, callOptions ...callopt.Option) (r *v1.RebuildHotAccountsResponse, err error)
	TriggerDayCut(ctx context.Context, Req *v1.TriggerDayCutRequest, callOptions ...callopt.Option) (r *v1.TriggerDayCutResponse, err error)
	AdjustBalance(ctx context.Context, Req *v1.AdjustBalanceRequest, callOptions ...callopt.Option) (r *v1.AdjustBalanceResponse, err error)
	GetTccStatus(ctx context.Context, Req *v1.GetTccStatusRequest, callOptions ...callopt.Option) (r *v1.GetTccStatusResponse, err error)
	ListStuckTcc(ctx context.Context, Req *v1.ListStuckTccRequest, callOptions ...callopt.Option) (r *v1.ListStuckTccResponse, err error)
	CancelTcc(ctx context.Context, Req *v1.CancelTccRequest, callOptions ...callopt.Option) (r *v1.CancelTccResponse, err error)
	CancelTccBranch(ctx context.Context, Req *v1.CancelTccBranchRequest, callOptions ...callopt.Option) (r *v1.CancelTccBranchResponse, err error)
	RunTrialBalance(ctx context.Context, Req *v1.RunTrialBalanceRequest, callOptions ...callopt.Option) (r *v1.RunTrialBalanceResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAccountingServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAccountingServiceClient struct {
	*kClient
}

func (p *kAccountingServiceClient) CreateAccount(ctx context.Context, Req *v1.CreateAccountRequest, callOptions ...callopt.Option) (r *v1.CreateAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAccount(ctx, Req)
}

func (p *kAccountingServiceClient) GetAccount(ctx context.Context, Req *v1.GetAccountRequest, callOptions ...callopt.Option) (r *v1.GetAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAccount(ctx, Req)
}

func (p *kAccountingServiceClient) FreezeAccount(ctx context.Context, Req *v1.FreezeAccountRequest, callOptions ...callopt.Option) (r *v1.FreezeAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FreezeAccount(ctx, Req)
}

func (p *kAccountingServiceClient) UnfreezeAccount(ctx context.Context, Req *v1.UnfreezeAccountRequest, callOptions ...callopt.Option) (r *v1.UnfreezeAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnfreezeAccount(ctx, Req)
}

func (p *kAccountingServiceClient) DoubleEntryBooking(ctx context.Context, Req *v1.DoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.DoubleEntryBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DoubleEntryBooking(ctx, Req)
}

func (p *kAccountingServiceClient) BatchBooking(ctx context.Context, Req *v1.BatchBookingRequest, callOptions ...callopt.Option) (r *v1.BatchBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchBooking(ctx, Req)
}

func (p *kAccountingServiceClient) MoneyFlow(ctx context.Context, Req *v1.MoneyFlowRequest, callOptions ...callopt.Option) (r *v1.MoneyFlowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MoneyFlow(ctx, Req)
}

func (p *kAccountingServiceClient) HybridDoubleEntryBooking(ctx context.Context, Req *v1.HybridDoubleEntryBookingRequest, callOptions ...callopt.Option) (r *v1.HybridDoubleEntryBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HybridDoubleEntryBooking(ctx, Req)
}

func (p *kAccountingServiceClient) AtomicBatchBooking(ctx context.Context, Req *v1.AtomicBatchBookingRequest, callOptions ...callopt.Option) (r *v1.AtomicBatchBookingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AtomicBatchBooking(ctx, Req)
}

func (p *kAccountingServiceClient) GetTransaction(ctx context.Context, Req *v1.GetTransactionRequest, callOptions ...callopt.Option) (r *v1.GetTransactionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTransaction(ctx, Req)
}

func (p *kAccountingServiceClient) GetBalanceSnapshot(ctx context.Context, Req *v1.GetBalanceSnapshotRequest, callOptions ...callopt.Option) (r *v1.GetBalanceSnapshotResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBalanceSnapshot(ctx, Req)
}

func (p *kAccountingServiceClient) ListAccountsByUserAndBusinessType(ctx context.Context, Req *v1.ListAccountsByUserAndBusinessTypeRequest, callOptions ...callopt.Option) (r *v1.ListAccountsByUserAndBusinessTypeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAccountsByUserAndBusinessType(ctx, Req)
}

func (p *kAccountingServiceClient) ListDayCutHistory(ctx context.Context, Req *v1.ListDayCutHistoryRequest, callOptions ...callopt.Option) (r *v1.ListDayCutHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListDayCutHistory(ctx, Req)
}

func (p *kAccountingServiceClient) ListSnapshotDates(ctx context.Context, Req *v1.ListSnapshotDatesRequest, callOptions ...callopt.Option) (r *v1.ListSnapshotDatesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSnapshotDates(ctx, Req)
}

func (p *kAccountingServiceClient) RebuildHotAccounts(ctx context.Context, Req *v1.RebuildHotAccountsRequest, callOptions ...callopt.Option) (r *v1.RebuildHotAccountsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RebuildHotAccounts(ctx, Req)
}

func (p *kAccountingServiceClient) TriggerDayCut(ctx context.Context, Req *v1.TriggerDayCutRequest, callOptions ...callopt.Option) (r *v1.TriggerDayCutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TriggerDayCut(ctx, Req)
}

func (p *kAccountingServiceClient) AdjustBalance(ctx context.Context, Req *v1.AdjustBalanceRequest, callOptions ...callopt.Option) (r *v1.AdjustBalanceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdjustBalance(ctx, Req)
}

func (p *kAccountingServiceClient) GetTccStatus(ctx context.Context, Req *v1.GetTccStatusRequest, callOptions ...callopt.Option) (r *v1.GetTccStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTccStatus(ctx, Req)
}

func (p *kAccountingServiceClient) ListStuckTcc(ctx context.Context, Req *v1.ListStuckTccRequest, callOptions ...callopt.Option) (r *v1.ListStuckTccResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListStuckTcc(ctx, Req)
}

func (p *kAccountingServiceClient) CancelTcc(ctx context.Context, Req *v1.CancelTccRequest, callOptions ...callopt.Option) (r *v1.CancelTccResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelTcc(ctx, Req)
}

func (p *kAccountingServiceClient) CancelTccBranch(ctx context.Context, Req *v1.CancelTccBranchRequest, callOptions ...callopt.Option) (r *v1.CancelTccBranchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelTccBranch(ctx, Req)
}

func (p *kAccountingServiceClient) RunTrialBalance(ctx context.Context, Req *v1.RunTrialBalanceRequest, callOptions ...callopt.Option) (r *v1.RunTrialBalanceResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RunTrialBalance(ctx, Req)
}
