// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/cardpayment/v1/cardpayment.proto

package cardpaymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payment_token 由 card-center.CreatePaymentToken 颁发的一次性 token
	PaymentToken string `protobuf:"bytes,1,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	// pi_id 必须与 payment_token AAD 绑定一致
	PiId     string `protobuf:"bytes,2,opt,name=pi_id,json=piId,proto3" json:"pi_id,omitempty"`
	Amount   int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	// network 期望走的卡组织（"visa" / "mastercard" / ...）；空则按 BIN 自动判断
	Network string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// merchant_descriptor 商户描述（卡单上显示）
	MerchantDescriptor string `protobuf:"bytes,6,opt,name=merchant_descriptor,json=merchantDescriptor,proto3" json:"merchant_descriptor,omitempty"`
	// installment 分期（0 = 不分期）
	Installment int32 `protobuf:"varint,7,opt,name=installment,proto3" json:"installment,omitempty"`
	// three_ds_data 3DS 验证结果（前端走的 3DS challenge 通过后传过来）
	ThreeDsData   *ThreeDSData `protobuf:"bytes,8,opt,name=three_ds_data,json=threeDsData,proto3" json:"three_ds_data,omitempty"`
	TraceId       string       `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *AuthorizeRequest) GetPiId() string {
	if x != nil {
		return x.PiId
	}
	return ""
}

func (x *AuthorizeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AuthorizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AuthorizeRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *AuthorizeRequest) GetMerchantDescriptor() string {
	if x != nil {
		return x.MerchantDescriptor
	}
	return ""
}

func (x *AuthorizeRequest) GetInstallment() int32 {
	if x != nil {
		return x.Installment
	}
	return 0
}

func (x *AuthorizeRequest) GetThreeDsData() *ThreeDSData {
	if x != nil {
		return x.ThreeDsData
	}
	return nil
}

func (x *AuthorizeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network_ref_no 卡组织返的交易 id（用于后续 Capture / Refund 引用）
	NetworkRefNo  string `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // approved / declined / pending
	DeclineCode   string `protobuf:"bytes,3,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	DeclineReason string `protobuf:"bytes,4,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	MaskedPan     string `protobuf:"bytes,5,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	Network       string `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	// arn (Acquirer Reference Number) 对账用
	Arn           string `protobuf:"bytes,7,opt,name=arn,proto3" json:"arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *AuthorizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizeResponse) GetDeclineCode() string {
	if x != nil {
		return x.DeclineCode
	}
	return ""
}

func (x *AuthorizeResponse) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

func (x *AuthorizeResponse) GetMaskedPan() string {
	if x != nil {
		return x.MaskedPan
	}
	return ""
}

func (x *AuthorizeResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *AuthorizeResponse) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

type CaptureRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NetworkRefNo string                 `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	PiId         string                 `protobuf:"bytes,2,opt,name=pi_id,json=piId,proto3" json:"pi_id,omitempty"`
	// amount 部分捕获时小于授权金额；0 表示全额
	Amount        int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TraceId       string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureRequest) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *CaptureRequest) GetPiId() string {
	if x != nil {
		return x.PiId
	}
	return ""
}

func (x *CaptureRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CaptureRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CaptureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NetworkRefNo   string                 `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CapturedAmount int64                  `protobuf:"varint,3,opt,name=captured_amount,json=capturedAmount,proto3" json:"captured_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureResponse) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *CaptureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaptureResponse) GetCapturedAmount() int64 {
	if x != nil {
		return x.CapturedAmount
	}
	return 0
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkRefNo  string                 `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	PiId          string                 `protobuf:"bytes,2,opt,name=pi_id,json=piId,proto3" json:"pi_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	TraceId       string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{4}
}

func (x *RefundRequest) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *RefundRequest) GetPiId() string {
	if x != nil {
		return x.PiId
	}
	return ""
}

func (x *RefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type RefundResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RefundRefNo    string                 `protobuf:"bytes,1,opt,name=refund_ref_no,json=refundRefNo,proto3" json:"refund_ref_no,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RefundedAmount int64                  `protobuf:"varint,3,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{5}
}

func (x *RefundResponse) GetRefundRefNo() string {
	if x != nil {
		return x.RefundRefNo
	}
	return ""
}

func (x *RefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefundResponse) GetRefundedAmount() int64 {
	if x != nil {
		return x.RefundedAmount
	}
	return 0
}

type VoidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkRefNo  string                 `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	PiId          string                 `protobuf:"bytes,2,opt,name=pi_id,json=piId,proto3" json:"pi_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	TraceId       string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidRequest) Reset() {
	*x = VoidRequest{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidRequest) ProtoMessage() {}

func (x *VoidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidRequest.ProtoReflect.Descriptor instead.
func (*VoidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{6}
}

func (x *VoidRequest) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *VoidRequest) GetPiId() string {
	if x != nil {
		return x.PiId
	}
	return ""
}

func (x *VoidRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoidRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type VoidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidResponse) Reset() {
	*x = VoidResponse{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidResponse) ProtoMessage() {}

func (x *VoidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidResponse.ProtoReflect.Descriptor instead.
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{7}
}

func (x *VoidResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkRefNo  string                 `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	PiId          string                 `protobuf:"bytes,2,opt,name=pi_id,json=piId,proto3" json:"pi_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{8}
}

func (x *QueryRequest) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *QueryRequest) GetPiId() string {
	if x != nil {
		return x.PiId
	}
	return ""
}

func (x *QueryRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkRefNo  string                 `protobuf:"bytes,1,opt,name=network_ref_no,json=networkRefNo,proto3" json:"network_ref_no,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	DeclineCode   string                 `protobuf:"bytes,5,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResponse) GetNetworkRefNo() string {
	if x != nil {
		return x.NetworkRefNo
	}
	return ""
}

func (x *QueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QueryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QueryResponse) GetDeclineCode() string {
	if x != nil {
		return x.DeclineCode
	}
	return ""
}

// ThreeDSData 3DS 2.x 验证结果（仅在 frictionless / challenge 通过后存在）
type ThreeDSData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                        // "2.1.0" / "2.2.0"
	Eci           string                 `protobuf:"bytes,2,opt,name=eci,proto3" json:"eci,omitempty"`                                // 02/05 = 验证通过；07 = 未验证
	Cavv          string                 `protobuf:"bytes,3,opt,name=cavv,proto3" json:"cavv,omitempty"`                              // 卡持有人验证值（base64）
	Xid           string                 `protobuf:"bytes,4,opt,name=xid,proto3" json:"xid,omitempty"`                                // 交易标识
	DsTransId     string                 `protobuf:"bytes,5,opt,name=ds_trans_id,json=dsTransId,proto3" json:"ds_trans_id,omitempty"` // 卡组织 directory server 交易 id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreeDSData) Reset() {
	*x = ThreeDSData{}
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreeDSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreeDSData) ProtoMessage() {}

func (x *ThreeDSData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreeDSData.ProtoReflect.Descriptor instead.
func (*ThreeDSData) Descriptor() ([]byte, []int) {
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP(), []int{10}
}

func (x *ThreeDSData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ThreeDSData) GetEci() string {
	if x != nil {
		return x.Eci
	}
	return ""
}

func (x *ThreeDSData) GetCavv() string {
	if x != nil {
		return x.Cavv
	}
	return ""
}

func (x *ThreeDSData) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *ThreeDSData) GetDsTransId() string {
	if x != nil {
		return x.DsTransId
	}
	return ""
}

var File_api_proto_cardpayment_v1_cardpayment_proto protoreflect.FileDescriptor

const file_api_proto_cardpayment_v1_cardpayment_proto_rawDesc = "" +
	"\n" +
	"*api/proto/cardpayment/v1/cardpayment.proto\x12\x0ecardpayment.v1\"\xc9\x02\n" +
	"\x10AuthorizeRequest\x12#\n" +
	"\rpayment_token\x18\x01 \x01(\tR\fpaymentToken\x12\x13\n" +
	"\x05pi_id\x18\x02 \x01(\tR\x04piId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12/\n" +
	"\x13merchant_descriptor\x18\x06 \x01(\tR\x12merchantDescriptor\x12 \n" +
	"\vinstallment\x18\a \x01(\x05R\vinstallment\x12?\n" +
	"\rthree_ds_data\x18\b \x01(\v2\x1b.cardpayment.v1.ThreeDSDataR\vthreeDsData\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"\xe6\x01\n" +
	"\x11AuthorizeResponse\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fdecline_code\x18\x03 \x01(\tR\vdeclineCode\x12%\n" +
	"\x0edecline_reason\x18\x04 \x01(\tR\rdeclineReason\x12\x1d\n" +
	"\n" +
	"masked_pan\x18\x05 \x01(\tR\tmaskedPan\x12\x18\n" +
	"\anetwork\x18\x06 \x01(\tR\anetwork\x12\x10\n" +
	"\x03arn\x18\a \x01(\tR\x03arn\"~\n" +
	"\x0eCaptureRequest\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x13\n" +
	"\x05pi_id\x18\x02 \x01(\tR\x04piId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"x\n" +
	"\x0fCaptureResponse\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fcaptured_amount\x18\x03 \x01(\x03R\x0ecapturedAmount\"\x95\x01\n" +
	"\rRefundRequest\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x13\n" +
	"\x05pi_id\x18\x02 \x01(\tR\x04piId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"u\n" +
	"\x0eRefundResponse\x12\"\n" +
	"\rrefund_ref_no\x18\x01 \x01(\tR\vrefundRefNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0frefunded_amount\x18\x03 \x01(\x03R\x0erefundedAmount\"{\n" +
	"\vVoidRequest\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x13\n" +
	"\x05pi_id\x18\x02 \x01(\tR\x04piId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"&\n" +
	"\fVoidResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"d\n" +
	"\fQueryRequest\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x13\n" +
	"\x05pi_id\x18\x02 \x01(\tR\x04piId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"\xa4\x01\n" +
	"\rQueryResponse\x12$\n" +
	"\x0enetwork_ref_no\x18\x01 \x01(\tR\fnetworkRefNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fdecline_code\x18\x05 \x01(\tR\vdeclineCode\"\x7f\n" +
	"\vThreeDSData\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03eci\x18\x02 \x01(\tR\x03eci\x12\x12\n" +
	"\x04cavv\x18\x03 \x01(\tR\x04cavv\x12\x10\n" +
	"\x03xid\x18\x04 \x01(\tR\x03xid\x12\x1e\n" +
	"\vds_trans_id\x18\x05 \x01(\tR\tdsTransId2\xfd\x02\n" +
	"\vCardPayment\x12P\n" +
	"\tAuthorize\x12 .cardpayment.v1.AuthorizeRequest\x1a!.cardpayment.v1.AuthorizeResponse\x12J\n" +
	"\aCapture\x12\x1e.cardpayment.v1.CaptureRequest\x1a\x1f.cardpayment.v1.CaptureResponse\x12G\n" +
	"\x06Refund\x12\x1d.cardpayment.v1.RefundRequest\x1a\x1e.cardpayment.v1.RefundResponse\x12A\n" +
	"\x04Void\x12\x1b.cardpayment.v1.VoidRequest\x1a\x1c.cardpayment.v1.VoidResponse\x12D\n" +
	"\x05Query\x12\x1c.cardpayment.v1.QueryRequest\x1a\x1d.cardpayment.v1.QueryResponseBHZFgithub.com/xiongwp/card-payment/api/proto/cardpayment/v1;cardpaymentv1b\x06proto3"

var (
	file_api_proto_cardpayment_v1_cardpayment_proto_rawDescOnce sync.Once
	file_api_proto_cardpayment_v1_cardpayment_proto_rawDescData []byte
)

func file_api_proto_cardpayment_v1_cardpayment_proto_rawDescGZIP() []byte {
	file_api_proto_cardpayment_v1_cardpayment_proto_rawDescOnce.Do(func() {
		file_api_proto_cardpayment_v1_cardpayment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cardpayment_v1_cardpayment_proto_rawDesc), len(file_api_proto_cardpayment_v1_cardpayment_proto_rawDesc)))
	})
	return file_api_proto_cardpayment_v1_cardpayment_proto_rawDescData
}

var file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_cardpayment_v1_cardpayment_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),  // 0: cardpayment.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 1: cardpayment.v1.AuthorizeResponse
	(*CaptureRequest)(nil),    // 2: cardpayment.v1.CaptureRequest
	(*CaptureResponse)(nil),   // 3: cardpayment.v1.CaptureResponse
	(*RefundRequest)(nil),     // 4: cardpayment.v1.RefundRequest
	(*RefundResponse)(nil),    // 5: cardpayment.v1.RefundResponse
	(*VoidRequest)(nil),       // 6: cardpayment.v1.VoidRequest
	(*VoidResponse)(nil),      // 7: cardpayment.v1.VoidResponse
	(*QueryRequest)(nil),      // 8: cardpayment.v1.QueryRequest
	(*QueryResponse)(nil),     // 9: cardpayment.v1.QueryResponse
	(*ThreeDSData)(nil),       // 10: cardpayment.v1.ThreeDSData
}
var file_api_proto_cardpayment_v1_cardpayment_proto_depIdxs = []int32{
	10, // 0: cardpayment.v1.AuthorizeRequest.three_ds_data:type_name -> cardpayment.v1.ThreeDSData
	0,  // 1: cardpayment.v1.CardPayment.Authorize:input_type -> cardpayment.v1.AuthorizeRequest
	2,  // 2: cardpayment.v1.CardPayment.Capture:input_type -> cardpayment.v1.CaptureRequest
	4,  // 3: cardpayment.v1.CardPayment.Refund:input_type -> cardpayment.v1.RefundRequest
	6,  // 4: cardpayment.v1.CardPayment.Void:input_type -> cardpayment.v1.VoidRequest
	8,  // 5: cardpayment.v1.CardPayment.Query:input_type -> cardpayment.v1.QueryRequest
	1,  // 6: cardpayment.v1.CardPayment.Authorize:output_type -> cardpayment.v1.AuthorizeResponse
	3,  // 7: cardpayment.v1.CardPayment.Capture:output_type -> cardpayment.v1.CaptureResponse
	5,  // 8: cardpayment.v1.CardPayment.Refund:output_type -> cardpayment.v1.RefundResponse
	7,  // 9: cardpayment.v1.CardPayment.Void:output_type -> cardpayment.v1.VoidResponse
	9,  // 10: cardpayment.v1.CardPayment.Query:output_type -> cardpayment.v1.QueryResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_cardpayment_v1_cardpayment_proto_init() }
func file_api_proto_cardpayment_v1_cardpayment_proto_init() {
	if File_api_proto_cardpayment_v1_cardpayment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cardpayment_v1_cardpayment_proto_rawDesc), len(file_api_proto_cardpayment_v1_cardpayment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cardpayment_v1_cardpayment_proto_goTypes,
		DependencyIndexes: file_api_proto_cardpayment_v1_cardpayment_proto_depIdxs,
		MessageInfos:      file_api_proto_cardpayment_v1_cardpayment_proto_msgTypes,
	}.Build()
	File_api_proto_cardpayment_v1_cardpayment_proto = out.File
	file_api_proto_cardpayment_v1_cardpayment_proto_goTypes = nil
	file_api_proto_cardpayment_v1_cardpayment_proto_depIdxs = nil
}
