// Code generated by Kitex v0.16.2. DO NOT EDIT.

package merchantservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	usermerchantv1 "github.com/xiongwp/user-merchant-core/kitex_gen/usermerchant/v1"
	v1 "github.com/xiongwp/user-merchant-core/kitex_gen/usermerchant/v1"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Create": kitex.NewMethodInfo(
		createHandler,
		newCreateArgs,
		newCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Get": kitex.NewMethodInfo(
		getHandler,
		newGetArgs,
		newGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchGet": kitex.NewMethodInfo(
		batchGetHandler,
		newBatchGetArgs,
		newBatchGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"List": kitex.NewMethodInfo(
		listHandler,
		newListArgs,
		newListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Update": kitex.NewMethodInfo(
		updateHandler,
		newUpdateArgs,
		newUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RotateApiKey": kitex.NewMethodInfo(
		rotateApiKeyHandler,
		newRotateApiKeyArgs,
		newRotateApiKeyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SubmitKyc": kitex.NewMethodInfo(
		submitKycHandler,
		newSubmitKycArgs,
		newSubmitKycResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"StartReview": kitex.NewMethodInfo(
		startReviewHandler,
		newStartReviewArgs,
		newStartReviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Approve": kitex.NewMethodInfo(
		approveHandler,
		newApproveArgs,
		newApproveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Reject": kitex.NewMethodInfo(
		rejectHandler,
		newRejectArgs,
		newRejectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RequestMoreInfo": kitex.NewMethodInfo(
		requestMoreInfoHandler,
		newRequestMoreInfoArgs,
		newRequestMoreInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Suspend": kitex.NewMethodInfo(
		suspendHandler,
		newSuspendArgs,
		newSuspendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Unsuspend": kitex.NewMethodInfo(
		unsuspendHandler,
		newUnsuspendArgs,
		newUnsuspendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Terminate": kitex.NewMethodInfo(
		terminateHandler,
		newTerminateArgs,
		newTerminateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AddDocument": kitex.NewMethodInfo(
		addDocumentHandler,
		newAddDocumentArgs,
		newAddDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListDocuments": kitex.NewMethodInfo(
		listDocumentsHandler,
		newListDocumentsArgs,
		newListDocumentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReviewDocument": kitex.NewMethodInfo(
		reviewDocumentHandler,
		newReviewDocumentArgs,
		newReviewDocumentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListAudits": kitex.NewMethodInfo(
		listAuditsHandler,
		newListAuditsArgs,
		newListAuditsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	merchantServiceServiceInfo                = NewServiceInfo()
	merchantServiceServiceInfoForClient       = NewServiceInfoForClient()
	merchantServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return merchantServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return merchantServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return merchantServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MerchantService"
	handlerType := (*usermerchantv1.MerchantService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "usermerchant.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateMerchantRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Create(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateArgs:
		success, err := handler.(usermerchantv1.MerchantService).Create(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateArgs() interface{} {
	return &CreateArgs{}
}

func newCreateResult() interface{} {
	return &CreateResult{}
}

type CreateArgs struct {
	Req *v1.CreateMerchantRequest
}

func (p *CreateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateMerchantRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateArgs_Req_DEFAULT *v1.CreateMerchantRequest

func (p *CreateArgs) GetReq() *v1.CreateMerchantRequest {
	if !p.IsSetReq() {
		return CreateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateResult struct {
	Success *v1.CreateMerchantResponse
}

var CreateResult_Success_DEFAULT *v1.CreateMerchantResponse

func (p *CreateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateMerchantResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateResult) GetSuccess() *v1.CreateMerchantResponse {
	if !p.IsSetSuccess() {
		return CreateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateMerchantResponse)
}

func (p *CreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateResult) GetResult() interface{} {
	return p.Success
}

func getHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetMerchantRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Get(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetArgs:
		success, err := handler.(usermerchantv1.MerchantService).Get(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetArgs() interface{} {
	return &GetArgs{}
}

func newGetResult() interface{} {
	return &GetResult{}
}

type GetArgs struct {
	Req *v1.GetMerchantRequest
}

func (p *GetArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetMerchantRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetArgs_Req_DEFAULT *v1.GetMerchantRequest

func (p *GetArgs) GetReq() *v1.GetMerchantRequest {
	if !p.IsSetReq() {
		return GetArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetResult struct {
	Success *v1.GetMerchantResponse
}

var GetResult_Success_DEFAULT *v1.GetMerchantResponse

func (p *GetResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetResult) Unmarshal(in []byte) error {
	msg := new(v1.GetMerchantResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetResult) GetSuccess() *v1.GetMerchantResponse {
	if !p.IsSetSuccess() {
		return GetResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetMerchantResponse)
}

func (p *GetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetResult) GetResult() interface{} {
	return p.Success
}

func batchGetHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.BatchGetMerchantsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).BatchGet(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchGetArgs:
		success, err := handler.(usermerchantv1.MerchantService).BatchGet(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchGetResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchGetArgs() interface{} {
	return &BatchGetArgs{}
}

func newBatchGetResult() interface{} {
	return &BatchGetResult{}
}

type BatchGetArgs struct {
	Req *v1.BatchGetMerchantsRequest
}

func (p *BatchGetArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchGetArgs) Unmarshal(in []byte) error {
	msg := new(v1.BatchGetMerchantsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchGetArgs_Req_DEFAULT *v1.BatchGetMerchantsRequest

func (p *BatchGetArgs) GetReq() *v1.BatchGetMerchantsRequest {
	if !p.IsSetReq() {
		return BatchGetArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchGetArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchGetArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchGetResult struct {
	Success *v1.BatchGetMerchantsResponse
}

var BatchGetResult_Success_DEFAULT *v1.BatchGetMerchantsResponse

func (p *BatchGetResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchGetResult) Unmarshal(in []byte) error {
	msg := new(v1.BatchGetMerchantsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchGetResult) GetSuccess() *v1.BatchGetMerchantsResponse {
	if !p.IsSetSuccess() {
		return BatchGetResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchGetResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.BatchGetMerchantsResponse)
}

func (p *BatchGetResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchGetResult) GetResult() interface{} {
	return p.Success
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListMerchantsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).List(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListArgs:
		success, err := handler.(usermerchantv1.MerchantService).List(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListArgs() interface{} {
	return &ListArgs{}
}

func newListResult() interface{} {
	return &ListResult{}
}

type ListArgs struct {
	Req *v1.ListMerchantsRequest
}

func (p *ListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListMerchantsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListArgs_Req_DEFAULT *v1.ListMerchantsRequest

func (p *ListArgs) GetReq() *v1.ListMerchantsRequest {
	if !p.IsSetReq() {
		return ListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListResult struct {
	Success *v1.ListMerchantsResponse
}

var ListResult_Success_DEFAULT *v1.ListMerchantsResponse

func (p *ListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListResult) Unmarshal(in []byte) error {
	msg := new(v1.ListMerchantsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListResult) GetSuccess() *v1.ListMerchantsResponse {
	if !p.IsSetSuccess() {
		return ListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListMerchantsResponse)
}

func (p *ListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListResult) GetResult() interface{} {
	return p.Success
}

func updateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateMerchantRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Update(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateArgs:
		success, err := handler.(usermerchantv1.MerchantService).Update(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateArgs() interface{} {
	return &UpdateArgs{}
}

func newUpdateResult() interface{} {
	return &UpdateResult{}
}

type UpdateArgs struct {
	Req *v1.UpdateMerchantRequest
}

func (p *UpdateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateMerchantRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateArgs_Req_DEFAULT *v1.UpdateMerchantRequest

func (p *UpdateArgs) GetReq() *v1.UpdateMerchantRequest {
	if !p.IsSetReq() {
		return UpdateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateResult struct {
	Success *v1.UpdateMerchantResponse
}

var UpdateResult_Success_DEFAULT *v1.UpdateMerchantResponse

func (p *UpdateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdateMerchantResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateResult) GetSuccess() *v1.UpdateMerchantResponse {
	if !p.IsSetSuccess() {
		return UpdateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdateMerchantResponse)
}

func (p *UpdateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateResult) GetResult() interface{} {
	return p.Success
}

func rotateApiKeyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RotateApiKeyRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).RotateApiKey(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RotateApiKeyArgs:
		success, err := handler.(usermerchantv1.MerchantService).RotateApiKey(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RotateApiKeyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRotateApiKeyArgs() interface{} {
	return &RotateApiKeyArgs{}
}

func newRotateApiKeyResult() interface{} {
	return &RotateApiKeyResult{}
}

type RotateApiKeyArgs struct {
	Req *v1.RotateApiKeyRequest
}

func (p *RotateApiKeyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RotateApiKeyArgs) Unmarshal(in []byte) error {
	msg := new(v1.RotateApiKeyRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RotateApiKeyArgs_Req_DEFAULT *v1.RotateApiKeyRequest

func (p *RotateApiKeyArgs) GetReq() *v1.RotateApiKeyRequest {
	if !p.IsSetReq() {
		return RotateApiKeyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RotateApiKeyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RotateApiKeyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RotateApiKeyResult struct {
	Success *v1.RotateApiKeyResponse
}

var RotateApiKeyResult_Success_DEFAULT *v1.RotateApiKeyResponse

func (p *RotateApiKeyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RotateApiKeyResult) Unmarshal(in []byte) error {
	msg := new(v1.RotateApiKeyResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RotateApiKeyResult) GetSuccess() *v1.RotateApiKeyResponse {
	if !p.IsSetSuccess() {
		return RotateApiKeyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RotateApiKeyResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RotateApiKeyResponse)
}

func (p *RotateApiKeyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RotateApiKeyResult) GetResult() interface{} {
	return p.Success
}

func submitKycHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).SubmitKyc(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SubmitKycArgs:
		success, err := handler.(usermerchantv1.MerchantService).SubmitKyc(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SubmitKycResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSubmitKycArgs() interface{} {
	return &SubmitKycArgs{}
}

func newSubmitKycResult() interface{} {
	return &SubmitKycResult{}
}

type SubmitKycArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *SubmitKycArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SubmitKycArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SubmitKycArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *SubmitKycArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return SubmitKycArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SubmitKycArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SubmitKycArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SubmitKycResult struct {
	Success *v1.KycTransitionResponse
}

var SubmitKycResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *SubmitKycResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SubmitKycResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SubmitKycResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return SubmitKycResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SubmitKycResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *SubmitKycResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SubmitKycResult) GetResult() interface{} {
	return p.Success
}

func startReviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).StartReview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *StartReviewArgs:
		success, err := handler.(usermerchantv1.MerchantService).StartReview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*StartReviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newStartReviewArgs() interface{} {
	return &StartReviewArgs{}
}

func newStartReviewResult() interface{} {
	return &StartReviewResult{}
}

type StartReviewArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *StartReviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *StartReviewArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var StartReviewArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *StartReviewArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return StartReviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *StartReviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StartReviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type StartReviewResult struct {
	Success *v1.KycTransitionResponse
}

var StartReviewResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *StartReviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *StartReviewResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *StartReviewResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return StartReviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *StartReviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *StartReviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StartReviewResult) GetResult() interface{} {
	return p.Success
}

func approveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Approve(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ApproveArgs:
		success, err := handler.(usermerchantv1.MerchantService).Approve(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ApproveResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newApproveArgs() interface{} {
	return &ApproveArgs{}
}

func newApproveResult() interface{} {
	return &ApproveResult{}
}

type ApproveArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *ApproveArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ApproveArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ApproveArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *ApproveArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return ApproveArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ApproveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ApproveArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ApproveResult struct {
	Success *v1.KycTransitionResponse
}

var ApproveResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *ApproveResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ApproveResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ApproveResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return ApproveResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ApproveResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *ApproveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ApproveResult) GetResult() interface{} {
	return p.Success
}

func rejectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Reject(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RejectArgs:
		success, err := handler.(usermerchantv1.MerchantService).Reject(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RejectResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRejectArgs() interface{} {
	return &RejectArgs{}
}

func newRejectResult() interface{} {
	return &RejectResult{}
}

type RejectArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *RejectArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RejectArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RejectArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *RejectArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return RejectArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RejectArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RejectArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RejectResult struct {
	Success *v1.KycTransitionResponse
}

var RejectResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *RejectResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RejectResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RejectResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return RejectResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RejectResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *RejectResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RejectResult) GetResult() interface{} {
	return p.Success
}

func requestMoreInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).RequestMoreInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RequestMoreInfoArgs:
		success, err := handler.(usermerchantv1.MerchantService).RequestMoreInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RequestMoreInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRequestMoreInfoArgs() interface{} {
	return &RequestMoreInfoArgs{}
}

func newRequestMoreInfoResult() interface{} {
	return &RequestMoreInfoResult{}
}

type RequestMoreInfoArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *RequestMoreInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RequestMoreInfoArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RequestMoreInfoArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *RequestMoreInfoArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return RequestMoreInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RequestMoreInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RequestMoreInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RequestMoreInfoResult struct {
	Success *v1.KycTransitionResponse
}

var RequestMoreInfoResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *RequestMoreInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RequestMoreInfoResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RequestMoreInfoResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return RequestMoreInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RequestMoreInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *RequestMoreInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RequestMoreInfoResult) GetResult() interface{} {
	return p.Success
}

func suspendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Suspend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SuspendArgs:
		success, err := handler.(usermerchantv1.MerchantService).Suspend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SuspendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSuspendArgs() interface{} {
	return &SuspendArgs{}
}

func newSuspendResult() interface{} {
	return &SuspendResult{}
}

type SuspendArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *SuspendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SuspendArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SuspendArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *SuspendArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return SuspendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SuspendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SuspendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SuspendResult struct {
	Success *v1.KycTransitionResponse
}

var SuspendResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *SuspendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SuspendResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SuspendResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return SuspendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SuspendResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *SuspendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SuspendResult) GetResult() interface{} {
	return p.Success
}

func unsuspendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Unsuspend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnsuspendArgs:
		success, err := handler.(usermerchantv1.MerchantService).Unsuspend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnsuspendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnsuspendArgs() interface{} {
	return &UnsuspendArgs{}
}

func newUnsuspendResult() interface{} {
	return &UnsuspendResult{}
}

type UnsuspendArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *UnsuspendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnsuspendArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnsuspendArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *UnsuspendArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return UnsuspendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnsuspendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnsuspendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnsuspendResult struct {
	Success *v1.KycTransitionResponse
}

var UnsuspendResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *UnsuspendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnsuspendResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnsuspendResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return UnsuspendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnsuspendResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *UnsuspendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnsuspendResult) GetResult() interface{} {
	return p.Success
}

func terminateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.KycTransitionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).Terminate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *TerminateArgs:
		success, err := handler.(usermerchantv1.MerchantService).Terminate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TerminateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newTerminateArgs() interface{} {
	return &TerminateArgs{}
}

func newTerminateResult() interface{} {
	return &TerminateResult{}
}

type TerminateArgs struct {
	Req *v1.KycTransitionRequest
}

func (p *TerminateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *TerminateArgs) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TerminateArgs_Req_DEFAULT *v1.KycTransitionRequest

func (p *TerminateArgs) GetReq() *v1.KycTransitionRequest {
	if !p.IsSetReq() {
		return TerminateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TerminateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TerminateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TerminateResult struct {
	Success *v1.KycTransitionResponse
}

var TerminateResult_Success_DEFAULT *v1.KycTransitionResponse

func (p *TerminateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *TerminateResult) Unmarshal(in []byte) error {
	msg := new(v1.KycTransitionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TerminateResult) GetSuccess() *v1.KycTransitionResponse {
	if !p.IsSetSuccess() {
		return TerminateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TerminateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.KycTransitionResponse)
}

func (p *TerminateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TerminateResult) GetResult() interface{} {
	return p.Success
}

func addDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.AddKycDocumentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).AddDocument(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddDocumentArgs:
		success, err := handler.(usermerchantv1.MerchantService).AddDocument(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddDocumentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddDocumentArgs() interface{} {
	return &AddDocumentArgs{}
}

func newAddDocumentResult() interface{} {
	return &AddDocumentResult{}
}

type AddDocumentArgs struct {
	Req *v1.AddKycDocumentRequest
}

func (p *AddDocumentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddDocumentArgs) Unmarshal(in []byte) error {
	msg := new(v1.AddKycDocumentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddDocumentArgs_Req_DEFAULT *v1.AddKycDocumentRequest

func (p *AddDocumentArgs) GetReq() *v1.AddKycDocumentRequest {
	if !p.IsSetReq() {
		return AddDocumentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddDocumentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddDocumentResult struct {
	Success *v1.AddKycDocumentResponse
}

var AddDocumentResult_Success_DEFAULT *v1.AddKycDocumentResponse

func (p *AddDocumentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddDocumentResult) Unmarshal(in []byte) error {
	msg := new(v1.AddKycDocumentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddDocumentResult) GetSuccess() *v1.AddKycDocumentResponse {
	if !p.IsSetSuccess() {
		return AddDocumentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.AddKycDocumentResponse)
}

func (p *AddDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddDocumentResult) GetResult() interface{} {
	return p.Success
}

func listDocumentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListKycDocumentsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).ListDocuments(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListDocumentsArgs:
		success, err := handler.(usermerchantv1.MerchantService).ListDocuments(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListDocumentsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListDocumentsArgs() interface{} {
	return &ListDocumentsArgs{}
}

func newListDocumentsResult() interface{} {
	return &ListDocumentsResult{}
}

type ListDocumentsArgs struct {
	Req *v1.ListKycDocumentsRequest
}

func (p *ListDocumentsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListDocumentsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListKycDocumentsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListDocumentsArgs_Req_DEFAULT *v1.ListKycDocumentsRequest

func (p *ListDocumentsArgs) GetReq() *v1.ListKycDocumentsRequest {
	if !p.IsSetReq() {
		return ListDocumentsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListDocumentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListDocumentsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListDocumentsResult struct {
	Success *v1.ListKycDocumentsResponse
}

var ListDocumentsResult_Success_DEFAULT *v1.ListKycDocumentsResponse

func (p *ListDocumentsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListDocumentsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListKycDocumentsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListDocumentsResult) GetSuccess() *v1.ListKycDocumentsResponse {
	if !p.IsSetSuccess() {
		return ListDocumentsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListDocumentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListKycDocumentsResponse)
}

func (p *ListDocumentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListDocumentsResult) GetResult() interface{} {
	return p.Success
}

func reviewDocumentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ReviewKycDocumentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).ReviewDocument(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReviewDocumentArgs:
		success, err := handler.(usermerchantv1.MerchantService).ReviewDocument(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReviewDocumentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReviewDocumentArgs() interface{} {
	return &ReviewDocumentArgs{}
}

func newReviewDocumentResult() interface{} {
	return &ReviewDocumentResult{}
}

type ReviewDocumentArgs struct {
	Req *v1.ReviewKycDocumentRequest
}

func (p *ReviewDocumentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReviewDocumentArgs) Unmarshal(in []byte) error {
	msg := new(v1.ReviewKycDocumentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReviewDocumentArgs_Req_DEFAULT *v1.ReviewKycDocumentRequest

func (p *ReviewDocumentArgs) GetReq() *v1.ReviewKycDocumentRequest {
	if !p.IsSetReq() {
		return ReviewDocumentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReviewDocumentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReviewDocumentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReviewDocumentResult struct {
	Success *v1.ReviewKycDocumentResponse
}

var ReviewDocumentResult_Success_DEFAULT *v1.ReviewKycDocumentResponse

func (p *ReviewDocumentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReviewDocumentResult) Unmarshal(in []byte) error {
	msg := new(v1.ReviewKycDocumentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReviewDocumentResult) GetSuccess() *v1.ReviewKycDocumentResponse {
	if !p.IsSetSuccess() {
		return ReviewDocumentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReviewDocumentResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ReviewKycDocumentResponse)
}

func (p *ReviewDocumentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReviewDocumentResult) GetResult() interface{} {
	return p.Success
}

func listAuditsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListKycAuditsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(usermerchantv1.MerchantService).ListAudits(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListAuditsArgs:
		success, err := handler.(usermerchantv1.MerchantService).ListAudits(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListAuditsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListAuditsArgs() interface{} {
	return &ListAuditsArgs{}
}

func newListAuditsResult() interface{} {
	return &ListAuditsResult{}
}

type ListAuditsArgs struct {
	Req *v1.ListKycAuditsRequest
}

func (p *ListAuditsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListAuditsArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListKycAuditsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListAuditsArgs_Req_DEFAULT *v1.ListKycAuditsRequest

func (p *ListAuditsArgs) GetReq() *v1.ListKycAuditsRequest {
	if !p.IsSetReq() {
		return ListAuditsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListAuditsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListAuditsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListAuditsResult struct {
	Success *v1.ListKycAuditsResponse
}

var ListAuditsResult_Success_DEFAULT *v1.ListKycAuditsResponse

func (p *ListAuditsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListAuditsResult) Unmarshal(in []byte) error {
	msg := new(v1.ListKycAuditsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListAuditsResult) GetSuccess() *v1.ListKycAuditsResponse {
	if !p.IsSetSuccess() {
		return ListAuditsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListAuditsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListKycAuditsResponse)
}

func (p *ListAuditsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListAuditsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Create(ctx context.Context, Req *v1.CreateMerchantRequest) (r *v1.CreateMerchantResponse, err error) {
	var _args CreateArgs
	_args.Req = Req
	var _result CreateResult
	if err = p.c.Call(ctx, "Create", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Get(ctx context.Context, Req *v1.GetMerchantRequest) (r *v1.GetMerchantResponse, err error) {
	var _args GetArgs
	_args.Req = Req
	var _result GetResult
	if err = p.c.Call(ctx, "Get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGet(ctx context.Context, Req *v1.BatchGetMerchantsRequest) (r *v1.BatchGetMerchantsResponse, err error) {
	var _args BatchGetArgs
	_args.Req = Req
	var _result BatchGetResult
	if err = p.c.Call(ctx, "BatchGet", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, Req *v1.ListMerchantsRequest) (r *v1.ListMerchantsResponse, err error) {
	var _args ListArgs
	_args.Req = Req
	var _result ListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Update(ctx context.Context, Req *v1.UpdateMerchantRequest) (r *v1.UpdateMerchantResponse, err error) {
	var _args UpdateArgs
	_args.Req = Req
	var _result UpdateResult
	if err = p.c.Call(ctx, "Update", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RotateApiKey(ctx context.Context, Req *v1.RotateApiKeyRequest) (r *v1.RotateApiKeyResponse, err error) {
	var _args RotateApiKeyArgs
	_args.Req = Req
	var _result RotateApiKeyResult
	if err = p.c.Call(ctx, "RotateApiKey", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SubmitKyc(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args SubmitKycArgs
	_args.Req = Req
	var _result SubmitKycResult
	if err = p.c.Call(ctx, "SubmitKyc", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartReview(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args StartReviewArgs
	_args.Req = Req
	var _result StartReviewResult
	if err = p.c.Call(ctx, "StartReview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Approve(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args ApproveArgs
	_args.Req = Req
	var _result ApproveResult
	if err = p.c.Call(ctx, "Approve", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Reject(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args RejectArgs
	_args.Req = Req
	var _result RejectResult
	if err = p.c.Call(ctx, "Reject", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestMoreInfo(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args RequestMoreInfoArgs
	_args.Req = Req
	var _result RequestMoreInfoResult
	if err = p.c.Call(ctx, "RequestMoreInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Suspend(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args SuspendArgs
	_args.Req = Req
	var _result SuspendResult
	if err = p.c.Call(ctx, "Suspend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Unsuspend(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args UnsuspendArgs
	_args.Req = Req
	var _result UnsuspendResult
	if err = p.c.Call(ctx, "Unsuspend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Terminate(ctx context.Context, Req *v1.KycTransitionRequest) (r *v1.KycTransitionResponse, err error) {
	var _args TerminateArgs
	_args.Req = Req
	var _result TerminateResult
	if err = p.c.Call(ctx, "Terminate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddDocument(ctx context.Context, Req *v1.AddKycDocumentRequest) (r *v1.AddKycDocumentResponse, err error) {
	var _args AddDocumentArgs
	_args.Req = Req
	var _result AddDocumentResult
	if err = p.c.Call(ctx, "AddDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListDocuments(ctx context.Context, Req *v1.ListKycDocumentsRequest) (r *v1.ListKycDocumentsResponse, err error) {
	var _args ListDocumentsArgs
	_args.Req = Req
	var _result ListDocumentsResult
	if err = p.c.Call(ctx, "ListDocuments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReviewDocument(ctx context.Context, Req *v1.ReviewKycDocumentRequest) (r *v1.ReviewKycDocumentResponse, err error) {
	var _args ReviewDocumentArgs
	_args.Req = Req
	var _result ReviewDocumentResult
	if err = p.c.Call(ctx, "ReviewDocument", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAudits(ctx context.Context, Req *v1.ListKycAuditsRequest) (r *v1.ListKycAuditsResponse, err error) {
	var _args ListAuditsArgs
	_args.Req = Req
	var _result ListAuditsResult
	if err = p.c.Call(ctx, "ListAudits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
