// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/order/v1/order.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentIntentService_Create_FullMethodName               = "/order.v1.PaymentIntentService/Create"
	PaymentIntentService_Retrieve_FullMethodName             = "/order.v1.PaymentIntentService/Retrieve"
	PaymentIntentService_Update_FullMethodName               = "/order.v1.PaymentIntentService/Update"
	PaymentIntentService_Confirm_FullMethodName              = "/order.v1.PaymentIntentService/Confirm"
	PaymentIntentService_ConfirmPaymentAction_FullMethodName = "/order.v1.PaymentIntentService/ConfirmPaymentAction"
	PaymentIntentService_Capture_FullMethodName              = "/order.v1.PaymentIntentService/Capture"
	PaymentIntentService_Cancel_FullMethodName               = "/order.v1.PaymentIntentService/Cancel"
	PaymentIntentService_List_FullMethodName                 = "/order.v1.PaymentIntentService/List"
)

// PaymentIntentServiceClient is the client API for PaymentIntentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentIntentService PaymentIntent 生命周期（Stripe API 风格）
type PaymentIntentServiceClient interface {
	Create(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error)
	Retrieve(ctx context.Context, in *RetrievePaymentIntentRequest, opts ...grpc.CallOption) (*RetrievePaymentIntentResponse, error)
	Update(ctx context.Context, in *UpdatePaymentIntentRequest, opts ...grpc.CallOption) (*UpdatePaymentIntentResponse, error)
	Confirm(ctx context.Context, in *ConfirmPaymentIntentRequest, opts ...grpc.CallOption) (*ConfirmPaymentIntentResponse, error)
	// ConfirmPaymentAction 收银台回传用户挑战结果（OTP / 密码 / 3DS token）
	ConfirmPaymentAction(ctx context.Context, in *ConfirmPaymentActionRequest, opts ...grpc.CallOption) (*ConfirmPaymentActionResponse, error)
	Capture(ctx context.Context, in *CapturePaymentIntentRequest, opts ...grpc.CallOption) (*CapturePaymentIntentResponse, error)
	Cancel(ctx context.Context, in *CancelPaymentIntentRequest, opts ...grpc.CallOption) (*CancelPaymentIntentResponse, error)
	List(ctx context.Context, in *ListPaymentIntentsRequest, opts ...grpc.CallOption) (*ListPaymentIntentsResponse, error)
}

type paymentIntentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentIntentServiceClient(cc grpc.ClientConnInterface) PaymentIntentServiceClient {
	return &paymentIntentServiceClient{cc}
}

func (c *paymentIntentServiceClient) Create(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) Retrieve(ctx context.Context, in *RetrievePaymentIntentRequest, opts ...grpc.CallOption) (*RetrievePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrievePaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) Update(ctx context.Context, in *UpdatePaymentIntentRequest, opts ...grpc.CallOption) (*UpdatePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) Confirm(ctx context.Context, in *ConfirmPaymentIntentRequest, opts ...grpc.CallOption) (*ConfirmPaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) ConfirmPaymentAction(ctx context.Context, in *ConfirmPaymentActionRequest, opts ...grpc.CallOption) (*ConfirmPaymentActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentActionResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_ConfirmPaymentAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) Capture(ctx context.Context, in *CapturePaymentIntentRequest, opts ...grpc.CallOption) (*CapturePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapturePaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) Cancel(ctx context.Context, in *CancelPaymentIntentRequest, opts ...grpc.CallOption) (*CancelPaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPaymentIntentResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentIntentServiceClient) List(ctx context.Context, in *ListPaymentIntentsRequest, opts ...grpc.CallOption) (*ListPaymentIntentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentIntentsResponse)
	err := c.cc.Invoke(ctx, PaymentIntentService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentIntentServiceServer is the server API for PaymentIntentService service.
// All implementations must embed UnimplementedPaymentIntentServiceServer
// for forward compatibility.
//
// PaymentIntentService PaymentIntent 生命周期（Stripe API 风格）
type PaymentIntentServiceServer interface {
	Create(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error)
	Retrieve(context.Context, *RetrievePaymentIntentRequest) (*RetrievePaymentIntentResponse, error)
	Update(context.Context, *UpdatePaymentIntentRequest) (*UpdatePaymentIntentResponse, error)
	Confirm(context.Context, *ConfirmPaymentIntentRequest) (*ConfirmPaymentIntentResponse, error)
	// ConfirmPaymentAction 收银台回传用户挑战结果（OTP / 密码 / 3DS token）
	ConfirmPaymentAction(context.Context, *ConfirmPaymentActionRequest) (*ConfirmPaymentActionResponse, error)
	Capture(context.Context, *CapturePaymentIntentRequest) (*CapturePaymentIntentResponse, error)
	Cancel(context.Context, *CancelPaymentIntentRequest) (*CancelPaymentIntentResponse, error)
	List(context.Context, *ListPaymentIntentsRequest) (*ListPaymentIntentsResponse, error)
	mustEmbedUnimplementedPaymentIntentServiceServer()
}

// UnimplementedPaymentIntentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentIntentServiceServer struct{}

func (UnimplementedPaymentIntentServiceServer) Create(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPaymentIntentServiceServer) Retrieve(context.Context, *RetrievePaymentIntentRequest) (*RetrievePaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedPaymentIntentServiceServer) Update(context.Context, *UpdatePaymentIntentRequest) (*UpdatePaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPaymentIntentServiceServer) Confirm(context.Context, *ConfirmPaymentIntentRequest) (*ConfirmPaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedPaymentIntentServiceServer) ConfirmPaymentAction(context.Context, *ConfirmPaymentActionRequest) (*ConfirmPaymentActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPaymentAction not implemented")
}
func (UnimplementedPaymentIntentServiceServer) Capture(context.Context, *CapturePaymentIntentRequest) (*CapturePaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedPaymentIntentServiceServer) Cancel(context.Context, *CancelPaymentIntentRequest) (*CancelPaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedPaymentIntentServiceServer) List(context.Context, *ListPaymentIntentsRequest) (*ListPaymentIntentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPaymentIntentServiceServer) mustEmbedUnimplementedPaymentIntentServiceServer() {}
func (UnimplementedPaymentIntentServiceServer) testEmbeddedByValue()                              {}

// UnsafePaymentIntentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentIntentServiceServer will
// result in compilation errors.
type UnsafePaymentIntentServiceServer interface {
	mustEmbedUnimplementedPaymentIntentServiceServer()
}

func RegisterPaymentIntentServiceServer(s grpc.ServiceRegistrar, srv PaymentIntentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentIntentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentIntentService_ServiceDesc, srv)
}

func _PaymentIntentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).Create(ctx, req.(*CreatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).Retrieve(ctx, req.(*RetrievePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).Update(ctx, req.(*UpdatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).Confirm(ctx, req.(*ConfirmPaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_ConfirmPaymentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).ConfirmPaymentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_ConfirmPaymentAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).ConfirmPaymentAction(ctx, req.(*ConfirmPaymentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapturePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).Capture(ctx, req.(*CapturePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).Cancel(ctx, req.(*CancelPaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentIntentService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentIntentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentIntentServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentIntentService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentIntentServiceServer).List(ctx, req.(*ListPaymentIntentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentIntentService_ServiceDesc is the grpc.ServiceDesc for PaymentIntentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentIntentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.PaymentIntentService",
	HandlerType: (*PaymentIntentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PaymentIntentService_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _PaymentIntentService_Retrieve_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PaymentIntentService_Update_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _PaymentIntentService_Confirm_Handler,
		},
		{
			MethodName: "ConfirmPaymentAction",
			Handler:    _PaymentIntentService_ConfirmPaymentAction_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _PaymentIntentService_Capture_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _PaymentIntentService_Cancel_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PaymentIntentService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/order/v1/order.proto",
}

const (
	WebhookService_Ingest_FullMethodName = "/order.v1.WebhookService/Ingest"
)

// WebhookServiceClient is the client API for WebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebhookService 接收异步通知：渠道 webhook 或收银台 / 客户端主动推送
type WebhookServiceClient interface {
	Ingest(ctx context.Context, in *IngestWebhookRequest, opts ...grpc.CallOption) (*IngestWebhookResponse, error)
}

type webhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookServiceClient(cc grpc.ClientConnInterface) WebhookServiceClient {
	return &webhookServiceClient{cc}
}

func (c *webhookServiceClient) Ingest(ctx context.Context, in *IngestWebhookRequest, opts ...grpc.CallOption) (*IngestWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookServiceServer is the server API for WebhookService service.
// All implementations must embed UnimplementedWebhookServiceServer
// for forward compatibility.
//
// WebhookService 接收异步通知：渠道 webhook 或收银台 / 客户端主动推送
type WebhookServiceServer interface {
	Ingest(context.Context, *IngestWebhookRequest) (*IngestWebhookResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

// UnimplementedWebhookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookServiceServer struct{}

func (UnimplementedWebhookServiceServer) Ingest(context.Context, *IngestWebhookRequest) (*IngestWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}
func (UnimplementedWebhookServiceServer) testEmbeddedByValue()                        {}

// UnsafeWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookServiceServer will
// result in compilation errors.
type UnsafeWebhookServiceServer interface {
	mustEmbedUnimplementedWebhookServiceServer()
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func _WebhookService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).Ingest(ctx, req.(*IngestWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookService_ServiceDesc is the grpc.ServiceDesc for WebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _WebhookService_Ingest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/order/v1/order.proto",
}

const (
	ChargeService_Retrieve_FullMethodName = "/order.v1.ChargeService/Retrieve"
	ChargeService_List_FullMethodName     = "/order.v1.ChargeService/List"
)

// ChargeServiceClient is the client API for ChargeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChargeService Charge 查询
type ChargeServiceClient interface {
	Retrieve(ctx context.Context, in *RetrieveChargeRequest, opts ...grpc.CallOption) (*RetrieveChargeResponse, error)
	List(ctx context.Context, in *ListChargesRequest, opts ...grpc.CallOption) (*ListChargesResponse, error)
}

type chargeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChargeServiceClient(cc grpc.ClientConnInterface) ChargeServiceClient {
	return &chargeServiceClient{cc}
}

func (c *chargeServiceClient) Retrieve(ctx context.Context, in *RetrieveChargeRequest, opts ...grpc.CallOption) (*RetrieveChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveChargeResponse)
	err := c.cc.Invoke(ctx, ChargeService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chargeServiceClient) List(ctx context.Context, in *ListChargesRequest, opts ...grpc.CallOption) (*ListChargesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChargesResponse)
	err := c.cc.Invoke(ctx, ChargeService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChargeServiceServer is the server API for ChargeService service.
// All implementations must embed UnimplementedChargeServiceServer
// for forward compatibility.
//
// ChargeService Charge 查询
type ChargeServiceServer interface {
	Retrieve(context.Context, *RetrieveChargeRequest) (*RetrieveChargeResponse, error)
	List(context.Context, *ListChargesRequest) (*ListChargesResponse, error)
	mustEmbedUnimplementedChargeServiceServer()
}

// UnimplementedChargeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChargeServiceServer struct{}

func (UnimplementedChargeServiceServer) Retrieve(context.Context, *RetrieveChargeRequest) (*RetrieveChargeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedChargeServiceServer) List(context.Context, *ListChargesRequest) (*ListChargesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedChargeServiceServer) mustEmbedUnimplementedChargeServiceServer() {}
func (UnimplementedChargeServiceServer) testEmbeddedByValue()                       {}

// UnsafeChargeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChargeServiceServer will
// result in compilation errors.
type UnsafeChargeServiceServer interface {
	mustEmbedUnimplementedChargeServiceServer()
}

func RegisterChargeServiceServer(s grpc.ServiceRegistrar, srv ChargeServiceServer) {
	// If the following call panics, it indicates UnimplementedChargeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChargeService_ServiceDesc, srv)
}

func _ChargeService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargeServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChargeService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargeServiceServer).Retrieve(ctx, req.(*RetrieveChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChargeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChargesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChargeService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargeServiceServer).List(ctx, req.(*ListChargesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChargeService_ServiceDesc is the grpc.ServiceDesc for ChargeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChargeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.ChargeService",
	HandlerType: (*ChargeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _ChargeService_Retrieve_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ChargeService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/order/v1/order.proto",
}

const (
	RefundService_Create_FullMethodName   = "/order.v1.RefundService/Create"
	RefundService_Retrieve_FullMethodName = "/order.v1.RefundService/Retrieve"
	RefundService_List_FullMethodName     = "/order.v1.RefundService/List"
)

// RefundServiceClient is the client API for RefundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RefundService Refund 生命周期
type RefundServiceClient interface {
	Create(ctx context.Context, in *CreateRefundRequest, opts ...grpc.CallOption) (*CreateRefundResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRefundRequest, opts ...grpc.CallOption) (*RetrieveRefundResponse, error)
	List(ctx context.Context, in *ListRefundsRequest, opts ...grpc.CallOption) (*ListRefundsResponse, error)
}

type refundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRefundServiceClient(cc grpc.ClientConnInterface) RefundServiceClient {
	return &refundServiceClient{cc}
}

func (c *refundServiceClient) Create(ctx context.Context, in *CreateRefundRequest, opts ...grpc.CallOption) (*CreateRefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRefundResponse)
	err := c.cc.Invoke(ctx, RefundService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundServiceClient) Retrieve(ctx context.Context, in *RetrieveRefundRequest, opts ...grpc.CallOption) (*RetrieveRefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveRefundResponse)
	err := c.cc.Invoke(ctx, RefundService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundServiceClient) List(ctx context.Context, in *ListRefundsRequest, opts ...grpc.CallOption) (*ListRefundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRefundsResponse)
	err := c.cc.Invoke(ctx, RefundService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundServiceServer is the server API for RefundService service.
// All implementations must embed UnimplementedRefundServiceServer
// for forward compatibility.
//
// RefundService Refund 生命周期
type RefundServiceServer interface {
	Create(context.Context, *CreateRefundRequest) (*CreateRefundResponse, error)
	Retrieve(context.Context, *RetrieveRefundRequest) (*RetrieveRefundResponse, error)
	List(context.Context, *ListRefundsRequest) (*ListRefundsResponse, error)
	mustEmbedUnimplementedRefundServiceServer()
}

// UnimplementedRefundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefundServiceServer struct{}

func (UnimplementedRefundServiceServer) Create(context.Context, *CreateRefundRequest) (*CreateRefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRefundServiceServer) Retrieve(context.Context, *RetrieveRefundRequest) (*RetrieveRefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedRefundServiceServer) List(context.Context, *ListRefundsRequest) (*ListRefundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRefundServiceServer) mustEmbedUnimplementedRefundServiceServer() {}
func (UnimplementedRefundServiceServer) testEmbeddedByValue()                       {}

// UnsafeRefundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefundServiceServer will
// result in compilation errors.
type UnsafeRefundServiceServer interface {
	mustEmbedUnimplementedRefundServiceServer()
}

func RegisterRefundServiceServer(s grpc.ServiceRegistrar, srv RefundServiceServer) {
	// If the following call panics, it indicates UnimplementedRefundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RefundService_ServiceDesc, srv)
}

func _RefundService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).Create(ctx, req.(*CreateRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).Retrieve(ctx, req.(*RetrieveRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRefundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RefundService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).List(ctx, req.(*ListRefundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RefundService_ServiceDesc is the grpc.ServiceDesc for RefundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RefundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.RefundService",
	HandlerType: (*RefundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _RefundService_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _RefundService_Retrieve_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RefundService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/order/v1/order.proto",
}
