// payment-core 暴露给 order-core 的 gRPC 面。形状严格对齐 order-core
// internal/channel.PaymentChannel —— 就是把 Go interface 翻译成 proto。
//
// order-core 的 channel.PaymentChannel 接口有 6 个方法：
//   Charge / Capture / Void / Refund / Query / ParseWebhook
// ParseWebhook 在 gRPC 里对应 ForwardWebhook：order-core 收到渠道回调后把原始
// headers/body 转给 payment-core，payment-core 做签名校验 + 规范化。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/paymentcore/v1/paymentcore.proto

package paymentcorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId  string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ChargeId         string                 `protobuf:"bytes,2,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	Amount           int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Country          string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`                                             // 用于路由
	PaymentMethod    string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`            // GCASH / MAYA / GRABPAY / COINS_PH / INSTAPAY / PESONET / VISA / ...
	PaymentMethodRef string                 `protobuf:"bytes,7,opt,name=payment_method_ref,json=paymentMethodRef,proto3" json:"payment_method_ref,omitempty"` // token / card_token / wallet_id / account_no
	CustomerId       string                 `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CaptureMethod    string                 `protobuf:"bytes,9,opt,name=capture_method,json=captureMethod,proto3" json:"capture_method,omitempty"` // automatic / manual
	ReturnUrl        string                 `protobuf:"bytes,10,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	NotifyUrl        string                 `protobuf:"bytes,11,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Description      string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extra            map[string]string      `protobuf:"bytes,14,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChargeRequest) Reset() {
	*x = ChargeRequest{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequest) ProtoMessage() {}

func (x *ChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequest.ProtoReflect.Descriptor instead.
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ChargeRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *ChargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChargeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ChargeRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ChargeRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ChargeRequest) GetPaymentMethodRef() string {
	if x != nil {
		return x.PaymentMethodRef
	}
	return ""
}

func (x *ChargeRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ChargeRequest) GetCaptureMethod() string {
	if x != nil {
		return x.CaptureMethod
	}
	return ""
}

func (x *ChargeRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *ChargeRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *ChargeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChargeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChargeRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type RequiredAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ChallengeRef  string                 `protobuf:"bytes,3,opt,name=challenge_ref,json=challengeRef,proto3" json:"challenge_ref,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredAction) Reset() {
	*x = RequiredAction{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredAction) ProtoMessage() {}

func (x *RequiredAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredAction.ProtoReflect.Descriptor instead.
func (*RequiredAction) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{1}
}

func (x *RequiredAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequiredAction) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RequiredAction) GetChallengeRef() string {
	if x != nil {
		return x.ChallengeRef
	}
	return ""
}

func (x *RequiredAction) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ChargeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResultType       string                 `protobuf:"bytes,1,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"` // succeeded / authorized / processing / requires_action / failed
	ExternalRefNo    string                 `protobuf:"bytes,2,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	AuthCode         string                 `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	AmountAuthorized int64                  `protobuf:"varint,4,opt,name=amount_authorized,json=amountAuthorized,proto3" json:"amount_authorized,omitempty"`
	AmountCaptured   int64                  `protobuf:"varint,5,opt,name=amount_captured,json=amountCaptured,proto3" json:"amount_captured,omitempty"`
	RequiredAction   *RequiredAction        `protobuf:"bytes,6,opt,name=required_action,json=requiredAction,proto3" json:"required_action,omitempty"`
	FailureCode      string                 `protobuf:"bytes,7,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage   string                 `protobuf:"bytes,8,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	RiskLevel        string                 `protobuf:"bytes,9,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskScore        int32                  `protobuf:"varint,10,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RawResponse      map[string]string      `protobuf:"bytes,11,rep,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChargeResponse) Reset() {
	*x = ChargeResponse{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponse) ProtoMessage() {}

func (x *ChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponse.ProtoReflect.Descriptor instead.
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{2}
}

func (x *ChargeResponse) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *ChargeResponse) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *ChargeResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *ChargeResponse) GetAmountAuthorized() int64 {
	if x != nil {
		return x.AmountAuthorized
	}
	return 0
}

func (x *ChargeResponse) GetAmountCaptured() int64 {
	if x != nil {
		return x.AmountCaptured
	}
	return 0
}

func (x *ChargeResponse) GetRequiredAction() *RequiredAction {
	if x != nil {
		return x.RequiredAction
	}
	return nil
}

func (x *ChargeResponse) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *ChargeResponse) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *ChargeResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ChargeResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *ChargeResponse) GetRawResponse() map[string]string {
	if x != nil {
		return x.RawResponse
	}
	return nil
}

type CaptureRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ChargeId        string                 `protobuf:"bytes,2,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	ExternalRefNo   string                 `protobuf:"bytes,3,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	Amount          int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *CaptureRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *CaptureRequest) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *CaptureRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CaptureRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type VoidRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ChargeId        string                 `protobuf:"bytes,2,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	ExternalRefNo   string                 `protobuf:"bytes,3,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoidRequest) Reset() {
	*x = VoidRequest{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidRequest) ProtoMessage() {}

func (x *VoidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidRequest.ProtoReflect.Descriptor instead.
func (*VoidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{4}
}

func (x *VoidRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *VoidRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *VoidRequest) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *VoidRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoidRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type RefundRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ChargeId        string                 `protobuf:"bytes,2,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	RefundId        string                 `protobuf:"bytes,3,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	ExternalRefNo   string                 `protobuf:"bytes,4,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	Amount          int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Reason          string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{5}
}

func (x *RefundRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *RefundRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *RefundRequest) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RefundRequest) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *RefundRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type OpResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultType     string                 `protobuf:"bytes,1,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	ExternalRefNo  string                 `protobuf:"bytes,2,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	FailureCode    string                 `protobuf:"bytes,3,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage string                 `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	RawResponse    map[string]string      `protobuf:"bytes,5,rep,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{6}
}

func (x *OpResponse) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *OpResponse) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *OpResponse) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *OpResponse) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *OpResponse) GetRawResponse() map[string]string {
	if x != nil {
		return x.RawResponse
	}
	return nil
}

type QueryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ChargeId        string                 `protobuf:"bytes,2,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	ExternalRefNo   string                 `protobuf:"bytes,3,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	Extra           map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *QueryRequest) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *QueryRequest) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *QueryRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type QueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultType     string                 `protobuf:"bytes,1,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	ExternalRefNo  string                 `protobuf:"bytes,2,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	AmountCaptured int64                  `protobuf:"varint,3,opt,name=amount_captured,json=amountCaptured,proto3" json:"amount_captured,omitempty"`
	AmountRefunded int64                  `protobuf:"varint,4,opt,name=amount_refunded,json=amountRefunded,proto3" json:"amount_refunded,omitempty"`
	FailureCode    string                 `protobuf:"bytes,5,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage string                 `protobuf:"bytes,6,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	RawResponse    map[string]string      `protobuf:"bytes,7,rep,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *QueryResponse) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *QueryResponse) GetAmountCaptured() int64 {
	if x != nil {
		return x.AmountCaptured
	}
	return 0
}

func (x *QueryResponse) GetAmountRefunded() int64 {
	if x != nil {
		return x.AmountRefunded
	}
	return 0
}

func (x *QueryResponse) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *QueryResponse) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *QueryResponse) GetRawResponse() map[string]string {
	if x != nil {
		return x.RawResponse
	}
	return nil
}

type ParseWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adapter       string                 `protobuf:"bytes,1,opt,name=adapter,proto3" json:"adapter,omitempty"` // 可选；空则 payment-core 自行识别
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseWebhookRequest) Reset() {
	*x = ParseWebhookRequest{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseWebhookRequest) ProtoMessage() {}

func (x *ParseWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseWebhookRequest.ProtoReflect.Descriptor instead.
func (*ParseWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{9}
}

func (x *ParseWebhookRequest) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *ParseWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ParseWebhookRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type WebhookEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType       string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PaymentIntentId string                 `protobuf:"bytes,3,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	ChargeId        string                 `protobuf:"bytes,4,opt,name=charge_id,json=chargeId,proto3" json:"charge_id,omitempty"`
	RefundId        string                 `protobuf:"bytes,5,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	ExternalRefNo   string                 `protobuf:"bytes,6,opt,name=external_ref_no,json=externalRefNo,proto3" json:"external_ref_no,omitempty"`
	Amount          int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RawPayload      map[string]string      `protobuf:"bytes,9,rep,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP(), []int{10}
}

func (x *WebhookEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WebhookEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WebhookEvent) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *WebhookEvent) GetChargeId() string {
	if x != nil {
		return x.ChargeId
	}
	return ""
}

func (x *WebhookEvent) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *WebhookEvent) GetExternalRefNo() string {
	if x != nil {
		return x.ExternalRefNo
	}
	return ""
}

func (x *WebhookEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WebhookEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WebhookEvent) GetRawPayload() map[string]string {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

var File_api_proto_paymentcore_v1_paymentcore_proto protoreflect.FileDescriptor

const file_api_proto_paymentcore_v1_paymentcore_proto_rawDesc = "" +
	"\n" +
	"*api/proto/paymentcore/v1/paymentcore.proto\x12\x0epaymentcore.v1\"\xa3\x05\n" +
	"\rChargeRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1b\n" +
	"\tcharge_id\x18\x02 \x01(\tR\bchargeId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\x12,\n" +
	"\x12payment_method_ref\x18\a \x01(\tR\x10paymentMethodRef\x12\x1f\n" +
	"\vcustomer_id\x18\b \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0ecapture_method\x18\t \x01(\tR\rcaptureMethod\x12\x1d\n" +
	"\n" +
	"return_url\x18\n" +
	" \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"notify_url\x18\v \x01(\tR\tnotifyUrl\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12G\n" +
	"\bmetadata\x18\r \x03(\v2+.paymentcore.v1.ChargeRequest.MetadataEntryR\bmetadata\x12>\n" +
	"\x05extra\x18\x0e \x03(\v2(.paymentcore.v1.ChargeRequest.ExtraEntryR\x05extra\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x0eRequiredAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12#\n" +
	"\rchallenge_ref\x18\x03 \x01(\tR\fchallengeRef\x12E\n" +
	"\adetails\x18\x04 \x03(\v2+.paymentcore.v1.RequiredAction.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x04\n" +
	"\x0eChargeResponse\x12\x1f\n" +
	"\vresult_type\x18\x01 \x01(\tR\n" +
	"resultType\x12&\n" +
	"\x0fexternal_ref_no\x18\x02 \x01(\tR\rexternalRefNo\x12\x1b\n" +
	"\tauth_code\x18\x03 \x01(\tR\bauthCode\x12+\n" +
	"\x11amount_authorized\x18\x04 \x01(\x03R\x10amountAuthorized\x12'\n" +
	"\x0famount_captured\x18\x05 \x01(\x03R\x0eamountCaptured\x12G\n" +
	"\x0frequired_action\x18\x06 \x01(\v2\x1e.paymentcore.v1.RequiredActionR\x0erequiredAction\x12!\n" +
	"\ffailure_code\x18\a \x01(\tR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\b \x01(\tR\x0efailureMessage\x12\x1d\n" +
	"\n" +
	"risk_level\x18\t \x01(\tR\triskLevel\x12\x1d\n" +
	"\n" +
	"risk_score\x18\n" +
	" \x01(\x05R\triskScore\x12R\n" +
	"\fraw_response\x18\v \x03(\v2/.paymentcore.v1.ChargeResponse.RawResponseEntryR\vrawResponse\x1a>\n" +
	"\x10RawResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x02\n" +
	"\x0eCaptureRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1b\n" +
	"\tcharge_id\x18\x02 \x01(\tR\bchargeId\x12&\n" +
	"\x0fexternal_ref_no\x18\x03 \x01(\tR\rexternalRefNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12?\n" +
	"\x05extra\x18\x05 \x03(\v2).paymentcore.v1.CaptureRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x02\n" +
	"\vVoidRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1b\n" +
	"\tcharge_id\x18\x02 \x01(\tR\bchargeId\x12&\n" +
	"\x0fexternal_ref_no\x18\x03 \x01(\tR\rexternalRefNo\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12<\n" +
	"\x05extra\x18\x05 \x03(\v2&.paymentcore.v1.VoidRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\rRefundRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1b\n" +
	"\tcharge_id\x18\x02 \x01(\tR\bchargeId\x12\x1b\n" +
	"\trefund_id\x18\x03 \x01(\tR\brefundId\x12&\n" +
	"\x0fexternal_ref_no\x18\x04 \x01(\tR\rexternalRefNo\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12>\n" +
	"\x05extra\x18\b \x03(\v2(.paymentcore.v1.RefundRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x02\n" +
	"\n" +
	"OpResponse\x12\x1f\n" +
	"\vresult_type\x18\x01 \x01(\tR\n" +
	"resultType\x12&\n" +
	"\x0fexternal_ref_no\x18\x02 \x01(\tR\rexternalRefNo\x12!\n" +
	"\ffailure_code\x18\x03 \x01(\tR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\x04 \x01(\tR\x0efailureMessage\x12N\n" +
	"\fraw_response\x18\x05 \x03(\v2+.paymentcore.v1.OpResponse.RawResponseEntryR\vrawResponse\x1a>\n" +
	"\x10RawResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\fQueryRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1b\n" +
	"\tcharge_id\x18\x02 \x01(\tR\bchargeId\x12&\n" +
	"\x0fexternal_ref_no\x18\x03 \x01(\tR\rexternalRefNo\x12=\n" +
	"\x05extra\x18\x04 \x03(\v2'.paymentcore.v1.QueryRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x03\n" +
	"\rQueryResponse\x12\x1f\n" +
	"\vresult_type\x18\x01 \x01(\tR\n" +
	"resultType\x12&\n" +
	"\x0fexternal_ref_no\x18\x02 \x01(\tR\rexternalRefNo\x12'\n" +
	"\x0famount_captured\x18\x03 \x01(\x03R\x0eamountCaptured\x12'\n" +
	"\x0famount_refunded\x18\x04 \x01(\x03R\x0eamountRefunded\x12!\n" +
	"\ffailure_code\x18\x05 \x01(\tR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\x06 \x01(\tR\x0efailureMessage\x12Q\n" +
	"\fraw_response\x18\a \x03(\v2..paymentcore.v1.QueryResponse.RawResponseEntryR\vrawResponse\x1a>\n" +
	"\x10RawResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x13ParseWebhookRequest\x12\x18\n" +
	"\aadapter\x18\x01 \x01(\tR\aadapter\x12J\n" +
	"\aheaders\x18\x02 \x03(\v20.paymentcore.v1.ParseWebhookRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x03\n" +
	"\fWebhookEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12*\n" +
	"\x11payment_intent_id\x18\x03 \x01(\tR\x0fpaymentIntentId\x12\x1b\n" +
	"\tcharge_id\x18\x04 \x01(\tR\bchargeId\x12\x1b\n" +
	"\trefund_id\x18\x05 \x01(\tR\brefundId\x12&\n" +
	"\x0fexternal_ref_no\x18\x06 \x01(\tR\rexternalRefNo\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12M\n" +
	"\vraw_payload\x18\t \x03(\v2,.paymentcore.v1.WebhookEvent.RawPayloadEntryR\n" +
	"rawPayload\x1a=\n" +
	"\x0fRawPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc3\x03\n" +
	"\x12PaymentCoreService\x12G\n" +
	"\x06Charge\x12\x1d.paymentcore.v1.ChargeRequest\x1a\x1e.paymentcore.v1.ChargeResponse\x12E\n" +
	"\aCapture\x12\x1e.paymentcore.v1.CaptureRequest\x1a\x1a.paymentcore.v1.OpResponse\x12?\n" +
	"\x04Void\x12\x1b.paymentcore.v1.VoidRequest\x1a\x1a.paymentcore.v1.OpResponse\x12C\n" +
	"\x06Refund\x12\x1d.paymentcore.v1.RefundRequest\x1a\x1a.paymentcore.v1.OpResponse\x12D\n" +
	"\x05Query\x12\x1c.paymentcore.v1.QueryRequest\x1a\x1d.paymentcore.v1.QueryResponse\x12Q\n" +
	"\fParseWebhook\x12#.paymentcore.v1.ParseWebhookRequest\x1a\x1c.paymentcore.v1.WebhookEventBHZFgithub.com/xiongwp/payment-core/api/proto/paymentcore/v1;paymentcorev1b\x06proto3"

var (
	file_api_proto_paymentcore_v1_paymentcore_proto_rawDescOnce sync.Once
	file_api_proto_paymentcore_v1_paymentcore_proto_rawDescData []byte
)

func file_api_proto_paymentcore_v1_paymentcore_proto_rawDescGZIP() []byte {
	file_api_proto_paymentcore_v1_paymentcore_proto_rawDescOnce.Do(func() {
		file_api_proto_paymentcore_v1_paymentcore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_paymentcore_v1_paymentcore_proto_rawDesc), len(file_api_proto_paymentcore_v1_paymentcore_proto_rawDesc)))
	})
	return file_api_proto_paymentcore_v1_paymentcore_proto_rawDescData
}

var file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_paymentcore_v1_paymentcore_proto_goTypes = []any{
	(*ChargeRequest)(nil),       // 0: paymentcore.v1.ChargeRequest
	(*RequiredAction)(nil),      // 1: paymentcore.v1.RequiredAction
	(*ChargeResponse)(nil),      // 2: paymentcore.v1.ChargeResponse
	(*CaptureRequest)(nil),      // 3: paymentcore.v1.CaptureRequest
	(*VoidRequest)(nil),         // 4: paymentcore.v1.VoidRequest
	(*RefundRequest)(nil),       // 5: paymentcore.v1.RefundRequest
	(*OpResponse)(nil),          // 6: paymentcore.v1.OpResponse
	(*QueryRequest)(nil),        // 7: paymentcore.v1.QueryRequest
	(*QueryResponse)(nil),       // 8: paymentcore.v1.QueryResponse
	(*ParseWebhookRequest)(nil), // 9: paymentcore.v1.ParseWebhookRequest
	(*WebhookEvent)(nil),        // 10: paymentcore.v1.WebhookEvent
	nil,                         // 11: paymentcore.v1.ChargeRequest.MetadataEntry
	nil,                         // 12: paymentcore.v1.ChargeRequest.ExtraEntry
	nil,                         // 13: paymentcore.v1.RequiredAction.DetailsEntry
	nil,                         // 14: paymentcore.v1.ChargeResponse.RawResponseEntry
	nil,                         // 15: paymentcore.v1.CaptureRequest.ExtraEntry
	nil,                         // 16: paymentcore.v1.VoidRequest.ExtraEntry
	nil,                         // 17: paymentcore.v1.RefundRequest.ExtraEntry
	nil,                         // 18: paymentcore.v1.OpResponse.RawResponseEntry
	nil,                         // 19: paymentcore.v1.QueryRequest.ExtraEntry
	nil,                         // 20: paymentcore.v1.QueryResponse.RawResponseEntry
	nil,                         // 21: paymentcore.v1.ParseWebhookRequest.HeadersEntry
	nil,                         // 22: paymentcore.v1.WebhookEvent.RawPayloadEntry
}
var file_api_proto_paymentcore_v1_paymentcore_proto_depIdxs = []int32{
	11, // 0: paymentcore.v1.ChargeRequest.metadata:type_name -> paymentcore.v1.ChargeRequest.MetadataEntry
	12, // 1: paymentcore.v1.ChargeRequest.extra:type_name -> paymentcore.v1.ChargeRequest.ExtraEntry
	13, // 2: paymentcore.v1.RequiredAction.details:type_name -> paymentcore.v1.RequiredAction.DetailsEntry
	1,  // 3: paymentcore.v1.ChargeResponse.required_action:type_name -> paymentcore.v1.RequiredAction
	14, // 4: paymentcore.v1.ChargeResponse.raw_response:type_name -> paymentcore.v1.ChargeResponse.RawResponseEntry
	15, // 5: paymentcore.v1.CaptureRequest.extra:type_name -> paymentcore.v1.CaptureRequest.ExtraEntry
	16, // 6: paymentcore.v1.VoidRequest.extra:type_name -> paymentcore.v1.VoidRequest.ExtraEntry
	17, // 7: paymentcore.v1.RefundRequest.extra:type_name -> paymentcore.v1.RefundRequest.ExtraEntry
	18, // 8: paymentcore.v1.OpResponse.raw_response:type_name -> paymentcore.v1.OpResponse.RawResponseEntry
	19, // 9: paymentcore.v1.QueryRequest.extra:type_name -> paymentcore.v1.QueryRequest.ExtraEntry
	20, // 10: paymentcore.v1.QueryResponse.raw_response:type_name -> paymentcore.v1.QueryResponse.RawResponseEntry
	21, // 11: paymentcore.v1.ParseWebhookRequest.headers:type_name -> paymentcore.v1.ParseWebhookRequest.HeadersEntry
	22, // 12: paymentcore.v1.WebhookEvent.raw_payload:type_name -> paymentcore.v1.WebhookEvent.RawPayloadEntry
	0,  // 13: paymentcore.v1.PaymentCoreService.Charge:input_type -> paymentcore.v1.ChargeRequest
	3,  // 14: paymentcore.v1.PaymentCoreService.Capture:input_type -> paymentcore.v1.CaptureRequest
	4,  // 15: paymentcore.v1.PaymentCoreService.Void:input_type -> paymentcore.v1.VoidRequest
	5,  // 16: paymentcore.v1.PaymentCoreService.Refund:input_type -> paymentcore.v1.RefundRequest
	7,  // 17: paymentcore.v1.PaymentCoreService.Query:input_type -> paymentcore.v1.QueryRequest
	9,  // 18: paymentcore.v1.PaymentCoreService.ParseWebhook:input_type -> paymentcore.v1.ParseWebhookRequest
	2,  // 19: paymentcore.v1.PaymentCoreService.Charge:output_type -> paymentcore.v1.ChargeResponse
	6,  // 20: paymentcore.v1.PaymentCoreService.Capture:output_type -> paymentcore.v1.OpResponse
	6,  // 21: paymentcore.v1.PaymentCoreService.Void:output_type -> paymentcore.v1.OpResponse
	6,  // 22: paymentcore.v1.PaymentCoreService.Refund:output_type -> paymentcore.v1.OpResponse
	8,  // 23: paymentcore.v1.PaymentCoreService.Query:output_type -> paymentcore.v1.QueryResponse
	10, // 24: paymentcore.v1.PaymentCoreService.ParseWebhook:output_type -> paymentcore.v1.WebhookEvent
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_paymentcore_v1_paymentcore_proto_init() }
func file_api_proto_paymentcore_v1_paymentcore_proto_init() {
	if File_api_proto_paymentcore_v1_paymentcore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_paymentcore_v1_paymentcore_proto_rawDesc), len(file_api_proto_paymentcore_v1_paymentcore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_paymentcore_v1_paymentcore_proto_goTypes,
		DependencyIndexes: file_api_proto_paymentcore_v1_paymentcore_proto_depIdxs,
		MessageInfos:      file_api_proto_paymentcore_v1_paymentcore_proto_msgTypes,
	}.Build()
	File_api_proto_paymentcore_v1_paymentcore_proto = out.File
	file_api_proto_paymentcore_v1_paymentcore_proto_goTypes = nil
	file_api_proto_paymentcore_v1_paymentcore_proto_depIdxs = nil
}
