-- oauth2-server 分库分表 schema 入口.
--
-- 这是 *指南* 而不是直接可跑的 SQL。
-- 真实 schema 由 generate.sh 输出 10 个独立 init SQL 文件:
--
--   0_init.sql  →  oauth2_db_0 (clients_00..09 + revoked_tokens_00..09 + admin_audit_00..09 + rsa_keys + client_index)
--   1_init.sql  →  oauth2_db_1 (clients_10..19 + revoked_tokens_10..19 + admin_audit_10..19)
--   2_init.sql  →  oauth2_db_2 (clients_20..29 + ...)
--   ...
--   9_init.sql  →  oauth2_db_9 (clients_90..99 + ...)
--
-- 跟 user-merchant-core/database/userdb/init/0_init.sql..9_init.sql 同模式.
--
-- ──────────────────────────────────────────────────────────────────
-- 生成 + 部署:
-- ──────────────────────────────────────────────────────────────────
--
--   bash generate.sh
--
--   # 单机多 DB (dev):
--   for i in 0 1 2 3 4 5 6 7 8 9; do
--     mysql -h localhost -uroot -p < ${i}_init.sql
--   done
--
--   # 跨主机真分片 (生产):
--   for i in 0 1 2 3 4 5 6 7 8 9; do
--     mysql -h "mysql-shard-${i}.internal" -uroot -p < ${i}_init.sql
--   done
--
-- ──────────────────────────────────────────────────────────────────
-- 分片策略 (Router.RouteByKey, FNV-1a hash):
-- ──────────────────────────────────────────────────────────────────
--   clients         按 client_id  → 100 shard
--   revoked_tokens  按 jti        → 100 shard
--   admin_audit     按 actor      → 100 shard (跟 u-m-c admin_audit_log 同模式)
--   rsa_keys        全局单表       (放 oauth2_db_0)
--   client_index    全局映射表     (放 oauth2_db_0)
--
-- ──────────────────────────────────────────────────────────────────
-- 跨服务一致性:
-- ──────────────────────────────────────────────────────────────────
-- FNV-1a hash + n % 100 → (dbIdx=n/10, tableIdx=n) 跟以下服务完全对齐:
--   - user-merchant-core (admin_audit_log_NN)
--   - order-core         (按 user_id / merchant_id 分片)
--   - accounting-system  (按 account_id 分片)
--   - payment-channel    (按 channel_tx_id 分片)
--
-- 同 actor / merchant 跨服务落同一逻辑分片号, ops 排查 / 跨服务 join 时
-- SQL 拼接省心。
