-- AUTO-GENERATED by generate.sh — do not edit by hand
-- 物理库: oauth2_db_7
-- 持有: clients_70..79, revoked_tokens_70..79, admin_audit_70..79

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `oauth2_db_7` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `oauth2_db_7`;

-- ─── clients_70 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_70` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 70)';

-- ─── revoked_tokens_70 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_70` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 70)';

-- ─── admin_audit_70 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_70` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 70)';

-- ─── clients_71 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_71` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 71)';

-- ─── revoked_tokens_71 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_71` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 71)';

-- ─── admin_audit_71 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_71` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 71)';

-- ─── clients_72 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_72` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 72)';

-- ─── revoked_tokens_72 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_72` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 72)';

-- ─── admin_audit_72 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_72` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 72)';

-- ─── clients_73 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_73` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 73)';

-- ─── revoked_tokens_73 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_73` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 73)';

-- ─── admin_audit_73 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_73` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 73)';

-- ─── clients_74 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_74` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 74)';

-- ─── revoked_tokens_74 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_74` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 74)';

-- ─── admin_audit_74 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_74` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 74)';

-- ─── clients_75 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_75` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 75)';

-- ─── revoked_tokens_75 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_75` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 75)';

-- ─── admin_audit_75 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_75` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 75)';

-- ─── clients_76 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_76` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 76)';

-- ─── revoked_tokens_76 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_76` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 76)';

-- ─── admin_audit_76 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_76` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 76)';

-- ─── clients_77 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_77` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 77)';

-- ─── revoked_tokens_77 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_77` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 77)';

-- ─── admin_audit_77 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_77` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 77)';

-- ─── clients_78 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_78` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 78)';

-- ─── revoked_tokens_78 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_78` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 78)';

-- ─── admin_audit_78 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_78` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 78)';

-- ─── clients_79 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_79` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 79)';

-- ─── revoked_tokens_79 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_79` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 79)';

-- ─── admin_audit_79 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_79` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 79)';

-- ────────────────── shard 7 init done ──────────────────
