-- AUTO-GENERATED by generate.sh — do not edit by hand
-- 物理库: oauth2_db_9
-- 持有: clients_90..99, revoked_tokens_90..99, admin_audit_90..99

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `oauth2_db_9` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `oauth2_db_9`;

-- ─── clients_90 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_90` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 90)';

-- ─── revoked_tokens_90 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_90` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 90)';

-- ─── admin_audit_90 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_90` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 90)';

-- ─── clients_91 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_91` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 91)';

-- ─── revoked_tokens_91 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_91` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 91)';

-- ─── admin_audit_91 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_91` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 91)';

-- ─── clients_92 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_92` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 92)';

-- ─── revoked_tokens_92 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_92` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 92)';

-- ─── admin_audit_92 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_92` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 92)';

-- ─── clients_93 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_93` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 93)';

-- ─── revoked_tokens_93 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_93` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 93)';

-- ─── admin_audit_93 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_93` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 93)';

-- ─── clients_94 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_94` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 94)';

-- ─── revoked_tokens_94 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_94` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 94)';

-- ─── admin_audit_94 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_94` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 94)';

-- ─── clients_95 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_95` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 95)';

-- ─── revoked_tokens_95 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_95` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 95)';

-- ─── admin_audit_95 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_95` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 95)';

-- ─── clients_96 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_96` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 96)';

-- ─── revoked_tokens_96 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_96` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 96)';

-- ─── admin_audit_96 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_96` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 96)';

-- ─── clients_97 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_97` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 97)';

-- ─── revoked_tokens_97 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_97` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 97)';

-- ─── admin_audit_97 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_97` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 97)';

-- ─── clients_98 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_98` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 98)';

-- ─── revoked_tokens_98 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_98` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 98)';

-- ─── admin_audit_98 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_98` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 98)';

-- ─── clients_99 ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `clients_99` (
  `id`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id`       VARCHAR(128)    NOT NULL,
  `secret_hash`     VARCHAR(255)    NOT NULL,
  `secret_last4`    VARCHAR(8)      NOT NULL,
  `name`            VARCHAR(255)    NOT NULL,
  `owner_type`      ENUM('merchant','service','ops') NOT NULL,
  `owner_id`        VARCHAR(128)    NOT NULL,
  `allowed_scopes`  TEXT            NOT NULL,
  `allowed_ips`     TEXT            NULL,
  `rate_limit_rps`  INT             NOT NULL DEFAULT 0,
  `status`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  `expires_at`      DATETIME        NULL,
  `last_used_at`    DATETIME        NULL,
  `created_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_id` (`client_id`),
  KEY `idx_owner`         (`owner_type`, `owner_id`),
  KEY `idx_status`        (`status`),
  KEY `idx_last_used`     (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard 99)';

-- ─── revoked_tokens_99 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `revoked_tokens_99` (
  `jti`         VARCHAR(128) NOT NULL,
  `revoked_at`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expires_at`  DATETIME     NOT NULL,
  `client_id`   VARCHAR(128) NULL,
  PRIMARY KEY (`jti`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_client`  (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard 99)';

-- ─── admin_audit_99 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `admin_audit_99` (
  `id`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `occurred_at`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor`        VARCHAR(128)    NOT NULL,
  `action`       VARCHAR(64)     NOT NULL,
  `client_id`    VARCHAR(128)    NULL,
  `source_ip`    VARCHAR(64)     NULL,
  `details`      JSON            NULL,
  `prev_hash`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  `row_hash`     CHAR(64)        NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor`     (`actor`),
  KEY `idx_client`    (`client_id`),
  KEY `idx_occurred`  (`occurred_at`),
  KEY `idx_action`    (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard 99)';

-- ────────────────── shard 9 init done ──────────────────
