#!/usr/bin/env bash
# generate.sh — 生成 10 个独立 init SQL 文件 (0_init.sql..9_init.sql).
#
# 跟 user-merchant-core/database/userdb/init 同模式:
#   每个文件对应一个物理 DB, 含该 DB 上 10 张分片表 × 3 类 = 30 张表
#   (oauth2_db_0 额外加 rsa_keys + client_index 两张全局单表)
#
# 部署:
#   bash generate.sh                              # 写出 0_init.sql..9_init.sql
#   for i in 0 1 2 3 4 5 6 7 8 9; do
#     mysql -h <host_$i> -uroot -p < ${i}_init.sql
#   done
#
# 或单机多 DB (dev) 同主机:
#   for i in 0 1 2 3 4 5 6 7 8 9; do
#     mysql -h localhost -uroot -p < ${i}_init.sql
#   done

set -euo pipefail

# 在脚本目录里写, 跟当前 init/ 同级.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# 模板: 一张分片表的 SQL — 用 NN 占位, 调用方 sed 替换
emit_clients() {
  local NN=$1
  cat <<EOF

-- ─── clients_${NN} ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS \`clients_${NN}\` (
  \`id\`              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  \`client_id\`       VARCHAR(128)    NOT NULL,
  \`secret_hash\`     VARCHAR(255)    NOT NULL,
  \`secret_last4\`    VARCHAR(8)      NOT NULL,
  \`name\`            VARCHAR(255)    NOT NULL,
  \`owner_type\`      ENUM('merchant','service','ops') NOT NULL,
  \`owner_id\`        VARCHAR(128)    NOT NULL,
  \`allowed_scopes\`  TEXT            NOT NULL,
  \`allowed_ips\`     TEXT            NULL,
  \`rate_limit_rps\`  INT             NOT NULL DEFAULT 0,
  \`status\`          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  \`expires_at\`      DATETIME        NULL,
  \`last_used_at\`    DATETIME        NULL,
  \`created_at\`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\`      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uk_client_id\` (\`client_id\`),
  KEY \`idx_owner\`         (\`owner_type\`, \`owner_id\`),
  KEY \`idx_status\`        (\`status\`),
  KEY \`idx_last_used\`     (\`last_used_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OAuth2 客户端 (shard ${NN})';
EOF
}

emit_revoked() {
  local NN=$1
  cat <<EOF

-- ─── revoked_tokens_${NN} ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS \`revoked_tokens_${NN}\` (
  \`jti\`         VARCHAR(128) NOT NULL,
  \`revoked_at\`  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`expires_at\`  DATETIME     NOT NULL,
  \`client_id\`   VARCHAR(128) NULL,
  PRIMARY KEY (\`jti\`),
  KEY \`idx_expires\` (\`expires_at\`),
  KEY \`idx_client\`  (\`client_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='token revocation 黑名单 (shard ${NN})';
EOF
}

emit_audit() {
  local NN=$1
  cat <<EOF

-- ─── admin_audit_${NN} ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS \`admin_audit_${NN}\` (
  \`id\`           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  \`occurred_at\`  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`actor\`        VARCHAR(128)    NOT NULL,
  \`action\`       VARCHAR(64)     NOT NULL,
  \`client_id\`    VARCHAR(128)    NULL,
  \`source_ip\`    VARCHAR(64)     NULL,
  \`details\`      JSON            NULL,
  \`prev_hash\`    CHAR(64)        DEFAULT NULL COMMENT 'per-actor chain head',
  \`row_hash\`     CHAR(64)        NOT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_actor\`     (\`actor\`),
  KEY \`idx_client\`    (\`client_id\`),
  KEY \`idx_occurred\`  (\`occurred_at\`),
  KEY \`idx_action\`    (\`action\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='admin 操作审计 (shard ${NN})';
EOF
}

# 全局单表 — 只在 oauth2_db_0 上
emit_global() {
  cat <<'EOF'

-- ─── rsa_keys (全局单表, 不分片; key 数量极少) ─────────────────
CREATE TABLE IF NOT EXISTS `rsa_keys` (
  `kid`          VARCHAR(64)  NOT NULL,
  `private_pem`  TEXT         NOT NULL COMMENT '生产建议 KMS envelope 加密',
  `public_pem`   TEXT         NOT NULL,
  `status`       ENUM('active','retired') NOT NULL DEFAULT 'active',
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `retired_at`   DATETIME(3)  NULL,
  PRIMARY KEY (`kid`),
  KEY `idx_status` (`status`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='RSA 签名 key (active + retired)';

-- ─── client_index (全局 client_id → shard 映射; ops 反查 / 跨 shard 用) ──
CREATE TABLE IF NOT EXISTS `client_index` (
  `client_id`    VARCHAR(128) NOT NULL,
  `db_index`     TINYINT      NOT NULL,
  `table_index`  TINYINT      NOT NULL,
  `created_at`   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`client_id`),
  KEY `idx_shard` (`db_index`, `table_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='全局 client_id → (db,table) 映射';
EOF
}

# 主循环: 生成 10 个 init SQL
for i in 0 1 2 3 4 5 6 7 8 9; do
  out="${i}_init.sql"
  {
    cat <<EOF
-- AUTO-GENERATED by generate.sh — do not edit by hand
-- 物理库: oauth2_db_${i}
-- 持有: clients_${i}0..${i}9, revoked_tokens_${i}0..${i}9, admin_audit_${i}0..${i}9
EOF
    [[ $i -eq 0 ]] && echo "-- 额外: rsa_keys + client_index (全局单表)"
    echo
    echo "SET NAMES utf8mb4;"
    echo "CREATE DATABASE IF NOT EXISTS \`oauth2_db_${i}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
    echo "USE \`oauth2_db_${i}\`;"

    # 该 db 上的 10 张 × 3 类 = 30 张分片表
    for j in 0 1 2 3 4 5 6 7 8 9; do
      NN=$(printf "%d%d" "$i" "$j")
      emit_clients "$NN"
      emit_revoked "$NN"
      emit_audit "$NN"
    done

    # oauth2_db_0 加全局单表
    [[ $i -eq 0 ]] && emit_global

    echo
    echo "-- ────────────────── shard ${i} init done ──────────────────"
  } > "$out"
  echo "✓ wrote $out ($(wc -l < "$out") lines)"
done

echo ""
echo "✅ 10 个 init SQL 生成完毕。部署:"
echo "   for i in 0 1 2 3 4 5 6 7 8 9; do mysql -h <host_\$i> -uroot -p < \${i}_init.sql; done"
