#!/usr/bin/env bash
# generate.sh — 把模板 SQL 扩展成 100 张分片表。
#
# 输入: 01_schema_sharded.sql (含 _00 模板)
# 输出: 02_schema_full.sql (含 _00 .. _99 全 100 张表 + 10 个 USE 语句)
#
# 跑:
#   bash generate.sh > 02_schema_full.sql
#   mysql -h <host> -uroot -p < 02_schema_full.sql

set -euo pipefail

cat <<EOF
-- AUTO-GENERATED by generate.sh — do not edit by hand
-- 100 shard tables: clients_NN, revoked_tokens_NN, admin_audit_NN
--   where NN = 00..99
--   shard NN is on DB oauth2_db_(NN/10)

EOF

# 10 库
for i in $(seq 0 9); do
  echo "CREATE DATABASE IF NOT EXISTS oauth2_db_${i} DEFAULT CHARACTER SET utf8mb4;"
done
echo ""

# 100 张表 (每 10 个落一个 DB)
for n in $(seq 0 99); do
  nn=$(printf "%02d" $n)
  db_idx=$((n / 10))
  echo "USE oauth2_db_${db_idx};"
  cat <<EOF

CREATE TABLE IF NOT EXISTS \`clients_${nn}\` (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_id       VARCHAR(128) NOT NULL,
  secret_hash     VARCHAR(255) NOT NULL,
  secret_last4    VARCHAR(8)   NOT NULL,
  name            VARCHAR(255) NOT NULL,
  owner_type      ENUM('merchant','service','ops') NOT NULL,
  owner_id        VARCHAR(128) NOT NULL,
  allowed_scopes  TEXT NOT NULL,
  allowed_ips     TEXT NULL,
  rate_limit_rps  INT NOT NULL DEFAULT 0,
  status          ENUM('active','suspended','revoked') NOT NULL DEFAULT 'active',
  expires_at      DATETIME NULL,
  last_used_at    DATETIME NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_client_id (client_id),
  KEY idx_owner (owner_type, owner_id),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS \`revoked_tokens_${nn}\` (
  jti          VARCHAR(128) NOT NULL,
  revoked_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at   DATETIME NOT NULL,
  client_id    VARCHAR(128) NULL,
  PRIMARY KEY (jti),
  KEY idx_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS \`admin_audit_${nn}\` (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  occurred_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor        VARCHAR(128) NOT NULL,
  action       VARCHAR(64)  NOT NULL,
  client_id    VARCHAR(128) NULL,
  source_ip    VARCHAR(64)  NULL,
  details      JSON NULL,
  prev_hash    CHAR(64)     DEFAULT NULL,
  row_hash     CHAR(64)     DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_actor (actor),
  KEY idx_client (client_id),
  KEY idx_occurred (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
EOF
done

# 全局单表
cat <<'EOF'

USE oauth2_db_0;

CREATE TABLE IF NOT EXISTS `rsa_keys` (
  kid          VARCHAR(64)  NOT NULL,
  private_pem  TEXT         NOT NULL,
  public_pem   TEXT         NOT NULL,
  status       ENUM('active','retired') NOT NULL DEFAULT 'active',
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  retired_at   DATETIME NULL,
  PRIMARY KEY (kid),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `client_index` (
  client_id    VARCHAR(128) NOT NULL,
  db_index     TINYINT      NOT NULL,
  table_index  TINYINT      NOT NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (client_id),
  KEY idx_shard (db_index, table_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
EOF
