FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/{{.ServiceName}} ./cmd/server

FROM alpine:3.20
RUN apk add --no-cache ca-certificates && addgroup -S app && adduser -S app -G app
WORKDIR /app
COPY --from=build /out/{{.ServiceName}} /app/{{.ServiceName}}
USER app
EXPOSE {{.DefaultPort}}
ENTRYPOINT ["/app/{{.ServiceName}}"]
