// Code generated by Kitex v0.16.2. DO NOT EDIT.

package idservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	v1 "github.com/xiongwp/id-generator/kitex_gen/idgen/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetID(ctx context.Context, Req *v1.IDRequest, callOptions ...callopt.Option) (r *v1.IDResponse, err error)
	GetIDs(ctx context.Context, Req *v1.BatchRequest, callOptions ...callopt.Option) (r *v1.BatchResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kIDServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIDServiceClient struct {
	*kClient
}

func (p *kIDServiceClient) GetID(ctx context.Context, Req *v1.IDRequest, callOptions ...callopt.Option) (r *v1.IDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetID(ctx, Req)
}

func (p *kIDServiceClient) GetIDs(ctx context.Context, Req *v1.BatchRequest, callOptions ...callopt.Option) (r *v1.BatchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetIDs(ctx, Req)
}
