// Code generated by Kitex v0.16.2. DO NOT EDIT.

package paymentintentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	orderv1 "github.com/xiongwp/order-core/kitex_gen/order/v1"
	v1 "github.com/xiongwp/order-core/kitex_gen/order/v1"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Create": kitex.NewMethodInfo(
		createHandler,
		newCreateArgs,
		newCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Retrieve": kitex.NewMethodInfo(
		retrieveHandler,
		newRetrieveArgs,
		newRetrieveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Update": kitex.NewMethodInfo(
		updateHandler,
		newUpdateArgs,
		newUpdateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Confirm": kitex.NewMethodInfo(
		confirmHandler,
		newConfirmArgs,
		newConfirmResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfirmPaymentAction": kitex.NewMethodInfo(
		confirmPaymentActionHandler,
		newConfirmPaymentActionArgs,
		newConfirmPaymentActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Capture": kitex.NewMethodInfo(
		captureHandler,
		newCaptureArgs,
		newCaptureResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Cancel": kitex.NewMethodInfo(
		cancelHandler,
		newCancelArgs,
		newCancelResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"List": kitex.NewMethodInfo(
		listHandler,
		newListArgs,
		newListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	paymentIntentServiceServiceInfo                = NewServiceInfo()
	paymentIntentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentIntentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentIntentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentIntentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentIntentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentIntentService"
	handlerType := (*orderv1.PaymentIntentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreatePaymentIntentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).Create(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateArgs:
		success, err := handler.(orderv1.PaymentIntentService).Create(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateArgs() interface{} {
	return &CreateArgs{}
}

func newCreateResult() interface{} {
	return &CreateResult{}
}

type CreateArgs struct {
	Req *v1.CreatePaymentIntentRequest
}

func (p *CreateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreatePaymentIntentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateArgs_Req_DEFAULT *v1.CreatePaymentIntentRequest

func (p *CreateArgs) GetReq() *v1.CreatePaymentIntentRequest {
	if !p.IsSetReq() {
		return CreateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateResult struct {
	Success *v1.CreatePaymentIntentResponse
}

var CreateResult_Success_DEFAULT *v1.CreatePaymentIntentResponse

func (p *CreateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateResult) Unmarshal(in []byte) error {
	msg := new(v1.CreatePaymentIntentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateResult) GetSuccess() *v1.CreatePaymentIntentResponse {
	if !p.IsSetSuccess() {
		return CreateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreatePaymentIntentResponse)
}

func (p *CreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateResult) GetResult() interface{} {
	return p.Success
}

func retrieveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RetrievePaymentIntentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).Retrieve(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RetrieveArgs:
		success, err := handler.(orderv1.PaymentIntentService).Retrieve(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RetrieveResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRetrieveArgs() interface{} {
	return &RetrieveArgs{}
}

func newRetrieveResult() interface{} {
	return &RetrieveResult{}
}

type RetrieveArgs struct {
	Req *v1.RetrievePaymentIntentRequest
}

func (p *RetrieveArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RetrieveArgs) Unmarshal(in []byte) error {
	msg := new(v1.RetrievePaymentIntentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RetrieveArgs_Req_DEFAULT *v1.RetrievePaymentIntentRequest

func (p *RetrieveArgs) GetReq() *v1.RetrievePaymentIntentRequest {
	if !p.IsSetReq() {
		return RetrieveArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RetrieveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RetrieveArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RetrieveResult struct {
	Success *v1.RetrievePaymentIntentResponse
}

var RetrieveResult_Success_DEFAULT *v1.RetrievePaymentIntentResponse

func (p *RetrieveResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RetrieveResult) Unmarshal(in []byte) error {
	msg := new(v1.RetrievePaymentIntentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RetrieveResult) GetSuccess() *v1.RetrievePaymentIntentResponse {
	if !p.IsSetSuccess() {
		return RetrieveResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RetrieveResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.RetrievePaymentIntentResponse)
}

func (p *RetrieveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RetrieveResult) GetResult() interface{} {
	return p.Success
}

func updateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdatePaymentIntentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).Update(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateArgs:
		success, err := handler.(orderv1.PaymentIntentService).Update(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateArgs() interface{} {
	return &UpdateArgs{}
}

func newUpdateResult() interface{} {
	return &UpdateResult{}
}

type UpdateArgs struct {
	Req *v1.UpdatePaymentIntentRequest
}

func (p *UpdateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdatePaymentIntentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateArgs_Req_DEFAULT *v1.UpdatePaymentIntentRequest

func (p *UpdateArgs) GetReq() *v1.UpdatePaymentIntentRequest {
	if !p.IsSetReq() {
		return UpdateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateResult struct {
	Success *v1.UpdatePaymentIntentResponse
}

var UpdateResult_Success_DEFAULT *v1.UpdatePaymentIntentResponse

func (p *UpdateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateResult) Unmarshal(in []byte) error {
	msg := new(v1.UpdatePaymentIntentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateResult) GetSuccess() *v1.UpdatePaymentIntentResponse {
	if !p.IsSetSuccess() {
		return UpdateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.UpdatePaymentIntentResponse)
}

func (p *UpdateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateResult) GetResult() interface{} {
	return p.Success
}

func confirmHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ConfirmPaymentIntentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).Confirm(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfirmArgs:
		success, err := handler.(orderv1.PaymentIntentService).Confirm(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfirmResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfirmArgs() interface{} {
	return &ConfirmArgs{}
}

func newConfirmResult() interface{} {
	return &ConfirmResult{}
}

type ConfirmArgs struct {
	Req *v1.ConfirmPaymentIntentRequest
}

func (p *ConfirmArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfirmArgs) Unmarshal(in []byte) error {
	msg := new(v1.ConfirmPaymentIntentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfirmArgs_Req_DEFAULT *v1.ConfirmPaymentIntentRequest

func (p *ConfirmArgs) GetReq() *v1.ConfirmPaymentIntentRequest {
	if !p.IsSetReq() {
		return ConfirmArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfirmArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfirmArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfirmResult struct {
	Success *v1.ConfirmPaymentIntentResponse
}

var ConfirmResult_Success_DEFAULT *v1.ConfirmPaymentIntentResponse

func (p *ConfirmResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfirmResult) Unmarshal(in []byte) error {
	msg := new(v1.ConfirmPaymentIntentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfirmResult) GetSuccess() *v1.ConfirmPaymentIntentResponse {
	if !p.IsSetSuccess() {
		return ConfirmResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfirmResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ConfirmPaymentIntentResponse)
}

func (p *ConfirmResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfirmResult) GetResult() interface{} {
	return p.Success
}

func confirmPaymentActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ConfirmPaymentActionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).ConfirmPaymentAction(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfirmPaymentActionArgs:
		success, err := handler.(orderv1.PaymentIntentService).ConfirmPaymentAction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfirmPaymentActionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfirmPaymentActionArgs() interface{} {
	return &ConfirmPaymentActionArgs{}
}

func newConfirmPaymentActionResult() interface{} {
	return &ConfirmPaymentActionResult{}
}

type ConfirmPaymentActionArgs struct {
	Req *v1.ConfirmPaymentActionRequest
}

func (p *ConfirmPaymentActionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfirmPaymentActionArgs) Unmarshal(in []byte) error {
	msg := new(v1.ConfirmPaymentActionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfirmPaymentActionArgs_Req_DEFAULT *v1.ConfirmPaymentActionRequest

func (p *ConfirmPaymentActionArgs) GetReq() *v1.ConfirmPaymentActionRequest {
	if !p.IsSetReq() {
		return ConfirmPaymentActionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfirmPaymentActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfirmPaymentActionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfirmPaymentActionResult struct {
	Success *v1.ConfirmPaymentActionResponse
}

var ConfirmPaymentActionResult_Success_DEFAULT *v1.ConfirmPaymentActionResponse

func (p *ConfirmPaymentActionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfirmPaymentActionResult) Unmarshal(in []byte) error {
	msg := new(v1.ConfirmPaymentActionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfirmPaymentActionResult) GetSuccess() *v1.ConfirmPaymentActionResponse {
	if !p.IsSetSuccess() {
		return ConfirmPaymentActionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfirmPaymentActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ConfirmPaymentActionResponse)
}

func (p *ConfirmPaymentActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfirmPaymentActionResult) GetResult() interface{} {
	return p.Success
}

func captureHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CapturePaymentIntentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).Capture(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CaptureArgs:
		success, err := handler.(orderv1.PaymentIntentService).Capture(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CaptureResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCaptureArgs() interface{} {
	return &CaptureArgs{}
}

func newCaptureResult() interface{} {
	return &CaptureResult{}
}

type CaptureArgs struct {
	Req *v1.CapturePaymentIntentRequest
}

func (p *CaptureArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CaptureArgs) Unmarshal(in []byte) error {
	msg := new(v1.CapturePaymentIntentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CaptureArgs_Req_DEFAULT *v1.CapturePaymentIntentRequest

func (p *CaptureArgs) GetReq() *v1.CapturePaymentIntentRequest {
	if !p.IsSetReq() {
		return CaptureArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CaptureArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CaptureArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CaptureResult struct {
	Success *v1.CapturePaymentIntentResponse
}

var CaptureResult_Success_DEFAULT *v1.CapturePaymentIntentResponse

func (p *CaptureResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CaptureResult) Unmarshal(in []byte) error {
	msg := new(v1.CapturePaymentIntentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CaptureResult) GetSuccess() *v1.CapturePaymentIntentResponse {
	if !p.IsSetSuccess() {
		return CaptureResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CaptureResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CapturePaymentIntentResponse)
}

func (p *CaptureResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CaptureResult) GetResult() interface{} {
	return p.Success
}

func cancelHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CancelPaymentIntentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).Cancel(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CancelArgs:
		success, err := handler.(orderv1.PaymentIntentService).Cancel(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CancelResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCancelArgs() interface{} {
	return &CancelArgs{}
}

func newCancelResult() interface{} {
	return &CancelResult{}
}

type CancelArgs struct {
	Req *v1.CancelPaymentIntentRequest
}

func (p *CancelArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CancelArgs) Unmarshal(in []byte) error {
	msg := new(v1.CancelPaymentIntentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CancelArgs_Req_DEFAULT *v1.CancelPaymentIntentRequest

func (p *CancelArgs) GetReq() *v1.CancelPaymentIntentRequest {
	if !p.IsSetReq() {
		return CancelArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CancelArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CancelArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CancelResult struct {
	Success *v1.CancelPaymentIntentResponse
}

var CancelResult_Success_DEFAULT *v1.CancelPaymentIntentResponse

func (p *CancelResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CancelResult) Unmarshal(in []byte) error {
	msg := new(v1.CancelPaymentIntentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CancelResult) GetSuccess() *v1.CancelPaymentIntentResponse {
	if !p.IsSetSuccess() {
		return CancelResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CancelResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CancelPaymentIntentResponse)
}

func (p *CancelResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CancelResult) GetResult() interface{} {
	return p.Success
}

func listHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ListPaymentIntentsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(orderv1.PaymentIntentService).List(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListArgs:
		success, err := handler.(orderv1.PaymentIntentService).List(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListArgs() interface{} {
	return &ListArgs{}
}

func newListResult() interface{} {
	return &ListResult{}
}

type ListArgs struct {
	Req *v1.ListPaymentIntentsRequest
}

func (p *ListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListArgs) Unmarshal(in []byte) error {
	msg := new(v1.ListPaymentIntentsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListArgs_Req_DEFAULT *v1.ListPaymentIntentsRequest

func (p *ListArgs) GetReq() *v1.ListPaymentIntentsRequest {
	if !p.IsSetReq() {
		return ListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListResult struct {
	Success *v1.ListPaymentIntentsResponse
}

var ListResult_Success_DEFAULT *v1.ListPaymentIntentsResponse

func (p *ListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListResult) Unmarshal(in []byte) error {
	msg := new(v1.ListPaymentIntentsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListResult) GetSuccess() *v1.ListPaymentIntentsResponse {
	if !p.IsSetSuccess() {
		return ListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ListPaymentIntentsResponse)
}

func (p *ListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Create(ctx context.Context, Req *v1.CreatePaymentIntentRequest) (r *v1.CreatePaymentIntentResponse, err error) {
	var _args CreateArgs
	_args.Req = Req
	var _result CreateResult
	if err = p.c.Call(ctx, "Create", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Retrieve(ctx context.Context, Req *v1.RetrievePaymentIntentRequest) (r *v1.RetrievePaymentIntentResponse, err error) {
	var _args RetrieveArgs
	_args.Req = Req
	var _result RetrieveResult
	if err = p.c.Call(ctx, "Retrieve", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Update(ctx context.Context, Req *v1.UpdatePaymentIntentRequest) (r *v1.UpdatePaymentIntentResponse, err error) {
	var _args UpdateArgs
	_args.Req = Req
	var _result UpdateResult
	if err = p.c.Call(ctx, "Update", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Confirm(ctx context.Context, Req *v1.ConfirmPaymentIntentRequest) (r *v1.ConfirmPaymentIntentResponse, err error) {
	var _args ConfirmArgs
	_args.Req = Req
	var _result ConfirmResult
	if err = p.c.Call(ctx, "Confirm", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfirmPaymentAction(ctx context.Context, Req *v1.ConfirmPaymentActionRequest) (r *v1.ConfirmPaymentActionResponse, err error) {
	var _args ConfirmPaymentActionArgs
	_args.Req = Req
	var _result ConfirmPaymentActionResult
	if err = p.c.Call(ctx, "ConfirmPaymentAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Capture(ctx context.Context, Req *v1.CapturePaymentIntentRequest) (r *v1.CapturePaymentIntentResponse, err error) {
	var _args CaptureArgs
	_args.Req = Req
	var _result CaptureResult
	if err = p.c.Call(ctx, "Capture", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Cancel(ctx context.Context, Req *v1.CancelPaymentIntentRequest) (r *v1.CancelPaymentIntentResponse, err error) {
	var _args CancelArgs
	_args.Req = Req
	var _result CancelResult
	if err = p.c.Call(ctx, "Cancel", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) List(ctx context.Context, Req *v1.ListPaymentIntentsRequest) (r *v1.ListPaymentIntentsResponse, err error) {
	var _args ListArgs
	_args.Req = Req
	var _result ListResult
	if err = p.c.Call(ctx, "List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
